### ISSUE TITLE
Wrong spine version

### ISSUE THREAD

**Issue by pnyet** [Cacti/spine#10]
Hi,
I just installed cacti-spine 1.0.4 from source, and I found that the version is still 1.0.3. Here is the result when I tried to ru spine -v:

# /usr/local/spine/bin/spine -v
SPINE 1.0.3  Copyright 2004-2017 by The Cacti Group

Thank you

**Comment by ronytomen** [comment]
This was a build problem on my part. 

The package script did not complain and I will have to investigate that.

The correct release has been uploaded for download.  But, to be clear there is no functional change between Spine 1.0.3 and Spine 1.0.4 other than the version.
