### ISSUE TITLE
SPINE make fails to find correct mysql client

### ISSUE THREAD

**Issue by hiddenicon** [Cacti/spine#100]
**Describe the bug**
Running a make after configure outputs this error:

/bin/sh ./libtool  --tag=CC   --mode=link gcc  -I/usr/include/net-snmp -I/usr/include/net-snmp/.. -I/usr/include/mysql -g -O2  -L/usr/lib64 -L/usr/lib64/mysql -lpthread -lssl -lm  -o spine sql.o spine.o util.o snmp.o locks.o poller.o nft_popen.o php.o ping.o keywords.o error.o  -lmariadbclient -lm -ldl -lcrypto -lz -lpthread -ldl -lm 
libtool: link: gcc -I/usr/include/net-snmp -I/usr/include/net-snmp/.. -I/usr/include/mysql -g -O2 -o spine sql.o spine.o util.o snmp.o locks.o poller.o nft_popen.o php.o ping.o keywords.o error.o  -L/usr/lib64 -L/usr/lib64/mysql -lssl -lmariadbclient -lcrypto -lz -lpthread -ldl -lm
**/usr/bin/ld: cannot find -lmariadbclient**
collect2: error: ld returned 1 exit status
make: *** [spine] Error 1

**To Reproduce**
./configure
make

**Server (please complete the following information):**
 - OS: RHEL 7.6
 - MySQL Version:
   mysql-cimprov-1.0.1-5.x86_64
   mysql-community-libs-5.7.22-1.el7.x86_64
   mysql-community-libs-compat-5.7.22-1.el7.x86_64
   mysql57-community-release-el7-11.noarch
   mysql-community-client-5.7.22-1.el7.x86_64
   mysql-community-devel-5.7.22-1.el7.x86_64
   mysql-community-common-5.7.22-1.el7.x86_64
   mysql-community-server-5.7.22-1.el7.x86_64

**Compiling (please complete the following information):**

 - compiler: gcc (GCC) 4.8.5 20150623
 - autoconf: autoconf (GNU Autoconf) 2.69
 - glibc: glibc-2.17-260
 - source: release 1.2.5

**Additional context**
Looks like the detection of mysql client in configure.ac is not finding the community version of mysql? Or I'm missing a library or?

![image](https://user-images.githubusercontent.com/10273594/62077735-d7bda500-b218-11e9-87ac-2cddff9a4051.png)

**Comment by netniV** [comment]
We look for the mysql.h file which is installed as part of the build environment for mysql.  If you don't have the mysql/mariadb's development headers installed, the above error occurs.

This can happen when distributions rename the packages (such as cygwin has recently for windows builds).

**Comment by hiddenicon** [comment]
I do have that. Is it in a non-standard directory or a directory you're not searching for?

    # find ./ -name mysql.h
     ./usr/include/mysql/mysql.h

**Comment by netniV** [comment]
Check the other compilation thread to see if anything can help you there #101.  I'm away this week so will have limited access.

**Comment by frontierliu** [comment]
hello hiddenicon and netniV, I got the same problem and I found the reason.
In configure.ac, line 263:
`AC_CHECK_LIB(mysqlclient, mysql_init,
  [ LIBS="-lmysqlclient -lm -ldl $LIBS"
    AC_DEFINE(HAVE_MYSQL, 1, MySQL Client API)
    HAVE_MYSQL=yes ],
  [ HAVE_MYSQL=no ]
)

if test -n "$MYSQL_LIB_DIR" ; then
  LDFLAGS="-L$MYSQL_LIB_DIR $LDFLAGS"
fi
CFLAGS="-I$MYSQL_INC_DIR $CFLAGS"
`
Just change the order, define LDFLAGS and CFLAGS before  AC_CHECK_LIB , because gcc use these FLAGS for compile and link check. It will be OK.

`if test -n "$MYSQL_LIB_DIR" ; then
  LDFLAGS="-L$MYSQL_LIB_DIR $LDFLAGS"
fi
CFLAGS="-I$MYSQL_INC_DIR $CFLAGS"

AC_CHECK_LIB(mysqlclient, mysql_init,
  [ LIBS="-lmysqlclient -lm -ldl $LIBS"
    AC_DEFINE(HAVE_MYSQL, 1, MySQL Client API)
    HAVE_MYSQL=yes ],
  [ HAVE_MYSQL=no ]
)
`

**Comment by hiddenicon** [comment]
@frontierliu That did the trick.  moved the LDFLAGS/CFLAGS line above the AC_CHECK_LIB section and I was now able to find the client and configure/build/make properly.

**Comment by netniV** [comment]
Can you provide a diff or pull request for the change? I'm away right now but if I had either of those I could make a quick fix.

**Comment by hiddenicon** [comment]
PR submitted, issue resolved locally when I made the change. Issue resolved and worked on 2 test linux boxes and 1 production linux box. Closing.
