### ISSUE TITLE
MySQL 8 has retired 'my_bool' type

### ISSUE THREAD

**Issue by mortenstevens** [Cacti/spine#101]
cacti-spine 1.2.5 doesn't build on RHEL8.

BUILDSTDERR: sql.c: In function 'db_connect':
BUILDSTDERR: sql.c:232:2: error: unknown type name 'my_bool'; did you mean 'bool'?
BUILDSTDERR:   my_bool reconnect = 1;
BUILDSTDERR:   ^~~~~~~
BUILDSTDERR:   bool
BUILDSTDERR: sql.c:232:10: warning: unused variable 'reconnect' [-Wunused-variable]
BUILDSTDERR:   my_bool reconnect = 1;
BUILDSTDERR:           ^~~~~~~~~
BUILDSTDERR: make: *** [Makefile:502: sql.o] Error 1
BUILDSTDERR: make: *** Waiting for unfinished jobs....

Full build log: 
https://kojipkgs.fedoraproject.org//work/tasks/6713/36766713/build.log

OS details:
https://kojipkgs.fedoraproject.org//work/tasks/6713/36766713/root.log

**Comment by TheWitness** [comment]
Ode to a Greecian Urn.  Looks like someone changed their API.  MariaDB or MySQL?  Version?

**Comment by netniV** [comment]
Has RHEL 8 even been officially released yet?

**Comment by mortenstevens** [comment]
Yes, RHEL8 has been released in May 2019.
See: https://developers.redhat.com/blog/2019/05/07/red-hat-enterprise-linux-8-now-generally-available/

It seems to be an issue with MySQL 8.0? (mysql-devel               x86_64 8.0.13-1.module+el8+2558+036183ec build 141 k)

Maybe I should use mariadb-connector-c-devel instead of mysql-devel for RHEL8. Anyway, it should also work with MySQL8?

**Comment by mortenstevens** [comment]
Update: 
After switching the build dependency from mysql-devel (8.0.13) to MariaDB (mariadb-connector-c-devel) it's building fine. 

See buildlog: https://kojipkgs.fedoraproject.org//packages/cacti-spine/1.2.5/3.el8/data/logs/x86_64/build.log

Fedora / RHEL build:
https://koji.fedoraproject.org/koji/buildinfo?buildID=1345806

Anyway, I think we should fix that for MySQL 8.0.

**Comment by netniV** [comment]
Thanks for the extra info, we will look into it.

**Comment by jer-gentoo** [comment]
https://bugs.gentoo.org/692656

**Comment by netniV** [comment]
If you do a find for `mysql.h` what locations is it found in ?

**Comment by jer-gentoo** [comment]
If I didn't completely miss the point of this report, the issue here would be:
```
BUILDSTDERR: sql.c:232:2: error: unknown type name 'my_bool'; did you mean 'bool'?
```
which is different from that other preprocessor error failing to find the `mysql.h` include. In this case, the header file *is found* but does not define `my_bool` any longer[1].


[1] https://bugs.mysql.com/85131 "Fixed in 8.0.1."

**Comment by jer-gentoo** [comment]
> which is different from that other preprocessor error failing to find the `mysql.h` include.

Which is https://github.com/Cacti/spine/issues/100 and has been fixed.

**Comment by netniV** [comment]
Yeah sorry, I was on a mobile device and got my issues mixed up.  The change of removing MY_BOOL may work or may cause older systems to throw compile errors if the type isn't truly compatible.

I guess the only way to know is replace it and see.
