### ISSUE TITLE
Spine release 1.2.4 Release is actually 1.2.3

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/spine#103]
Hey Guys 

I just noticed that on the github page for spine release 1.2.4 actually shows as 1.2.3 or the version number was not updated 

Check the configure.ac  file

AC_PREREQ(2.53)
AC_INIT(Spine Poller, 1.2.3, http://www.cacti.net/issues.php)

AC_CONFIG_AUX_DIR(config)
AC_SUBST(ac_aux_dir)

AC_CANONICAL_HOST
AC_CONFIG_SRCDIR(spine.c)
AC_PREFIX_DEFAULT(/usr/local/spine)

**Comment by netniV** [comment]
This was report in issue #95
