### ISSUE TITLE
SNMP timeout setting not being respected?

### ISSUE THREAD

**Issue by CapitalF** [Cacti/spine#11]
I am having spine poller problems that I don't understand, and am seeking assistance.

I have about 15 hosts that I am testing Cacti 1.0.3 on. Host types are MS Windows, Linux, Cisco ASAs, Cisco Small Business 300 switches (like the old Linksys SRW series), and Netgear switches.

These hosts are all working with the PHP poller. However, I am doing 1-minute graphing and two of these systems at remote sites are taking up to 45 seconds to finish their polls, so I want to reduce that time as much as possible. These two hosts are at remote sites with 50ms of latency in between, but I noticed that a lot of the latency time was in the php poller itself.

My primary problem is that I am seeing chronic intermittent "SNMP timeout" failures with spine. I am not seeing any such errors with the PHP poller.

The default SNMP timeout is 500ms, from which I started. I started getting SNMP timeout errors, so I figured I might need to raise this setting. I had never seen SNMP timeouts with the PHP poller before.

So I started raising this number slowly, but to no effect: 900ms, then 1500ms, then 3000ms.

And then I got tired of jerking around and set it to 30000.

Mar 02 20:26:07 test7 Cacti[15458]: 2017-03-02 20:26:07 - SPINE: Poller[1] Device[11] TH[1] DS[728] WARNING: SNMP timeout detected [30000 ms], ignoring host 'sw2'
Mar 02 20:26:07 test7 Cacti[15458]: 2017-03-02 20:26:07 - SPINE: Poller[1] Device[11] TH[1] DS[729] WARNING: SNMP timeout detected [30000 ms], ignoring host 'sw2'
Mar 02 20:26:07 test7 Cacti[15458]: 2017-03-02 20:26:07 - SPINE: Poller[1] Device[11] TH[1] DS[730] WARNING: SNMP timeout detected [30000 ms], ignoring host 'sw2'
Mar 02 20:26:07 test7 Cacti[15458]: 2017-03-02 20:26:07 - SPINE: Poller[1] Device[11] TH[1] DS[731] WARNING: SNMP timeout detected [30000 ms], ignoring host 'sw2'
Mar 02 20:26:07 test7 Cacti[15458]: 2017-03-02 20:26:07 - SPINE: Poller[1] Device[11] TH[1] DS[732] WARNING: SNMP timeout detected [30000 ms], ignoring host 'sw2'
Mar 02 20:26:07 test7 Cacti[15458]: 2017-03-02 20:26:07 - SPINE: Poller[1] Device[11] TH[1] DS[733] WARNING: SNMP timeout detected [30000 ms], ignoring host 'sw2'
Mar 02 20:26:07 test7 Cacti[15458]: 2017-03-02 20:26:07 - SPINE: Poller[1] Device[11] TH[1] DS[734] WARNING: SNMP timeout detected [30000 ms], ignoring host 'sw2'
Mar 02 20:26:07 test7 Cacti[15458]: 2017-03-02 20:26:07 - SPINE: Poller[1] Device[11] TH[1] DS[735] WARNING: SNMP timeout detected [30000 ms], ignoring host 'sw2'
Mar 02 20:26:07 test7 Cacti[15466]: 2017-03-02 20:26:07 - SPINE: Poller[1] Device[12] TH[1] DS[1228] WARNING: SNMP timeout detected [30000 ms], ignoring host 'sw3'
Mar 02 20:26:08 test7 Cacti[15458]: 2017-03-02 20:26:08 - SPINE: Poller[1] Device[11] TH[1] DS[736] WARNING: SNMP timeout detected [30000 ms], ignoring host 'sw2'
Mar 02 20:26:10 test7 Cacti[15402]: SYSTEM: STATS: Time:8.5303 Method:spine Processes:64 Threads:1 Hosts:20 HostsPerProcess:1 DataSources:9398 RRDsProcessed:1920

Cron runs at the 00-second mark. You can see from these double-timestamped syslog messages that we are only seven seconds into the minute and the poller has already timed out what should have been 30 seconds.

This setting isn't doing anything as far as I can tell. It doesn't matter what I set it to; the poller gives up after just a few seconds seconds every time, with no difference in how long it takes to time out. It's always timing out at the 6-8 second mark.

One difference between the PHP poller and spine is the "The Maximum SNMP OIDs Per SNMP Get Request" setting. SNMP defaults to 10, which is probably what the PHP poller users, and cacti/spine is configured for 30 by default. I have snmpbulkwalked all of my hosts and they support -Cr 30 or even 60 just fine. I tried setting this down to 10 anyway but it had no effect. Please correct me if this is wrong.

There is a notable pattern to this problem. The hosts which spine says are timing out are always the four Cisco SB 300 series switches, but it's not always the same four every time. Spine likes to pick one or two out of the four to fail on. Two will work fine, and then two will repeatedly alternate between failing and not failing, and I get massive amounts of holes in the graphs for those devices. There really isn't any patten to which devices it will pick to fail on: they are all 1-switch away on the same LAN, are the same model, and have the same number of graphs/DSs.

However, the type should have nothing to do with that timeout feature. There might be something going on where these switches are not behaving correctly, but spine isn't respecting that SNMP timeout setting one way or another. Or, it might just because they have the largest amount of DSs by far.

Ideas?

I wouldn't have filed this as a bug if it were not for the SNMP timeout thing. One way or another, something is broken there. If there is an internal hard limit, that needs to be reflected in the log messages. If the log says the timeout is 30 seconds, it needs to be 30 seconds.

**Comment by CapitalF** [comment]
Oh, I forgot the second thing. Let me know if I should file this as a separate bug.

I am seeing log messages like this:

Mar 02 20:28:06 test7 Cacti[15941]: 2017-03-02 20:28:06 - SPINE: Poller[1] Device[10] TH[1] DS[960] WARNING: SNMP timeout detected [500 ms], ignoring host 'sw1'
Mar 02 20:28:06 test7 Cacti[15941]: 2017-03-02 20:28:06 - SPINE: Poller[1] Device[10] TH[1] DS[960] WARNING: SNMP timeout detected [500 ms], ignoring host 'sw1'
Mar 02 20:28:06 test7 Cacti[15941]: 2017-03-02 20:28:06 - SPINE: Poller[1] Device[10] TH[1] DS[960] WARNING: SNMP timeout detected [500 ms], ignoring host 'sw1'
Mar 02 20:28:06 test7 Cacti[15941]: 2017-03-02 20:28:06 - SPINE: Poller[1] Device[10] TH[1] DS[960] WARNING: SNMP timeout detected [500 ms], ignoring host 'sw1'
Mar 02 20:28:06 test7 Cacti[15941]: 2017-03-02 20:28:06 - SPINE: Poller[1] Device[10] TH[1] DS[960] WARNING: SNMP timeout detected [500 ms], ignoring host 'sw1'
Mar 02 20:28:06 test7 Cacti[15941]: 2017-03-02 20:28:06 - SPINE: Poller[1] Device[10] TH[1] DS[960] WARNING: SNMP timeout detected [500 ms], ignoring host 'sw1'
Mar 02 20:28:06 test7 Cacti[15941]: 2017-03-02 20:28:06 - SPINE: Poller[1] Device[10] TH[1] DS[960] WARNING: SNMP timeout detected [500 ms], ignoring host 'sw1'
Mar 02 20:28:06 test7 Cacti[15941]: 2017-03-02 20:28:06 - SPINE: Poller[1] Device[10] TH[1] DS[960] WARNING: SNMP timeout detected [500 ms], ignoring host 'sw1'
Mar 02 20:28:06 test7 Cacti[15941]: 2017-03-02 20:28:06 - SPINE: Poller[1] Device[10] TH[1] DS[960] WARNING: SNMP timeout detected [500 ms], ignoring host 'sw1'
Mar 02 20:28:06 test7 Cacti[15941]: 2017-03-02 20:28:06 - SPINE: Poller[1] Device[10] TH[1] DS[960] WARNING: SNMP timeout detected [500 ms], ignoring host 'sw1'
Mar 02 20:28:06 test7 Cacti[15941]: 2017-03-02 20:28:06 - SPINE: Poller[1] Device[10] TH[1] DS[960] WARNING: SNMP timeout detected [500 ms], ignoring host 'sw1'


Notice how it's the same DS timing out multiple times. How is that even possible? WTF is going on there?

**Comment by cigamit** [comment]
Try reducing the number of OID's per get request.  This is equivalent to:

snmpget -v2c -c public localhost .1.3.6.blah 1.3.6.blah.b.blah .1.3.6.blah.c.blah.d.blah

It could be that it is getting a bad response in the middle and simply failing after the longer duration, or it could be that the device is not supporting so many OID's.  You should run an strace for this one and post the output.  I suspect there is a bug in either case.  The strace will help resolve the bug.

Please upload the strace once you have it.

**Comment by cigamit** [comment]
Closing due to lack of feedback.
