### ISSUE TITLE
spine 1.2.5/1.2.6  Use snmp_sess_select_info2() for processing large file descriptors

### ISSUE THREAD

**Issue by j66h** [Cacti/spine#115]
**Environment**
OS: Windows Server 2016 standard
Cacti: 1.2.5
Spine: 1.2.5/1.2.6 (tried both)
Cygwin: 3.0.7
Net-SNMP: 5.7.3 
PHP: 7.3.7
MySQL: 8.0.16

Single server. Just "Main Poller".

**Describe the bug**
Using more than 20 Threats per Spine process leads to error message "Use snmp_sess_select_info2() for processing large file descriptors". Polls will not finish  successfull. Polltime will go beyond 300 seconds.

**To Reproduce**
1. Configure spine as poller type
2. Go to "main Poller" Settings and change threats to e.g. 50
3. Run spine using:
C:\cygwin64\usr\local\spine\bin\spine.exe -R -S -V 5 -C C:\cygwin64\usr\local\spine\etc\spine.conf

**Expected behavior**
Poller run without error ;-)

**Compiling (please complete the following information):**
./bootstrap
./configure --enable-strict-snmp
make
make install

**Additional Information**
I also played arround with:
- Number of PHP Script Servers
- The Maximum SNMP OIDs Per SNMP Get Request
But these two settings had no influence on the error.

**Messages**
Messages of above call were collected in attached files:
- spine-error.txt: 50 threats
- spine-ok.txt: 15 threats

[spine-error.txt](https://github.com/Cacti/spine/files/3574301/spine-error.txt)
[spine-ok.txt](https://github.com/Cacti/spine/files/3574304/spine-ok.txt)

**Comment by netniV** [comment]
Thanks for the detailed report, we will look into this.

**Comment by netniV** [comment]
This would appear to be down to the number of devices being polled at any one given point through the Net-SNMP API.  Because they can now support a larger file descriptor, they have a separate structure that isn't compatible with the original SNMP api.  

So, when we are attempting to obtain more handles than the API can actually handle that is a problem, and the API tries to offer a warning about it.  Not quite sure how we would handle this other than to limit the number of sessions being polled at any given point across multiple instances of spine (not as easy as it sounds!)

**Comment by netniV** [comment]
Reference material:
https://sourceforge.net/p/net-snmp/mailman/net-snmp-coders/thread/201006220833111253937@163.com/

**Comment by j66h** [comment]
First of all, thanxs for all your great work! Second, I'm not a programmer :-(
That said, for me it sounds like change to new API would solve the problem. But I guess, that also is a lot of work.

My problem was, that there was nothing in cacti.log about this. Of course firing up spine on CLI showed the issue. But then I didn't find any reference which helped to solve. After several aproches today I started to play with spine options and found the issue related to threat count.

So, maybe at least someone with the same issue now can find information and set threatcount accordngly.

My system:
- cmd.php, 15 processes, poll took aproximately 90 seconds.
- spine, 5 processes, 15 threats: down to 45 seconds

Not what I hoped for, but will do for a while. I'll put CPUs into that virtual machine and increase processes if I get somewhere above 150 seconds.

So: I can deal with it.

Don't hesitate to contact me, if you find something and need sombody to test this out. At least this is somthing I can do for the project :-)

Regards, JH

**Comment by netniV** [comment]
I agree, that we should be able to trap and notify about it as long as the API is returning that to us...

**Comment by cigamit** [comment]
I'm going to make a very minor change to the spine.c.  I'm not entirely certain if this will have any impact.  The reason I'm making this change is that the winsock API in the Windows world is different from the traditional Linux/UNIX sockets implementation.  After a review of the API, there are two calls that should appear in any Windows version of spine.

**Comment by cigamit** [comment]
I've pushed the changes to the develop/1.2.x branch.  Please retest on that branch.

**Comment by cigamit** [comment]
You should also test on Linux.  When I reviewed the spine code, we are using the net-snmp generic call snmp_sess_sync_response() to gather the snmp responses.  This call automatically moves the standard file descriptors to the larger structure.

In looking at the code, it seems that this transfer of the file descriptors will fail if the new larger file descriptor name space is greater than of the operating systems FD_SETSIZE macro returns.

My guess is that on Windows/Cygwin, the macro is returning a smaller value, and therefore it's failing.  We need to rely on the net-snmp call to be performing these changes.  So, my guess either limitation in Windows/Cygwin or a bug in the snmp_sess_sync_reponse() Net-SNMP API().

**Comment by cigamit** [comment]
Yea, just checked the cygwin sys/select.h.  The FD_SETSIZE is limited to 64.  So, this means that Windows is not the best place for enterprise level Cacti if you plan on using spine.

If you don't want to give up Windows, you can try to use multiple data collectors.

I'm going to make this as not-a-problem, or third party bug.

**Comment by cigamit** [comment]
Some additional and humorous discussion on the cygwin mailing list here: https://cygwin.cygwin.narkive.com/X1jUt3Bg/fd-setsize-and-sizeof-fd-set.  Corinna has been cygwin dev for several years.
