### ISSUE TITLE
[1.2.6] bootstrap error - m4 directory

### ISSUE THREAD

**Issue by eschoeller** [Cacti/spine#116]
On an RHEL 6 system bootstrap fails:
```
./bootstrap 
INFO: Starting Spine build process
INFO: Removing cache directories
INFO: Running auto-tools to verify buildability
aclocal: couldn't open directory `m4': No such file or directory
autoreconf: aclocal failed with exit status: 1
ERROR: 'autoreconf' exited with errors
```

Debian 9 powers through it:
```
./bootstrap 
INFO: Starting Spine build process
INFO: Removing cache directories
INFO: Running auto-tools to verify buildability
aclocal: warning: couldn't open directory 'm4': No such file or directory
configure.ac:80: installing 'config/compile'
configure.ac:7: installing 'config/config.guess'
configure.ac:7: installing 'config/config.sub'
configure.ac:12: installing 'config/install-sh'
configure.ac:12: installing 'config/missing'
Makefile.am: installing 'config/depcomp'
INFO: Spine bootstrap process completed
```
I created the m4 directory by hand on the RHEL system and got through it. Not sure if this is something that can be fixed on your end or not. I tried building 1.2.4 again on both systems and had no issue.

**Comment by netniV** [comment]
I think there was a change recently for the newer configuration systems to do with the m4 directory.  Given the age of RH 6, I'm not really that bothered about supporting it so much especially given RH 8 is around the corner so I think accepting that the answer is to create the directory should be enough.

However, I'll not close this just yet as either @cigamit or @TheWitness might want to weigh in on this one.

**Comment by j66h** [comment]
I think, this was already addressed in issue #113

**Comment by netniV** [comment]
I think you are right :)

If you aren't already using the latest 1.2.x branch of spine @eschoeller, pick that up first.

**Comment by eschoeller** [comment]
Oh shucks, I'm sorry I should have looked for other reports before I posted this. I'm on the 1.2.6 tar ball right now, but I can just double check against the most recent 1.2.x pretty easily.
