### ISSUE TITLE
When calling bootstrap, an invalid error claiming config.h.in is missing can appear on first compile 

### ISSUE THREAD

**Issue by whsir** [Cacti/spine#119]
test Centos7

......
configure.ac:7: installing 'config/config.guess'
configure.ac:7: installing 'config/config.sub'
configure.ac:12: installing 'config/install-sh'
configure.ac:12: installing 'config/missing'
configure.ac:13: error: required file 'config/config.h.in' not found
Makefile.am: installing 'config/depcomp'
......

**Comment by netniV** [comment]
Did you run through the correct installation steps that are documented?

**Comment by whsir** [comment]
./bootstrap

INFO: Starting Spine build process
INFO: Removing cache directories
INFO: Running auto-tools to verify buildability
aclocal: installing 'm4/libtool.m4' from '/usr/share/aclocal/libtool.m4'
aclocal: installing 'm4/ltoptions.m4' from '/usr/share/aclocal/ltoptions.m4'
aclocal: installing 'm4/ltsugar.m4' from '/usr/share/aclocal/ltsugar.m4'
aclocal: installing 'm4/ltversion.m4' from '/usr/share/aclocal/ltversion.m4'
aclocal: installing 'm4/lt~obsolete.m4' from '/usr/share/aclocal/lt~obsolete.m4'
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `config'.
libtoolize: linking file `config/ltmain.sh'
configure.ac:7: installing 'config/config.guess'
configure.ac:7: installing 'config/config.sub'
configure.ac:12: installing 'config/install-sh'
configure.ac:12: installing 'config/missing'
**configure.ac:13: error: required file 'config/config.h.in' not found**
Makefile.am: installing 'config/depcomp'
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `config'.
libtoolize: copying file `config/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
INFO: Spine bootstrap process completed

  These instructions assume the default install location for spine
  of /usr/local/spine.  If you choose to use another prefix, make
  sure you update the commands as required for that new path.

  To compile and install Spine using MySQL versions 5.5 or higher
  please do the following:

  ./configure
  make
  make install
  chown root:root /usr/local/spine/bin/spine
  chmod +s /usr/local/spine/bin/spine

  To compile and install Spine using MySQL versions previous to 5.5
  please do the following:

  ./configure --with-reentrant
  make
  make install
  chown root:root /usr/local/spine/bin/spine
  chmod +s /usr/local/spine/bin/spine

+ ./configure
......

**Comment by netniV** [comment]
Where are you sourcing 1.2.7 from?

**Comment by whsir** [comment]
https://github.com/Cacti/spine/archive/release/1.2.7.tar.gz

**Comment by whsir** [comment]
flow

1、init Centos7.6
2、yum install automake dos2unix libtool* ......
3、wget https://github.com/Cacti/spine/archive/release/1.2.7.tar.gz
4、cd spine-release-1.2.7
./bootstrap

**Comment by whsir** [comment]
```shell
INFO: Starting Spine build process
INFO: Removing cache directories
INFO: Running auto-tools to verify buildability
aclocal: installing 'm4/libtool.m4' from '/usr/share/aclocal/libtool.m4'
aclocal: installing 'm4/ltoptions.m4' from '/usr/share/aclocal/ltoptions.m4'
aclocal: installing 'm4/ltsugar.m4' from '/usr/share/aclocal/ltsugar.m4'
aclocal: installing 'm4/ltversion.m4' from '/usr/share/aclocal/ltversion.m4'
aclocal: installing 'm4/lt~obsolete.m4' from '/usr/share/aclocal/lt~obsolete.m4'
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `config'.
libtoolize: linking file `config/ltmain.sh'
configure.ac:7: installing 'config/config.guess'
configure.ac:7: installing 'config/config.sub'
configure.ac:12: installing 'config/install-sh'
configure.ac:12: installing 'config/missing'
configure.ac:13: error: required file 'config/config.h.in' not found
Makefile.am: installing 'config/depcomp'
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `config'.
libtoolize: copying file `config/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
INFO: Spine bootstrap process completed

  These instructions assume the default install location for spine
  of /usr/local/spine.  If you choose to use another prefix, make
  sure you update the commands as required for that new path.

  To compile and install Spine using MySQL versions 5.5 or higher
  please do the following:

  ./configure
  make
  make install
  chown root:root /usr/local/spine/bin/spine
  chmod +s /usr/local/spine/bin/spine

  To compile and install Spine using MySQL versions previous to 5.5
  please do the following:

  ./configure --with-reentrant
  make
  make install
  chown root:root /usr/local/spine/bin/spine
  chmod +s /usr/local/spine/bin/spine
```
./bootstrap

```shell
INFO: Starting Spine build process
INFO: Removing cache directories
INFO: Running auto-tools to verify buildability
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `config'.
libtoolize: copying file `config/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
INFO: Spine bootstrap process completed

  These instructions assume the default install location for spine
  of /usr/local/spine.  If you choose to use another prefix, make
  sure you update the commands as required for that new path.

  To compile and install Spine using MySQL versions 5.5 or higher
  please do the following:

  ./configure
  make
  make install
  chown root:root /usr/local/spine/bin/spine
  chmod +s /usr/local/spine/bin/spine

  To compile and install Spine using MySQL versions previous to 5.5
  please do the following:

  ./configure --with-reentrant
  make
  make install
  chown root:root /usr/local/spine/bin/spine
  chmod +s /usr/local/spine/bin/spine
```

**Comment by whsir** [comment]
cd ..
rm -rf spine-release-1.2.7
tar xf spine-release-1.2.7.tar.gz
cd spine-release-1.2.7

**Comment by whsir** [comment]
./bootstrap

```shell
INFO: Starting Spine build process
INFO: Removing cache directories
INFO: Running auto-tools to verify buildability
aclocal: installing 'm4/libtool.m4' from '/usr/share/aclocal/libtool.m4'
aclocal: installing 'm4/ltoptions.m4' from '/usr/share/aclocal/ltoptions.m4'
aclocal: installing 'm4/ltsugar.m4' from '/usr/share/aclocal/ltsugar.m4'
aclocal: installing 'm4/ltversion.m4' from '/usr/share/aclocal/ltversion.m4'
aclocal: installing 'm4/lt~obsolete.m4' from '/usr/share/aclocal/lt~obsolete.m4'
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `config'.
libtoolize: linking file `config/ltmain.sh'
configure.ac:7: installing 'config/config.guess'
configure.ac:7: installing 'config/config.sub'
configure.ac:12: installing 'config/install-sh'
configure.ac:12: installing 'config/missing'
configure.ac:13: error: required file 'config/config.h.in' not found
Makefile.am: installing 'config/depcomp'
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `config'.
libtoolize: copying file `config/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
INFO: Spine bootstrap process completed

  These instructions assume the default install location for spine
  of /usr/local/spine.  If you choose to use another prefix, make
  sure you update the commands as required for that new path.

  To compile and install Spine using MySQL versions 5.5 or higher
  please do the following:

  ./configure
  make
  make install
  chown root:root /usr/local/spine/bin/spine
  chmod +s /usr/local/spine/bin/spine

  To compile and install Spine using MySQL versions previous to 5.5
  please do the following:

  ./configure --with-reentrant
  make
  make install
  chown root:root /usr/local/spine/bin/spine
  chmod +s /usr/local/spine/bin/spine
```

**Comment by netniV** [comment]
It seems to me that this was an environment issue like the full tar was not extracted the first time around.  Your two subsequent builds appear fine.

**Comment by whsir** [comment]
The first time you get an error！
Repeat execution normal

**Comment by whsir** [comment]
configure.ac:13: error: required file 'config/config.h.in' not found

**Comment by whsir** [comment]
I hope you can have a try. Thank you

**Comment by netniV** [comment]
So I finally had a chance to look at this, and that error has always occurred it would seem even back in 1.2.2.  However, I think there is a way to make the error disappear.

The error occurs because automake scans the configure.ac and sees that we use `AC_CONFIG_HEADERS(config/config.h)`, so it automatically assumes that there should be a `config/config.h.in`.  It doesn't actually stop anything and then when autoreconf is called, that creates the config/config.h.in from the configure.ac.

Thus the next time around, no error.

To alleviate this, we can call autoheader before we call automake or autoreconf.  As autoheader also creates `config/config.h.in` the same as autoreconf, the error is magically removed.

**Comment by TheWitness** [comment]
No updates.
