### ISSUE TITLE
Spine cause CPU usage  up to 100%

### ISSUE THREAD

**Issue by horizonlin** [Cacti/spine#12]
when set SPINE working threads  over  1,  all poller CPU usage will be 100%  except  main poller

**Comment by cigamit** [comment]
State your operating system and architecture.  Provide polling statistics, and indicate if the spine binary is setuid.

**Comment by horizonlin** [comment]
redhat 5.4   and Centos  6.4  both ,  setuid  ?  how to do it

**Comment by horizonlin** [comment]
I have  test  setuid , it is  runing 100%  also,   main poller operating system  is centos 6.8   and the another two poller is centos  6.8  64 bit.  one poller is REDHat  5.4 64 bit

**Comment by cigamit** [comment]
How many threads and processes?

**Comment by horizonlin** [comment]
one  processes , one threads    It work well.   If  threads more than one ,CPU's usage will be 100%.

**Comment by cigamit** [comment]
Run the following command using multiple threads and upload the results.  Insure you do this as the cacti user.

./spine -R -V 5 -S

**Comment by cigamit** [comment]
also, try this spine.c.  thanks.

**Comment by cigamit** [comment]
[spine.txt](https://github.com/Cacti/spine/files/871252/spine.txt)

**Comment by horizonlin** [comment]
Thanks  for your replies.  I think the problem is  that  I set spine's  owner to  cacti user  and then setuid  .  I worked at main poller  but other .
