### ISSUE TITLE
Can't compile spine on Openbsd

### ISSUE THREAD

**Issue by mikygee** [Cacti/spine#122]
Spine: 1.2.7

Hello,
I'm not able to compile spine on openbsd

export AUTOCONF_VERSION=2.69
export AUTOMAKE_VERSION=1.16
./bootstrap
./configure

make
gcc -DHAVE_CONFIG_H -I. -I./config      -I/usr/local/include/net-snmp -I/usr/local/include/net-snmp/.. -I/usr/local/include/mysql -g -O2 -MT sql.o -MD -MP -MF .deps/sql.Tpo -c -o sql.o sql.c
mv -f .deps/sql.Tpo .deps/sql.Po
...
mv -f .deps/error.Tpo .deps/error.Po

/bin/sh ./libtool  --tag=CC    --mode=link gcc  -I/usr/local/include/net-snmp -I/usr/local/include/net-snmp/.. -I/usr/local/include/mysql -g -O2   -L/usr/local/lib -L/usr/local/lib -lpthread -lssl -lm  -o spine sql.o spine.o util.o  snmp.o locks.o poller.o  nft_popen.o php.o ping.o  keywords.o error.o  -lmysqlclient -lm -ldl -lmysqlclient -lm -ldl -lcrypto -lz -lpthread -lm
libtool: link: gcc -I/usr/local/include/net-snmp -I/usr/local/include/net-snmp/.. -I/usr/local/include/mysql -g -O2 -o spine sql.o spine.o util.o snmp.o locks.o poller.o nft_popen.o php.o ping.o keywords.o error.o  -L/usr/local/lib -lssl -lmysqlclient -ldl -lcrypto -lz -lpthread -lm
ld: error: unable to find library -ldl
collect2: ld returned 1 exit status
*** Error 1 in /var/www/htdocs/applications/cacti-1.2.7/SPINE/cacti-spine-1.2.7 (Makefile:471 'spine')

They say -ldl doesn't exist on *BSD
https://reviews.llvm.org/D43168

Can we do something for that ?

Thank you

**Comment by netniV** [comment]
```diff
diff --git a/configure.ac b/configure.ac
index 688ffdf..3bdf34d 100644
--- a/configure.ac
+++ b/configure.ac
@@ -58,7 +58,7 @@ fi
 
 # Platform-specific tweaks
 ShLib="so"
-
+LDLFLAG="-ldl"
 case $host_alias in
 *sparc-sun-solaris2.8)
   CPPFLAGS="$CPPFLAGS -D_POSIX_PTHREAD_SEMANTICS"
@@ -66,6 +66,7 @@ case $host_alias in
 *solaris*)
   CPPFLAGS="$CPPFLAGS -D_POSIX_PTHREAD_SEMANTICS";;
 *freebsd*)
+  LDLFLAG=""
   LIBS="$LIBS -pthread"
   LDFLAGS="-lexecinfo"
   AC_DEFINE(HAVE_LIBPTHREAD, 1);;
@@ -278,25 +279,25 @@ fi
   CFLAGS="-I$MYSQL_INC_DIR $CFLAGS"
 
 AC_CHECK_LIB(mysqlclient, mysql_init,
-  [ LIBS="-lmysqlclient -lm -ldl $LIBS"
+  [ LIBS="-lmysqlclient -lm $LDLFLAG $LIBS"
     AC_DEFINE(HAVE_MYSQL, 1, MySQL Client API)
     HAVE_MYSQL=yes ],
   [ HAVE_MYSQL=no ]
 )
 
 if test $MYSQL_REENTRANT = 1 ; then
-  LIBS="-lmysqlclient_r -lm -ldl $LIBS"
+  LIBS="-lmysqlclient_r -lm $LDLFLAG $LIBS"
 else 
   if test -f $MYSQL_LIB_DIR/libmysqlclient_r.a -o -f $MYSQL_LIB_DIR/libmysqlclient_r.$ShLib; then
-    LIBS="-lmysqlclient_r -lm -ldl $LIBS"
+    LIBS="-lmysqlclient_r -lm $LDLFLAG $LIBS"
   else 
     if test -f $MYSQL_LIB_DIR/libmysqlclient_r.a -o -f $MYSQL_LIB_DIR/libmysqlclient_r.$ShLib ; then
-      LIBS="-lmysqlclient_r -lm -ldl $LIBS"
+      LIBS="-lmysqlclient_r -lm $LDLFLAG $LIBS"
     else
       if test "$HAVE_MYSQL" == "yes"; then
-        LIBS="-lmysqlclient -lm -ldl $LIBS"
+        LIBS="-lmysqlclient -lm $LDLFLAG $LIBS"
       else
-        LIBS="-lmariadbclient -lm -ldl $LIBS"
+        LIBS="-lmariadbclient -lm $LDLFLAG $LIBS"
       fi
     fi
   fi
```
Try that diff and see if it works for you.

**Comment by mikygee** [comment]
Hello,

Thank you for your quick answer.
I have not been able to use this patch because I use openbsd not freebsd.

1)
I tried to add in configure.ac
```
*openbsd*)
   LDLFLAG=""
   LIBS="$LIBS -pthread"
   LDFLAGS="-lexecinfo"
   AC_DEFINE(HAVE_LIBPTHREAD, 1);;
```

But for some reason it doesn't recognize openbsd
```
# ./configure
checking build system type... x86_64-unknown-openbsd6.5
checking host system type... x86_64-unknown-openbsd6.5
```

Do you know how ac_cv_host_alias is set ?

2)
If I go in the Makefile and I remove the -ldl option on this line
`LIBS = -lmysqlclient -lm -lmysqlclient -lm -lcrypto -lz -lpthread -lm`

I see
```
/bin/sh ./libtool  --tag=CC    --mode=link gcc  -I/usr/local/include/net-snmp -I/usr/local/include/net-snmp/.. -I/usr/local/include/mysql -g -O2   -L/usr/local/lib -L/usr/local/lib -lpthread -lssl -lm  -o spine sql.o spine.o util.o  snmp.o locks.o poller.o  nft_popen.o php.o ping.o  keywords.o error.o  -lmysqlclient -lm -lmysqlclient -lm -lcrypto -lz -lpthread -lm
libtool: link: gcc -I/usr/local/include/net-snmp -I/usr/local/include/net-snmp/.. -I/usr/local/include/mysql -g -O2 -o spine sql.o spine.o util.o snmp.o locks.o poller.o nft_popen.o php.o ping.o keywords.o error.o  -L/usr/local/lib -lssl -lmysqlclient -lcrypto -lz -lpthread -lm
ld: error: undefined symbol: snmp_pdu_create
>>> referenced by snmp.c:657
>>>               snmp.o:(snmp_get_multi)

ld: error: undefined symbol: snmp_add_null_var
>>> referenced by snmp.c:667
>>>               snmp.o:(snmp_get_multi)

ld: error: undefined symbol: snmp_parse_oid
>>> referenced by snmp.c:661
>>>               snmp.o:(snmp_get_multi)
```

Thanks

**Comment by netniV** [comment]
Now that I do not know because I only know a little about the AC system.  I had incorrectly read that as FreeBSD.  Basically, it would appear the automake system doesn't know about OpenBSD period.

**Comment by mikygee** [comment]
Hello,
First I wanted to thank you in your attempt to help me.

I did this
```
export AUTOCONF_VERSION=2.69
export AUTOMAKE_VERSION=1.16
./bootstrap
./configure
```
I edited the configure file and modified the default
```
*)
#  LDFLAGS="-lpthread -lssl -lm $LDFLAGS";;
  LDLFLAG=""
  LIBS="$LIBS -pthread"
  $as_echo "#define HAVE_LIBPTHREAD 1" >>confdefs.h
```
Then make

I just have a warning
```
snmp.c: In function 'snmp_host_init':
snmp.c:189: warning: 'remote_port' is deprecated (declared at /usr/local/include/net-snmp/../net-snmp/types.h:345)
```

```
./spine -v
SPINE 1.2.7  Copyright 2004-2019 by The Cacti Group
```

So I suppose it's compiled

**Comment by netniV** [comment]
That would suggest so.

**Comment by cigamit** [comment]
It would be nice if you would simply add that to the *openbsd*) case logic and submit a pull request.

**Comment by mikygee** [comment]
Hello,
I tried to add a switch but it doesn't work.
The reason is that $host_alias is empty and I didn't find where $host_alias was set

Also Openbsd doesn't want -ldl

In which file should I add that switch ?

**Comment by mikygee** [comment]
Can I have help from you guys, in which file should the switch be added ?
The switch can work only if $host_alias is not empty

**Comment by TheWitness** [comment]
@mikygee, can you test with the latest 1.2.x branch?

**Comment by mikygee** [comment]
Hello,
Still the same problem
/bin/sh ./libtool  --tag=CC    --mode=link gcc  -I/usr/local/include/net-snmp -I/usr/local/include/net-snmp/.. -I/usr/local/include/mysql -g -O2   -L/usr/local/lib -L/usr/local/lib  -o spine sql.o spine.o util.o  snmp.o locks.o poller.o  nft_popen.o php.o ping.o  keywords.o error.o  -lmysqlclient -lm -ldl -lmysqlclient -lm -ldl -lcrypto -lz -lpthread -lm -lpthread -lssl
libtool: link: gcc -I/usr/local/include/net-snmp -I/usr/local/include/net-snmp/.. -I/usr/local/include/mysql -g -O2 -o spine sql.o spine.o util.o snmp.o locks.o poller.o nft_popen.o php.o ping.o keywords.o error.o  -L/usr/local/lib -lmysqlclient -ldl -lcrypto -lz -lm -lpthread -lssl
ld: error: unable to find library -ldl
collect2: ld returned 1 exit status
*** Error 1 in /var/www/htdocs/metrologie/cacti-spine-1.2.13 (Makefile:471 'spine')

**Comment by netniV** [comment]
As there is a new thread for this now, i've locked this one.
