### ISSUE TITLE
spine debug error

### ISSUE THREAD

**Issue by majed17** [Cacti/spine#128]
` SPINE: Poller[Main Poller] PID[13097] Device[Local Linux Machine] DEBUG Falling back to UDP Ping Due to SetUID Issues `

this is on fedora latest,  5.3.15-200.fc30.x86_64,
i saw that it was an issue on freebsd last year and "stated as resolved"

i did not compile, but installed from their repository, cacti version 1.2.7
selinux is disabled
thoughts?

**Comment by netniV** [comment]
Check that spine is owned by root and +s has been applied.

**Comment by majed17** [comment]
thanks that solved the problem
