### ISSUE TITLE
Repeated warnings due to 'Recache Event Detected for Device'

### ISSUE THREAD

**Issue by gvoitis** [Cacti/spine#129]
Hello,

If I switch  Re-Index Method to Verify All I have this error:

2019/12/15 05:37:34 - PCOMMAND Device[POP] WARNING: Recache Event Detected for Device
2019/12/15 05:37:33 - SPINE: Poller[Main Poller] PID[20883] Device[POP] HT[6] DQ[SNMP - Interface Statistics] RECACHE ASSERT FAILED: '\\\"Fa1\\\"=\"Fa1\"'
2019/12/15 05:37:33 - SPINE: Poller[Main Poller] PID[20883] Device[POP] HT[5] DQ[SNMP - Interface Statistics] RECACHE ASSERT FAILED: '\\\"Fa1\\\"=\"Fa1\"'
2019/12/15 05:37:33 - SPINE: Poller[Main Poller] PID[20883] Device[POP] HT[4] DQ[SNMP - Interface Statistics] RECACHE ASSERT FAILED: '\\\"Fa1\\\"=\"Fa1\"'

If I go back to Index Count, Uptime or None this problem is gone.

My configuration is:
http://prntscr.com/qazfsf
http://prntscr.com/qazg30

Thanks!
Gabriel

**Comment by cigamit** [comment]
Grab the latest branch 1.2.x of poller.c, then remake and install.  Should be resolved.

**Comment by gvoitis** [comment]
Thanks,  can you help me where i can find it ?

**Comment by cigamit** [comment]
Go to the code section of the spine page, and then pick the 1.2.x branch.  Then, 'Clone or Download' it.

**Comment by a-vasilishin** [comment]
I have the same problem, all log of such entries:

> 2020/03/29 00:50:10 - SPINE: Poller[Main Poller] PID[20441] Device[c11 (FDC)] HT[1] DQ[SNMP - Interface Statistics] RECACHE ASSERT FAILED: 'lo=\"lo\"'
> 2020/03/29 00:50:10 - SPINE: Poller[Main Poller] PID[20441] Device[s12] HT[1] DQ[SNMP - Interface Statistics] RECACHE ASSERT FAILED: 'lo=\"lo\"'
> 2020/03/29 00:50:10 - SPINE: Poller[Main Poller] PID[20441] Device[s11] HT[1] DQ[SNMP - Interface Statistics] RECACHE ASSERT FAILED: 'lo=\"lo\"'


> 2020/03/29 00:51:42 - PCOMMAND Device[s12] WARNING: Recache Event Detected for Device
> 2020/03/29 00:51:41 - PCOMMAND Device[c24 (FDC)] WARNING: Recache Event Detected for Device
> 2020/03/29 00:51:40 - PCOMMAND Device[c23 (FDC)] WARNING: Recache Event Detected for Device
> 2020/03/29 00:51:40 - PCOMMAND Device[c21 (FDC)] WARNING: Recache Event Detected for Device

Spine latest from  1.2.x branch

**Comment by TheWitness** [comment]
This should be working now.  Was able to reproduce and fix.

**Comment by sigilxz** [comment]
I had run into the same issue, and finally got around to cleaning up my patch submit an issue for this.

Mine was basically the same, however I have one other change. I made a similar change as you did to snmp_get function to the snmp_getnext function as well.

Here is what remains of my patch:
```
diff -ur cacti-spine-1.2.9/snmp.c cacti-spine-1.2.9.new/snmp.c
--- cacti-spine-1.2.11/snmp.c	2019-02-24 09:53:23.000000000 -0500
+++ cacti-spine-1.2.11.new/snmp.c	2019-06-12 13:27:12.614489133 -0400
@@ -466,7 +466,7 @@
 					if (vars != NULL) {
 						snprint_value(temp_result, RESULTS_BUFFER, vars->name, vars->name_length, vars);
 
-						snprint_asciistring(result_string, RESULTS_BUFFER, temp_result, strlen(temp_result));
+						snprintf(result_string, RESULTS_BUFFER, "%s", trim(temp_result));
 					} else {
 						SET_UNDEFINED(result_string);
 						status = STAT_ERROR;

```

Thanks for the very useful tool. Also, I should mention that I originally started using spine because the 'standard' poller had similar issues. They may or may not still be present there...
