### ISSUE TITLE
Segmentation Fault triggered by a lot of errors

### ISSUE THREAD

**Issue by lucanLepus** [Cacti/spine#130]
Hello,
I recently ran into a Segfault when my polling script returned loads of empty results.

I believe this is due to improper usage of the return value of `snprintf` in `poller.c` in the lines that look like this:

```
 error_len += snprintf(error_string+error_len, DBL_BUFSIZE-error_len, ...)
```

because **snprintf returns the number of bytes it would have written** if the buffer was big enough, **not the bytes actually written**.

So once error_string is full, snprintf truncates the string correctly, but the value of error_len will become bigger than DBL_BUFSIZE, leading to memory corruption/UB the next time such a line is executed.

Not sure what the proper fix would be, so i thought i just leave this here before heading in the holidays.

Kind regards,
LucanLepus

**Comment by cigamit** [comment]
Let me take a crack at something a bit more efficient.

**Comment by cigamit** [comment]
This could have gone further.  In the mean time, please test.

**Comment by lucanLepus** [comment]
Hello,
thanks for your time.

I just tested and the segfaults are indeed gone.

However the error reporting output is now broken:
`WARNING: Invalid Response(s), Errors[286] Device[125] Thread[4] DS[, 74212]`

the snprintf always starts writing at the start of the buffer.
`snprintf(error_string, DBL_BUFSIZE, "%s", tbuffer);`
should probably be something like
``snprintf(error_string + bufsize, DBL_BUFSIZE, "%s", tbuffer);``

also i feel like the explicit flush triggered by the boolean should also set `errors` and `bufsize` to zero

**Comment by lucanLepus** [comment]
it also seems like the usage of static variables blows up when running spine with multiple threads,
at least i am getting very strange results in such a configuration

**Comment by netniV** [comment]
The alternative is that it should be doing 

```c++
snprintf(error_string, DBL_BUFSIZE, "%s%s", error_string, tbuffer);
```

This would copy the string to itself, appending the new buffer for the length of DBL_BUFSIZE.  So if error_String was already up to that size, it would not even copy tbuffer.

**Comment by lucanLepus** [comment]
> The alternative is that it should be doing
> 
> ```c++
> snprintf(error_string, DBL_BUFSIZE, "%s%s", error_string, tbuffer);
> ```
> 
> This would copy the string to itself, appending the new buffer for the length of DBL_BUFSIZE. So if error_String was already up to that size, it would not even copy tbuffer. Or using sncopy (I think it is, but I'm not sure of the top of my head)

is it safe to use snprintf like that? when destination is also one of the source arguments i mean.
i think i remember learning that one should not do that, many years ago, so this may be moot

**Comment by netniV** [comment]
Actually, it will generate a lot of warnings such as:

```
directive output may be truncated writing 15 bytes
```

**Comment by cigamit** [comment]
Try it again, and this time see if the formatting of the output is correct.

**Comment by cigamit** [comment]
More changes coming due to the threading problem.

**Comment by cigamit** [comment]
Been a while, since I've been threading in the archaic language of C.

**Comment by cigamit** [comment]
Should be ready to re-test now.

**Comment by lucanLepus** [comment]
Will test on tuesday.

From looking at it though, there seem to be missing dereferences on the pointers `buf_size` and `buf_errors` both when initializing to zero and in `buffer_output_errors()`

**Comment by lucanLepus** [comment]
i tired to fix the remaining issues i found and created a pull request with my changes for you to check.
