### ISSUE TITLE
Replace function gethostbyname with thread safe getaddrinfo

### ISSUE THREAD

**Issue by leonardo0014** [Cacti/spine#131]
**It's actually not a BUG, just a hint**
When I package with the Open Build Service from SuSE, there is a reference to an outdated command in the source text.

**Hint**
cacti-spine.x86_64: I: binary-or-shlib-calls-gethostbyname /usr/bin/spine
The binary calls gethostbyname(). Please port the code to use getaddrinfo().

**Comment by netniV** [comment]
I think it is worth switching over.  getaddrinfo is actually thread safe (see https://engineering.mongodb.com/post/the-saga-of-concurrent-dns-in-python-and-the-defeat-of-the-wicked-mutex-troll/ for a funny account about that).

**Comment by netniV** [comment]
I've committed a change to the 1.2.x branch. Feel free to try this out and test things.  I've also requested a review from either @cigamit or @TheWitness just to be sure what I have done is correct.
