### ISSUE TITLE
Feature Request: Cacti file into spine.conf

### ISSUE THREAD

**Issue by mikygee** [Cacti/spine#133]
We should be able to specify the path for the cacti configuration file (i.e: cacti/include/config.php) where spind could retrieve the parameters regarding database, database user/password, socket...

It would be better to have all these parameters in the cacti config file and specify the config file in spine.conf:
Cacti_File /htdocs/cacti/include/config.php

Thank you

**Comment by netniV** [comment]
I agree with that idea in principal. We would need to be able to parse the PHP file though so that would be extra work to ensure it’s done properly. Therefore I’m making this an enhancement that we can look at for 1.3

**Comment by TheWitness** [comment]
Fixed in issue #134
