### ISSUE TITLE
Feature request: Loop Waiting on 2 of 2 pollers when database name is incorrect

### ISSUE THREAD

**Issue by mikygee** [Cacti/spine#134]
Spine: 1.2.8

When all parameters are correct in spine.conf but DB_Database is incorrect, there is no error message and the poller polls until the end of the polling time
Waiting on 2 of 2 pollers.
Waiting on 2 of 2 pollers.
2020/01/07 15:50:02 - POLLER: Poller[1] Maximum runtime of 58 seconds exceeded. Exiting.

What should be nice is an error message saying, incorrect database name and exit.

Thank you

**Comment by cigamit** [comment]
Nice catch.

**Comment by cigamit** [comment]
Is it a legit database though?

**Comment by mikygee** [comment]
Hello Cigamit,
The database didn't exist I had made a typo mistake writing the database name.

**Comment by netniV** [comment]
If this was in core, you would have the fatal error asking you to check all the details so it should operate the same on spine.

**Comment by netniV** [comment]
However, I would say that is a big rather than feature improvement.

**Comment by TheWitness** [comment]
There are errors that goto the standard error log I would think.  There is not much we can do here other than that.  Spine has to be able to reach the database, to be able to find the cacti.log location.

**Comment by TheWitness** [comment]
I'm not really interested in fixing this myself.  Maybe either @cigamit or @netniV would like to take it.  Otherwise, I'm just going to close.  If they don't take it in a few weeks, I'll just close.

**Comment by TheWitness** [comment]
Alright, I'm bored.  I've fixed this by the introduction of a new variable Cacti_Log in the spine.conf.dist.

**Comment by mikygee** [comment]
Hello, thank you for this fix, I'll test it as soon as i'll be able to compile spine on openbsd.
