### ISSUE TITLE
Spine-Error with "Wrong-Type" SNMP-Answer

### ISSUE THREAD

**Issue by thomasbuesser** [Cacti/spine#136]
If you have a SNMP-Device that gives you a "WRONG Type" Answer for a SNMP-Query. Spine removes trailing characters from the answer.

To Reproduce

do SNMP-Query on Host: (Answer should look like that):
IF-MIB::ifHCInOctets.167862272 = Wrong Type (should be Counter64): Hex-STRING: 00 00 00 02 41 CF B4 DC

debug answer in snmp.c from spine ~line 700

debug answer after
snprintf(snmp_oids[i].result, RESULTS_BUFFER, "%s", trim(strip_alpha(temp_result)));

compare values in temp_result <-> snmp_oids[i].result

in snmp_oids[i].result the DC (last two characters) are removed in strip_alpha

Server-OS is FreeBSD 12.1-RELEASE-p1
Cacti / Spine-Release 1.2.7

**Comment by cigamit** [comment]
A pull request would be appreciated.

**Comment by TheWitness** [comment]
Please update to the latest spine and see if this is reproducible.

**Comment by TheWitness** [comment]
No feedback.
