### ISSUE TITLE
New requirement of help2man?

### ISSUE THREAD

**Issue by austinbutler** [Cacti/spine#14]
I was compiling a pre 1.0 version without issue but just tried to compile 1.0.4 and it exited status 1 with the error "No help2man." I installed help2man from Yum and compiling worked again.

Should the help2man requirement be documented somewhere? There are [a number of threads](https://www.google.com/search?q="spine"+"help2man"+site:forums.cacti.net) where people are seeing the same issue, yet the [install page](http://www.cacti.net/spine_install_unix.php) says nothing about it.

**Comment by pozgo** [comment]
+

**Comment by cigamit** [comment]
This has been documented in the new GitHub documentation repository.  We are working on breaking up the rather large manual.md there to individual sections in the next coming months.
