### ISSUE TITLE
configure: error: Cannot find SNMP headers.  Use --with-snmp= to specify non-default path

### ISSUE THREAD

**Issue by Izmenoff** [Cacti/spine#141]
During update Spine 1.2.8 to 1.2.9 is getting this error - configure: error: Cannot find SNMP headers

I used to ./configure without any parameters and have default path of spine:
/usr/local/spine/bin/spine
/usr/local/spine/bin/spine

**Comment by interduo** [comment]
You need to install debian package libsnmp-dev.

**Comment by Izmenoff** [comment]
I use Centos7

yum install libsnmp-dev
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
No package libsnmp-dev available.

**Comment by Izmenoff** [comment]
I have found a solution:
yum install -y net-snmp-devel
