### ISSUE TITLE
Spine crash after upgrading from spine-1.1.38 to spine-1.2.8

### ISSUE THREAD

**Issue by xefil** [Cacti/spine#142]
**Describe the bug**
Hello, After upgrading spine from spine-1.1.38 to spine-1.2.8, during the poller execution, spine crashes:

```
*** Error in `./spine-1.2.8': double free or corruption (out): 0x00007fe16c012410 ***
2020/02/10 18:13:26 - SPINE: Poller[1] PID[59484] SPINE: Active Threads is 32, Pending is 32
```

**To Reproduce**
Wait poller execution or exetute it manually:
`./spine` from within `/opt/spine/`

**Expected behavior**
That works without crash

**Screenshots**
nope

**Server (please complete the following information):**
 - OS: CentOS Linux release 7.3.1611
 - MySQL: mysql  Ver 15.1 Distrib 10.1.23-MariaDB, for Linux (x86_64) using readline 5.1

**Compiling (please complete the following information):**

 - compiler: gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) 
 - autoconf: autoconf (GNU Autoconf) 2.69
 - glibc: glibc-2.17
 - source: release (download from cacti.net)

*Note: you can find glibc version by running `ldd --version`*
ldd (GNU libc) 2.17

*Note: if source is github, please include last commit reference*

**Additional context**
Add any other context about the problem here including logs and command line output

Back to pervious version spine-1.1.38 all works well.
After having compiled it via `make` I've moved the `spine` executable into final destination, without executing `make install` btw. AFAYK should not needed, or?

Thanks for the help!

Simon

**Comment by netniV** [comment]
Try updating to 1.2.9, there were a couple more fixes.  If this is still an issue, we will try to investigate further.

**Comment by xefil** [comment]
I'll do, but be careful, on cacti.net the saved spine is `cacti-spine-1.2.9.tar.gz` but after compiling I get:
```
./spine -h
SPINE 1.2.8  Copyright 2004-2019 by The Cacti Group
```
I'll try download it from GitHub.

Simon

**Comment by xefil** [comment]
Ok, the output version is the same after compiling, maybe only a version code error. The `diff /usr/local/spine/bin/spine /opt/spine/spine-1.2.8` doesn't get results, also same executable.
The problem persists.
Ideas?
Thanks!

**Comment by netniV** [comment]
This is a version coding error and is my bad.  The patch to make it right is:
```diff
diff --git a/configure.ac b/configure.ac
index b9ce669..2b50f46 100644
--- a/configure.ac
+++ b/configure.ac
@@ -1,5 +1,5 @@
 AC_PREREQ(2.53)
-AC_INIT(Spine Poller, 1.2.8, http://www.cacti.net/issues.php)
+AC_INIT(Spine Poller, 1.2.9, http://www.cacti.net/issues.php)
 
 AC_CONFIG_AUX_DIR(config)
 AC_SUBST(ac_aux_dir)
```

**Comment by netniV** [comment]
I'm going to add some sanity checks to the publishing scripts to make sure that the versions we are releasing are properly tagged as this isn't the first time I missed it.
