### ISSUE TITLE
Compiling spine

### ISSUE THREAD

**Issue by interduo** [Cacti/spine#143]
Errors during compiling spine on debian buster 10.3.

```
# make
gcc -DHAVE_CONFIG_H -I. -I./config     -I/usr/include/net-snmp -I/usr/include/net-snmp/.. -I/usr/include/mariadb -g -O2 -MT sql.o -MD -MP -MF .deps/sql.Tpo -c -o sql.o sql.c
sql.c: In function ‘db_escape’:
sql.c:386:3: warning: ‘strncpy’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
   strncpy(input_trimmed, input, input_size);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
sql.c:380:15: note: length computed here
  input_size = strlen(input);
               ^~~~~~~~~~~~~
mv -f .deps/sql.Tpo .deps/sql.Po
gcc -DHAVE_CONFIG_H -I. -I./config     -I/usr/include/net-snmp -I/usr/include/net-snmp/.. -I/usr/include/mariadb -g -O2 -MT spine.o -MD -MP -MF .deps/spine.Tpo -c -o spine.o spine.c
mv -f .deps/spine.Tpo .deps/spine.Po
gcc -DHAVE_CONFIG_H -I. -I./config     -I/usr/include/net-snmp -I/usr/include/net-snmp/.. -I/usr/include/mariadb -g -O2 -MT util.o -MD -MP -MF .deps/util.Tpo -c -o util.o util.c
util.c: In function ‘spine_log’:
util.c:1171:3: warning: ‘strncat’ specified bound 1 equals source length [-Wstringop-overflow=]
   strncat(flogmessage, "\n", 1);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
util.c: In function ‘strncopy’:
util.c:1471:3: warning: ‘strncpy’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
   strncpy(dst, src, len);
   ^~~~~~~~~~~~~~~~~~~~~~
util.c:1466:8: note: length computed here
  len = strlen(src);
        ^~~~~~~~~~~
mv -f .deps/util.Tpo .deps/util.Po
gcc -DHAVE_CONFIG_H -I. -I./config     -I/usr/include/net-snmp -I/usr/include/net-snmp/.. -I/usr/include/mariadb -g -O2 -MT snmp.o -MD -MP -MF .deps/snmp.Tpo -c -o snmp.o snmp.c
mv -f .deps/snmp.Tpo .deps/snmp.Po
gcc -DHAVE_CONFIG_H -I. -I./config     -I/usr/include/net-snmp -I/usr/include/net-snmp/.. -I/usr/include/mariadb -g -O2 -MT locks.o -MD -MP -MF .deps/locks.Tpo -c -o locks.o locks.c
mv -f .deps/locks.Tpo .deps/locks.Po
gcc -DHAVE_CONFIG_H -I. -I./config     -I/usr/include/net-snmp -I/usr/include/net-snmp/.. -I/usr/include/mariadb -g -O2 -MT poller.o -MD -MP -MF .deps/poller.Tpo -c -o poller.o poller.c
poller.c: In function ‘poll_host’:
poller.c:1562:3: warning: ‘strncat’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
   strncat(query3, query8, strlen(query8));
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
poller.c:1572:4: warning: ‘strncat’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
    strncat(query12, query11, strlen(query11));
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
poller.c:1597:5: warning: ‘strncat’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
     strncat(query3, posuffix, strlen(posuffix));
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
poller.c:1604:5: warning: ‘strncat’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
     strncat(query3, query8, strlen(query8));
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
poller.c:1609:6: warning: ‘strncat’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
      strncat(query12, posuffix, strlen(posuffix));
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
poller.c:1614:6: warning: ‘strncat’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
      strncat(query12, query11, strlen(query11));
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
poller.c:1631:4: warning: ‘strncat’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
    strncat(query3, result_string, strlen(result_string));
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
poller.c:1634:5: warning: ‘strncat’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
     strncat(query12, result_string, strlen(result_string));
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
poller.c:1645:4: warning: ‘strncat’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
    strncat(query3, posuffix, strlen(posuffix));
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
poller.c:1653:5: warning: ‘strncat’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
     strncat(query12, posuffix, strlen(posuffix));
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by Izmenoff** [comment]
I have problem too on Centos7
[appadmin@srv-mncacti-01 cacti-spine-1.2.9]$ sudo make
gcc -DHAVE_CONFIG_H -I. -I./config     -I/usr/include/net-snmp -I/usr/include/net-snmp/.. -I/usr/include/mysql -g -O2 -MT sql.o -MD -MP -MF .de                                             ps/sql.Tpo -c -o sql.o sql.c
mv -f .deps/sql.Tpo .deps/sql.Po
gcc -DHAVE_CONFIG_H -I. -I./config     -I/usr/include/net-snmp -I/usr/include/net-snmp/.. -I/usr/include/mysql -g -O2 -MT spine.o -MD -MP -MF .                                             deps/spine.Tpo -c -o spine.o spine.c
mv -f .deps/spine.Tpo .deps/spine.Po
gcc -DHAVE_CONFIG_H -I. -I./config     -I/usr/include/net-snmp -I/usr/include/net-snmp/.. -I/usr/include/mysql -g -O2 -MT util.o -MD -MP -MF .d                                             eps/util.Tpo -c -o util.o util.c
mv -f .deps/util.Tpo .deps/util.Po
gcc -DHAVE_CONFIG_H -I. -I./config     -I/usr/include/net-snmp -I/usr/include/net-snmp/.. -I/usr/include/mysql -g -O2 -MT snmp.o -MD -MP -MF .d                                             eps/snmp.Tpo -c -o snmp.o snmp.c
mv -f .deps/snmp.Tpo .deps/snmp.Po
gcc -DHAVE_CONFIG_H -I. -I./config     -I/usr/include/net-snmp -I/usr/include/net-snmp/.. -I/usr/include/mysql -g -O2 -MT locks.o -MD -MP -MF .                                             deps/locks.Tpo -c -o locks.o locks.c
mv -f .deps/locks.Tpo .deps/locks.Po
gcc -DHAVE_CONFIG_H -I. -I./config     -I/usr/include/net-snmp -I/usr/include/net-snmp/.. -I/usr/include/mysql -g -O2 -MT poller.o -MD -MP -MF                                              .deps/poller.Tpo -c -o poller.o poller.c
mv -f .deps/poller.Tpo .deps/poller.Po
gcc -DHAVE_CONFIG_H -I. -I./config     -I/usr/include/net-snmp -I/usr/include/net-snmp/.. -I/usr/include/mysql -g -O2 -MT nft_popen.o -MD -MP -                                             MF .deps/nft_popen.Tpo -c -o nft_popen.o nft_popen.c
mv -f .deps/nft_popen.Tpo .deps/nft_popen.Po
gcc -DHAVE_CONFIG_H -I. -I./config     -I/usr/include/net-snmp -I/usr/include/net-snmp/.. -I/usr/include/mysql -g -O2 -MT php.o -MD -MP -MF .de                                             ps/php.Tpo -c -o php.o php.c
mv -f .deps/php.Tpo .deps/php.Po
gcc -DHAVE_CONFIG_H -I. -I./config     -I/usr/include/net-snmp -I/usr/include/net-snmp/.. -I/usr/include/mysql -g -O2 -MT ping.o -MD -MP -MF .d                                             eps/ping.Tpo -c -o ping.o ping.c
mv -f .deps/ping.Tpo .deps/ping.Po
gcc -DHAVE_CONFIG_H -I. -I./config     -I/usr/include/net-snmp -I/usr/include/net-snmp/.. -I/usr/include/mysql -g -O2 -MT keywords.o -MD -MP -M                                             F .deps/keywords.Tpo -c -o keywords.o keywords.c
mv -f .deps/keywords.Tpo .deps/keywords.Po
gcc -DHAVE_CONFIG_H -I. -I./config     -I/usr/include/net-snmp -I/usr/include/net-snmp/.. -I/usr/include/mysql -g -O2 -MT error.o -MD -MP -MF .                                             deps/error.Tpo -c -o error.o error.c
mv -f .deps/error.Tpo .deps/error.Po
/bin/sh ./libtool  --tag=CC   --mode=link gcc  -I/usr/include/net-snmp -I/usr/include/net-snmp/.. -I/usr/include/mysql -g -O2  -L/usr/lib64 -L/                                             usr/lib64 -lpthread -lssl -lm  -o spine sql.o spine.o util.o snmp.o locks.o poller.o nft_popen.o php.o ping.o keywords.o error.o  -lnetsnmp -lm                                             ysqlclient_r -lm -ldl -lmysqlclient -lm -ldl -lcrypto -lz -lpthread -ldl -lm
libtool: link: gcc -I/usr/include/net-snmp -I/usr/include/net-snmp/.. -I/usr/include/mysql -g -O2 -o spine sql.o spine.o util.o snmp.o locks.o                                              poller.o nft_popen.o php.o ping.o keywords.o error.o  -L/usr/lib64 -lssl -lnetsnmp -lmysqlclient_r -lmysqlclient -lcrypto -lz -lpthread -ldl -l                                             m
/bin/help2man --output=spine.1 --name='Data Collector for Cacti' --no-info --version-option='--version' ./spine

**Comment by TheWitness** [comment]
Yea, those can all be ignored.  They are just warnings anyway.
