### ISSUE TITLE
SPINE: Poller Errors

### ISSUE THREAD

**Issue by zhengzx0127** [Cacti/spine#148]
SPINE: Poller[Main Poller] PID[10932] WARNING: Invalid Response(s), Errors[58] Device

**Comment by TheWitness** [comment]
Well, that is clearly not enough information.  You need to run by hand and then see what is up.  So, you need to find the device ID in question or just run spine this way to see there errors:

```cmd
./spine -R -V 3 -S
```

**Comment by zhengzx0127** [comment]
I delete the device and add it again without error log.
I'm not sure what the issue. sorry.
