### ISSUE TITLE
Spine ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count

### ISSUE THREAD

**Issue by Susanin63** [Cacti/spine#159]
Few days ago spine was flooding in log with error:

`2020/05/30 15:35:35 - SPINE: Poller[Main Poller] PID[3576] ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
2020/05/30 15:35:35 - SPINE: Poller[Main Poller] PID[3576] ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
2020/05/30 15:35:35 - SPINE: Poller[Main Poller] PID[3576] ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count`
./spine -v
SPINE 1.2.6  Copyright 2004-2019 by The Cacti Group

I am update spins to last version:

/usr/local/spine/bin/spine -v
SPINE 1.2.12  Copyright 2004-2020 by The Cacti Group

After that it work for 2 days. But today I see this error again.  I determined that an error occurs while polling a single device.
Here the debug log:
`sudo -H -u cacti bash -c '/usr/local/spine/bin/spine -C /usr/local/spine/etc/spine.conf --poller 1 --first 184 --last 184 --stdout --readonly --verbosity=500'
SPINE: Using spine config file [/usr/local/spine/etc/spine.conf]
2020/06/01 15:31:39 - SPINE: Poller[1] PID[3267] DEVDBG: SQL:SELECT value FROM settings WHERE name = 'path_webroot'
2020/06/01 15:31:39 - SPINE: Poller[1] PID[3267] DEVDBG: SQL:SELECT value FROM settings WHERE name = 'path_cactilog'
2020/06/01 15:31:39 - SPINE: Poller[1] PID[3267] DEVDBG: SQL:SELECT value FROM settings WHERE name = 'default_datechar'
2020/06/01 15:31:39 - SPINE: Poller[1] PID[3267] DEVDBG: SQL:SELECT value FROM settings WHERE name = 'default_datechar'
2020/06/01 15:31:39 - SPINE: Poller[1] PID[3267] DEBUG: The path_php_server variable is /var/www/html/cacti/script_server.php
2020/06/01 15:31:39 - SPINE: Poller[1] PID[3267] DEBUG: The path_cactilog variable is /var/www/html/cacti/log/cacti.log
DEBUG: The log_destination variable is 4 (STDOUT)
DEVDBG: SQL:SELECT value FROM settings WHERE name = 'path_php_binary
DEBUG: The path_php variable is /usr/bin/php
DEVDBG: SQL:SELECT value FROM settings WHERE name = 'availability_method
DEBUG: The availability_method variable is 2
DEVDBG: SQL:SELECT value FROM settings WHERE name = 'ping_recovery_count
DEBUG: The ping_recovery_count variable is 2
DEVDBG: SQL:SELECT value FROM settings WHERE name = 'ping_failure_count
DEBUG: The ping_failure_count variable is 1
DEVDBG: SQL:SELECT value FROM settings WHERE name = 'ping_method
DEBUG: The ping_method variable is 2
DEVDBG: SQL:SELECT value FROM settings WHERE name = 'ping_retries
DEBUG: The ping_retries variable is 3
DEVDBG: SQL:SELECT value FROM settings WHERE name = 'ping_timeout
DEBUG: The ping_timeout variable is 400
DEVDBG: SQL:SELECT value FROM settings WHERE name = 'snmp_retries
DEBUG: The snmp_retries variable is 3
DEVDBG: SQL:SELECT value FROM settings WHERE name = 'log_perror
DEBUG: The log_perror variable is 1
DEVDBG: SQL:SELECT value FROM settings WHERE name = 'log_pwarn
DEBUG: The log_pwarn variable is 0
DEVDBG: SQL:SELECT value FROM settings WHERE name = 'boost_redirect
DEBUG: The boost_redirect variable is 0
DEVDBG: SQL:SELECT value FROM settings WHERE name = 'boost_rrd_update_enable
DEBUG: The boost_rrd_update_enable variable is 0
DEVDBG: SQL:SELECT value FROM settings WHERE name = 'log_pstats
DEBUG: The log_pstats variable is 1
DEVDBG: SQL:SELECT threads FROM poller WHERE id = '1
DEBUG: The threads variable is 8
DEVDBG: SQL:SELECT value FROM settings WHERE name = 'poller_interval
DEBUG: The polling interval is 300 seconds
DEVDBG: SQL:SELECT value FROM settings WHERE name = 'concurrent_processes
DEBUG: The number of concurrent processes is 4
DEVDBG: SQL:SELECT value FROM settings WHERE name = 'script_timeout
DEBUG: The script timeout is 5
DEVDBG: SQL:SELECT value FROM settings WHERE name = 'selective_device_debug
DEBUG: The selective_device_debug variable is
DEVDBG: SQL:SELECT value FROM settings WHERE name = 'spine_log_level
DEBUG: The spine_log_level variable is 0
DEVDBG: SQL:SELECT value FROM settings WHERE name = 'php_servers
DEBUG: The number of php script servers to run is 4
DEVDBG: SQL:SELECT action FROM poller_item WHERE action=2 AND host_id BETWEEN 184 AND 184 LIMIT 1
DEBUG: StartDevice='184', EndDevice='184', TotalPHPScripts='0
DEBUG: The PHP Script Server is Not Required
DEVDBG: SQL:SELECT value FROM settings WHERE name = 'max_get_size
DEBUG: The Maximum SNMP OID Get Size is 20
DEVDBG: SQL:SET SESSION sql_mode = (SELECT REPLACE(@@sql_mode,'NO_ZERO_DATE', ''))
DEVDBG: SQL:SET SESSION sql_mode = (SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY', ''))
SPINE: Version 1.2.12 starting
DEBUG: Spine running as 1000 UID, 0 EUID
DEBUG: Spine is running as root.
DEBUG: Spine has got ICMP
SPINE: Initializing Net-SNMP API
DEBUG: Issues with SNMP Header Version information, assuming old version of Net-SNMP.
SPINE: Initializing PHP Script Server(s)
DEVDBG: SQL:SHOW COLUMNS FROM host LIKE 'poller_id
DEVDBG: SQL:SHOW COLUMNS FROM host LIKE 'device_threads
NOTE: Spine will support multithread device polling.
DEVDBG: SQL:SELECT id, device_threads FROM host WHERE disabled='' AND id BETWEEN 184 AND 184 AND host.poller_id=1 ORDER BY polling_time DESC
DEVDBG: SQL:INSERT INTO poller_time (poller_id, pid, start_time, end_time) VALUES (1, 3267, NOW(), '0000-00-00 00:00:00')
DEBUG: Initial Value of Active Threads is 0
DEVDBG: SQL:SELECT COUNT(*) FROM poller_item WHERE host_id=0 AND rrd_next_step <=0
DEBUG: Valid Thread to be Created
DEBUG: In Poller, About to Start Polling of Device for Device ID 0
SPINE: Active Threads is 1, Pending is 1
INFO: DTS: device = 0, host_id = 0, host_thread = 1, last_host_thread = 0, host_data_ids = 0, complete = 0
DEVDBG: SQL:SELECT COUNT(*) FROM poller_item WHERE host_id=184 AND rrd_next_step <=0
DEBUG: Valid Thread to be Created
DEVDBG: SQL:SET SESSION sql_mode = (SELECT REPLACE(@@sql_mode,'NO_ZERO_DATE', ''))
DEVDBG: SQL:SET SESSION sql_mode = (SELECT REPLACE(@@sql_mode,'NO_ZERO_IN_DATE', ''))
DEBUG: In Poller, About to Start Polling of Device for Device ID 184
DEVDBG: SQL:SET SESSION sql_mode = (SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY', ''))
DEVDBG: SQL:SET SESSION sql_mode = (SELECT REPLACE(@@sql_mode,'NO_AUTO_VALUE_ON_ZERO', ''))
DEVDBG: SQL:SET SESSION sql_mode = (SELECT REPLACE(@@sql_mode,'TRADITIONAL', ''))
DEVDBG: SQL:SET SESSION sql_mode = (SELECT REPLACE(@@sql_mode,'STRICT_ALL_TABLES', ''))
DEVDBG: SQL:SET SESSION sql_mode = (SELECT REPLACE(@@sql_mode,'STRICT_TRANS_TABLES', ''))
SPINE: Active Threads is 2, Pending is 2
INFO: DTS: device = 1, host_id = 184, host_thread = 1, last_host_thread = 1, host_data_ids = 0, complete = 0
DEVDBG: SQL:SET SESSION sql_mode = (SELECT REPLACE(@@sql_mode,'NO_ZERO_DATE', ''))
DEVDBG: SQL:SET SESSION sql_mode = (SELECT REPLACE(@@sql_mode,'NO_ZERO_IN_DATE', ''))
DEVDBG: SQL:SET SESSION sql_mode = (SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY', ''))
DEVDBG: SQL:SET SESSION sql_mode = (SELECT REPLACE(@@sql_mode,'NO_AUTO_VALUE_ON_ZERO', ''))
DEVDBG: SQL:SET SESSION sql_mode = (SELECT REPLACE(@@sql_mode,'TRADITIONAL', ''))
DEVDBG: SQL:SET SESSION sql_mode = (SELECT REPLACE(@@sql_mode,'STRICT_ALL_TABLES', ''))
DEVDBG: SQL:SET SESSION sql_mode = (SELECT REPLACE(@@sql_mode,'STRICT_TRANS_TABLES', ''))
DEVDBG: SQL:SET SESSION sql_mode = (SELECT REPLACE(@@sql_mode,'NO_ZERO_DATE', ''))
DEVDBG: SQL:SET SESSION sql_mode = (SELECT REPLACE(@@sql_mode,'NO_ZERO_IN_DATE', ''))
DEVDBG: SQL:SET SESSION sql_mode = (SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY', ''))
DEVDBG: SQL:SET SESSION sql_mode = (SELECT REPLACE(@@sql_mode,'NO_AUTO_VALUE_ON_ZERO', ''))
DEVDBG: SQL:SET SESSION sql_mode = (SELECT REPLACE(@@sql_mode,'TRADITIONAL', ''))
DEVDBG: SQL:SET SESSION sql_mode = (SELECT REPLACE(@@sql_mode,'STRICT_ALL_TABLES', ''))
DEVDBG: SQL:SET SESSION sql_mode = (SELECT REPLACE(@@sql_mode,'STRICT_TRANS_TABLES', ''))
DEVDBG: SQL:SELECT snmp_port, count(snmp_port) FROM poller_item WHERE host_id=0 AND rrd_next_step <=0 AND poller_id=1 GROUP BY snmp_port
DEVDBG: SQL:SET SESSION sql_mode = (SELECT REPLACE(@@sql_mode,'NO_ZERO_DATE', ''))
DEVDBG: SQL:SET SESSION sql_mode = (SELECT REPLACE(@@sql_mode,'NO_ZERO_IN_DATE', ''))
DEVDBG: SQL:SET SESSION sql_mode = (SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY', ''))
DEVDBG: SQL:SET SESSION sql_mode = (SELECT REPLACE(@@sql_mode,'NO_AUTO_VALUE_ON_ZERO', ''))
DEVDBG: SQL:SET SESSION sql_mode = (SELECT REPLACE(@@sql_mode,'TRADITIONAL', ''))
DEVDBG: SQL:SET SESSION sql_mode = (SELECT REPLACE(@@sql_mode,'STRICT_ALL_TABLES', ''))
DEVDBG: SQL:SET SESSION sql_mode = (SELECT REPLACE(@@sql_mode,'STRICT_TRANS_TABLES', ''))
DEVDBG: SQL:SELECT id, hostname, snmp_community, snmp_version, snmp_username, snmp_password, snmp_auth_protocol, snmp_priv_passphrase, snmp_priv_protocol, snmp_context, snmp_engine_id, snmp_port, snmp_timeout, max_oids, availability_method, ping_method, ping_port, ping_timeout, ping_retries, status, status_event_count, status_fail_date, status_rec_date, status_last_error, min_time, max_time, cur_time, avg_time, total_polls, failed_polls, availability, snmp_sysUpTimeInstance, snmp_sysDescr, snmp_sysObjectID, snmp_sysContact, snmp_sysName, snmp_sysLocation FROM host WHERE id=184 AND deleted =
DEVDBG: SQL:SELECT action, hostname, snmp_community, snmp_version, snmp_username, snmp_password, rrd_name, rrd_path, arg1, arg2, arg3, local_data_id, rrd_num, snmp_port, snmp_timeout, snmp_auth_protocol, snmp_priv_passphrase, snmp_priv_protocol, snmp_context, snmp_engine_id  FROM poller_item WHERE host_id=0 AND rrd_next_step <=0 AND poller_id=1 ORDER by snmp_port
Device[0] HT[1] Total Time: 0.0012 Seconds
Device[184] INFO: SNMP Device '85.113.60.218' has timeout 2000000 (2000), retries 3
DEVDBG: SQL:UPDATE host SET polling_time=1591011100.004 - 1591011100.003 WHERE id=0
Device[184] DEBUG: Entering SNMP Ping
Device[184] WARNING: snmp_pdu_create(.1.3.6.1.2.1.1.3.0)
Device[184] WARNING: snmp_pdu_create(.1.3.6.1.2.1.1.3.0) [complete]
Device[184] WARNING: snmp_parse_oid(.1.3.6.1.2.1.1.3.0)
Device[184] WARNING: snmp_parse_oid(.1.3.6.1.2.1.1.3.0) [complete]
Device[184] WARNING: snmp_add_null_var(.1.3.6.1.2.1.1.3.0)
Device[0] HT[1] DEBUG: HOST COMPLETE: About to Exit Device Polling Thread Function
DEBUG: The Value of Active Threads is 1 for Device ID 0
Device[184] WARNING: snmp_add_null_var(.1.3.6.1.2.1.1.3.0) [complete]
Device[184] WARNING: snmp_sess_sync_response(.1.3.6.1.2.1.1.3.0)
POLLER: Active Threads is 1, Pending is 1
Device[184] WARNING: snmp_sess_sync_response(.1.3.6.1.2.1.1.3.0) [complete]
Device[184] SNMP Result: Device responded to SNMP
NOTE: Device[184] Checking for System Information Update
NOTE: Device[184] Updating Full System Information Table
DEVDBG: Device[184] poll_result = snmp_get(host, '.1.3.6.1.2.1.1.1.0');
Device[184] WARNING: snmp_pdu_create(.1.3.6.1.2.1.1.1.0)
Device[184] WARNING: snmp_pdu_create(.1.3.6.1.2.1.1.1.0) [complete]
Device[184] WARNING: snmp_parse_oid(.1.3.6.1.2.1.1.1.0)
Device[184] WARNING: snmp_parse_oid(.1.3.6.1.2.1.1.1.0) [complete]
Device[184] WARNING: snmp_add_null_var(.1.3.6.1.2.1.1.1.0)
Device[184] WARNING: snmp_add_null_var(.1.3.6.1.2.1.1.1.0) [complete]
Device[184] WARNING: snmp_sess_sync_response(.1.3.6.1.2.1.1.1.0)
Device[184] WARNING: snmp_sess_sync_response(.1.3.6.1.2.1.1.1.0) [complete]
DEVDBG: Device[184] poll_result = snmp_get(host, '.1.3.6.1.2.1.1.1.0'); [complete]
DEVDBG: Device[184] poll_result = snmp_get(host, '.1.3.6.1.2.1.1.2.0');
Device[184] WARNING: snmp_pdu_create(.1.3.6.1.2.1.1.2.0)
Device[184] WARNING: snmp_pdu_create(.1.3.6.1.2.1.1.2.0) [complete]
Device[184] WARNING: snmp_parse_oid(.1.3.6.1.2.1.1.2.0)
Device[184] WARNING: snmp_parse_oid(.1.3.6.1.2.1.1.2.0) [complete]
Device[184] WARNING: snmp_add_null_var(.1.3.6.1.2.1.1.2.0)
Device[184] WARNING: snmp_add_null_var(.1.3.6.1.2.1.1.2.0) [complete]
Device[184] WARNING: snmp_sess_sync_response(.1.3.6.1.2.1.1.2.0)
Device[184] WARNING: snmp_sess_sync_response(.1.3.6.1.2.1.1.2.0) [complete]
DEVDBG: Device[184] poll_result = snmp_get(host, '.1.3.6.1.2.1.1.2.0'); [complete]
DEVDBG: Device[184] poll_result = snmp_get(host, '.1.3.6.1.2.1.1.3.0');
Device[184] WARNING: snmp_pdu_create(.1.3.6.1.2.1.1.3.0)
Device[184] WARNING: snmp_pdu_create(.1.3.6.1.2.1.1.3.0) [complete]
Device[184] WARNING: snmp_parse_oid(.1.3.6.1.2.1.1.3.0)
Device[184] WARNING: snmp_parse_oid(.1.3.6.1.2.1.1.3.0) [complete]
Device[184] WARNING: snmp_add_null_var(.1.3.6.1.2.1.1.3.0)
Device[184] WARNING: snmp_add_null_var(.1.3.6.1.2.1.1.3.0) [complete]
Device[184] WARNING: snmp_sess_sync_response(.1.3.6.1.2.1.1.3.0)
Device[184] WARNING: snmp_sess_sync_response(.1.3.6.1.2.1.1.3.0) [complete]
DEVDGB: Device[184] poll_result = snmp_get(host, '.1.3.6.1.2.1.1.3.0'); [complete]
DEVDBG: Device [184] poll_result = snmp_get(host, '.1.3.6.1.2.1.1.4.0');
Device[184] WARNING: snmp_pdu_create(.1.3.6.1.2.1.1.4.0)
Device[184] WARNING: snmp_pdu_create(.1.3.6.1.2.1.1.4.0) [complete]
Device[184] WARNING: snmp_parse_oid(.1.3.6.1.2.1.1.4.0)
Device[184] WARNING: snmp_parse_oid(.1.3.6.1.2.1.1.4.0) [complete]
Device[184] WARNING: snmp_add_null_var(.1.3.6.1.2.1.1.4.0)
Device[184] WARNING: snmp_add_null_var(.1.3.6.1.2.1.1.4.0) [complete]
Device[184] WARNING: snmp_sess_sync_response(.1.3.6.1.2.1.1.4.0)
Device[184] WARNING: snmp_sess_sync_response(.1.3.6.1.2.1.1.4.0) [complete]
DEVDBG: Device [184] poll_result = snmp_get(host, '.1.3.6.1.2.1.1.4.0'); [complete]
DEVDBG: Device [184] poll_result = snmp_get(host, '.1.3.6.1.2.1.1.5.0');
Device[184] WARNING: snmp_pdu_create(.1.3.6.1.2.1.1.5.0)
Device[184] WARNING: snmp_pdu_create(.1.3.6.1.2.1.1.5.0) [complete]
Device[184] WARNING: snmp_parse_oid(.1.3.6.1.2.1.1.5.0)
Device[184] WARNING: snmp_parse_oid(.1.3.6.1.2.1.1.5.0) [complete]
Device[184] WARNING: snmp_add_null_var(.1.3.6.1.2.1.1.5.0)
Device[184] WARNING: snmp_add_null_var(.1.3.6.1.2.1.1.5.0) [complete]
Device[184] WARNING: snmp_sess_sync_response(.1.3.6.1.2.1.1.5.0)
Device[184] WARNING: snmp_sess_sync_response(.1.3.6.1.2.1.1.5.0) [complete]
DEVDBG: Device [184] poll_result = snmp_get(host, '.1.3.6.1.2.1.1.5.0'); [complete]
DEVDBG: Device [184] poll_result = snmp_get(host, '.1.3.6.1.2.1.1.6.0');
Device[184] WARNING: snmp_pdu_create(.1.3.6.1.2.1.1.6.0)
Device[184] WARNING: snmp_pdu_create(.1.3.6.1.2.1.1.6.0) [complete]
Device[184] WARNING: snmp_parse_oid(.1.3.6.1.2.1.1.6.0)
Device[184] WARNING: snmp_parse_oid(.1.3.6.1.2.1.1.6.0) [complete]
Device[184] WARNING: snmp_add_null_var(.1.3.6.1.2.1.1.6.0)
Device[184] WARNING: snmp_add_null_var(.1.3.6.1.2.1.1.6.0) [complete]
Device[184] WARNING: snmp_sess_sync_response(.1.3.6.1.2.1.1.6.0)
Device[184] WARNING: snmp_sess_sync_response(.1.3.6.1.2.1.1.6.0) [complete]
DEVDBG: Device [184] poll_result = snmp_get(host, '.1.3.6.1.2.1.1.6.0'); [complete]
DEVDBG: SQL:UPDATE host SET status='3', status_event_count='0', status_fail_date='2020-05-29 11:55:00', status_rec_date='2020-05-29 15:25:00', status_last_error='Device did not respond to SNMP', min_time='4.253860', max_time='1993.018870', cur_time='12.544160', avg_time='75.021968', total_polls='619539', failed_polls='5631', availability='99.0911', snmp_sysDescr='Linux 2.6.32.71 #1 Fri May 5 15:25:58 EEST 2017 mips',  snmp_sysObjectID='iso.3.6.1.4.1.41112.1.4', snmp_sysUpTimeInstance='5963300',  snmp_sysContact='Oleg', snmp_sysName='OKT', snmp_sysLocation='2-ka' WHERE id='184
DEVDBG: SQL:SELECT data_query_id, action, op, assert_value, arg1 FROM poller_reindex WHERE host_id=184
Device[184] HT[1] RECACHE: Processing 2 items in the auto reindex cache for '85.113.60.218
Device[184] WARNING: snmp_pdu_create(.1.3.6.1.2.1.2.1.0)
Device[184] WARNING: snmp_pdu_create(.1.3.6.1.2.1.2.1.0) [complete]
Device[184] WARNING: snmp_parse_oid(.1.3.6.1.2.1.2.1.0)
Device[184] WARNING: snmp_parse_oid(.1.3.6.1.2.1.2.1.0) [complete]
Device[184] WARNING: snmp_add_null_var(.1.3.6.1.2.1.2.1.0)
Device[184] WARNING: snmp_add_null_var(.1.3.6.1.2.1.2.1.0) [complete]
Device[184] WARNING: snmp_sess_sync_response(.1.3.6.1.2.1.2.1.0)
Device[184] WARNING: snmp_sess_sync_response(.1.3.6.1.2.1.2.1.0) [complete]
Device[184] HT[1] DQ[1] RECACHE OID: .1.3.6.1.2.1.2.1.0, (assert: 6 = output: 6)
NOTE: walk starts at OID .1.3.6.1.4.1.41112.1.4.7.1.1
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
ERROR: An internal Net-Snmp error condition detected in Cacti snmp_count
`
*Server (please complete the following information):**
 - OS: CentOS 7
 - Version 1.2.12

` snmpwalk -v 1 -c xxxxxx 85.113.x.x:12161 .1.3.6.1.4.1.41112.1.4.7.1.1
End of MIB
`

**Comment by Susanin63** [comment]
Sorry for formatting. Here is the log:
[spine.log](https://github.com/Cacti/spine/files/4711063/spine.log)

**Comment by TheWitness** [comment]
Can you please update to the 1.2.x branch and see if this still occurs?

**Comment by TheWitness** [comment]
Also, what happens when you attempt to walk this oid for device id 184?

```
.1.3.6.1.4.1.41112.1.4.7.1.1
```

**Comment by TheWitness** [comment]
No feedback.
