### ISSUE TITLE
SQL Failed! Error: '1065'

### ISSUE THREAD

**Issue by interduo** [Cacti/spine#160]
2020/06/10 11:55:19 - SPINE: Poller[Main Poller] PID[50271] ERROR: SQL Failed! Error:'1065', Message:'Query was empty', SQL Fragment:''
--
2020/06/10 11:55:19 - SPINE: Poller[Main Poller] PID[50271] ERROR: SQL Failed! Error:'1065', Message:'Query was empty', SQL Fragment:''
2020/06/10 11:55:19 - SPINE: Poller[Main Poller] PID[50271] ERROR: SQL Failed! Error:'1065', Message:'Query was empty', SQL Fragment:''

**Comment by netniV** [comment]
Was this all that was present, no stack trace?

**Comment by interduo** [comment]
This message was from clog. Where to find whole stack?

**Comment by netniV** [comment]
I would have suspected that it should be recorded there.

**Comment by interduo** [comment]
http://kłopotek.pl/spine-poller.txt <-- that is the whole cacti log within one pooling, this is reproducable every pool.

**Comment by interduo** [comment]
This version error occurs.
root@cacti:/usr/sbin# spine.older -v
SPINE 1.2.12  Copyright 2004-2020 by The Cacti Group

This version not.
root@cacti:/usr/sbin# spine -v
SPINE 1.2.8  Copyright 2004-2019 by The Cacti Group

**Comment by TheWitness** [comment]
This has already been resolved in the 1.2.x branch.  Thanks for reporting though.

**Comment by TheWitness** [comment]
Here is that change.  Will be resolved in 1.2.13.

https://github.com/Cacti/spine/commit/3d0adde5dc90656d5dc692303de84689c5b21eb3

**Comment by interduo** [comment]
Is this a spine or cacti issue?

**Comment by TheWitness** [comment]
Spine
