### ISSUE TITLE
Spine not updating rrd_next_step

### ISSUE THREAD

**Issue by UnrealQuester** [Cacti/spine#162]
**Describe the bug**
When a host currently has no poller_items that the poller needs to work on rrd_next_step is never decremented and that host never gets polled again.

**To Reproduce**
1. Have a host with one poller_item with an rrd_step of 300 and an rrd_next_step of 60
2. Spine runs every minute

**Expected behavior**
After one run spine should decrement rrd_next_step by 60 and then actually poll the data on the next run

**Server (please complete the following information):**
 - OS: irrelevant

**Compiling (please complete the following information):**

 - source: irrelevant

**Additional context**
The problem was introduced in version 1.2.0.

If total_items in spine.c is 0 (i.e. no work needs to be done this run), then device_threads gets set to 0 as well in https://github.com/Cacti/spine/blob/develop/spine.c#L698, while current_thread stays at 1. This can happen if we have a host with just a few items that run infrequently (i.e. one item that should run every 5 minutes). This then makes the check in https://github.com/Cacti/spine/blob/develop/poller.c#L1639 fail every time, which causes the value to never be updated.

**Proposed solution**

Only update device_threads if total_items is not zero.

**Comment by netniV** [comment]
I have made a change, can you test this out and make sure it works for you.

**Comment by UnrealQuester** [comment]
Can confirm the issue is now fixed. Thank you for the quick response!
