### ISSUE TITLE
Unable to compile spine on OpenBSD

### ISSUE THREAD

**Issue by mikygee** [Cacti/spine#163]
Spine: 1.2.13

Hello,
I'm not able to compile spine on openbsd

The same problem as in
https://github.com/Cacti/spine/issues/122

```
/bin/sh ./libtool  --tag=CC    --mode=link gcc  -I/usr/local/include/net-snmp -I/usr/local/include/net-snmp/.. -I/usr/local/include/mysql -g -O2   -L/usr/local/lib -L/usr/local/lib  -o spine sql.o spine.o util.o  snmp.o locks.o poller.o  nft_popen.o php.o ping.o  keywords.o error.o  -lmysqlclient -lm -ldl -lmysqlclient -lm -ldl -lcrypto -lz -lpthread -lm -lpthread -lssl
libtool: link: gcc -I/usr/local/include/net-snmp -I/usr/local/include/net-snmp/.. -I/usr/local/include/mysql -g -O2 -o spine sql.o spine.o util.o snmp.o locks.o poller.o nft_popen.o php.o ping.o keywords.o error.o  -L/usr/local/lib -lmysqlclient -ldl -lcrypto -lz -lm -lpthread -lssl
ld: error: unable to find library -ldl
collect2: ld returned 1 exit status
*** Error 1 in /var/www/htdocs/cacti-spine-1.2.13 (Makefile:471 'spine')
```

In the Makefile there is a freebsd switch but no openbsd switch

I ended removing all the -ldl in the Makefile and have these errors

ld: error: undefined symbol: snmp_pdu_create
>>> referenced by snmp.c:656
>>>               snmp.o:(snmp_get_multi)

ld: error: undefined symbol: snmp_add_null_var
>>> referenced by snmp.c:666
>>>               snmp.o:(snmp_get_multi)

ld: error: undefined symbol: snmp_parse_oid
>>> referenced by snmp.c:660
>>>               snmp.o:(snmp_get_multi)

ld: error: undefined symbol: snmp_sess_synch_response
>>> referenced by snmp.c:676
>>>               snmp.o:(snmp_get_multi)

ld: error: undefined symbol: snmp_fix_pdu
>>> referenced by snmp.c:722
>>>               snmp.o:(snmp_get_multi)

....

**Comment by mikygee** [comment]
Hello,

I found a dirty hack in configure.ac and it compiles ok

```
unamestr=$(uname)
if test $unamestr == 'OpenBSD'; then
  AC_CHECK_LIB(mysqlclient, mysql_init,
    [ LIBS="-lmysqlclient -lm $LIBS"
      AC_DEFINE(HAVE_MYSQL, 1, MySQL Client API)
      HAVE_MYSQL=yes ],
    [ HAVE_MYSQL=no ]
  )
else
  AC_CHECK_LIB(mysqlclient, mysql_init,
    [ LIBS="-lmysqlclient -lm -ldl $LIBS"
      AC_DEFINE(HAVE_MYSQL, 1, MySQL Client API)
      HAVE_MYSQL=yes ],
    [ HAVE_MYSQL=no ]
  )
fi

if test $MYSQL_REENTRANT = 1 ; then
  LIBS="-lmysqlclient_r -lm -ldl $LIBS"
else
  if test -f $MYSQL_LIB_DIR/libmysqlclient_r.a -o -f $MYSQL_LIB_DIR/libmysqlclient_r.$ShLib; then
    LIBS="-lmysqlclient_r -lm -ldl $LIBS"
  else
    if test -f $MYSQL_LIB_DIR/libmysqlclient_r.a -o -f $MYSQL_LIB_DIR/libmysqlclient_r.$ShLib ; then
      LIBS="-lmysqlclient_r -lm -ldl $LIBS"
    else
      if test "$HAVE_MYSQL" == "yes"; then
        if test $unamestr == 'OpenBSD'; then
          LIBS="-lmysqlclient -lm $LIBS"
        else
          LIBS="-lmysqlclient -lm -ldl $LIBS"
        fi
      else
        LIBS="-lmariadbclient -lm -ldl $LIBS"
      fi
    fi
  fi
fi
```

**Comment by netniV** [comment]
Feel free to present it as a PR with a CHANGELOG entry and we will look at merging it.

**Comment by mikygee** [comment]
Hello,
What is a PR ?

**Comment by mikygee** [comment]
I guess it's a pull request =)

**Comment by TheWitness** [comment]
:)  Thanks for bringing me a little joy in my long day.

**Comment by mikygee** [comment]
Hello,
I created this new pull request
https://github.com/Cacti/spine/pull/168
With 1.2 branch
