### ISSUE TITLE
Spine 1.2.13 double quote in output

### ISSUE THREAD

**Issue by bredis** [Cacti/spine#165]
The problem from ticket number 157 persists in release 1.2.13.
```

2020-08-01 12:45:01 - SPINE: Poller[Main Poller] PID[1439] DEVDBG: SQL:INSERT INTO poller_output (local_data_id, rrd_name, time, output) VALUES (52,'Connections','2020-08-01 12:45:01','"CONNECTIONS:8') ON DUPLICATE KEY UPDATE output=VALUES(output)
--
2020-08-01 12:45:01 - SPINE: Poller[Main Poller] PID[1439] Device[192.168.31.3] HT[1] DS[192.168.31.3 - Keenetic - Connections] Graphs[192.168.31.3 - Keenetic - Connections] SCRIPT: /usr/bin/php /var/www/cacti/scripts/query_keenetic_connections.php '192.168.31.3' '10161' 'public' , output: "CONNECTIONS:8

```
Wrong output = ``"CONNECTIONS:8``
Correct output = ``CONNECTIONS:8``

OS:Linux ns.home 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux

- compiler: gcc version 8.3.0 (Debian 8.3.0-6)
- autoconf: autoconf (GNU Autoconf) 2.69
- glibc:  ldd (Debian GLIBC 2.28-10) 2.28
- source: release 1.2.13 [https://www.cacti.net/downloads/spine/cacti-spine-1.2.13.tar.gz](https://www.cacti.net/downloads/spine/cacti-spine-1.2.13.tar.gz)

Correct output from snmpwalk: 
``root@ns:~# snmpwalk -v2c -c public 192.168.31.3:10161 .1.3.6.1.4.1.2021.8.1.101.2
UCD-SNMP-MIB::extOutput.2 = STRING: CONNECTIONS:7
root@ns:~#
``

**Comment by bredis** [comment]
Spine 1.2.14 problem persists

```

2020-08-26 19:34:02 - SPINE: Poller[Main Poller] PID[21842] DEVDBG: SQL:INSERT INTO poller_output (local_data_id, rrd_name, time, output) VALUES (52,'Connections','2020-08-26 19:34:01','"CONNECTIONS:5') ON DUPLICATE KEY UPDATE output=VALUES(output)
--
2020-08-26 19:34:02 - SPINE: Poller[Main Poller] PID[21842] Device[192.168.31.3] HT[1] DS[192.168.31.3 - Keenetic - Connections] Graphs[192.168.31.3 - Keenetic - Connections] SCRIPT: /usr/bin/php /var/www/cacti/scripts/query_keenetic_connections.php '192.168.31.3' '10161' 'public' , output: "CONNECTIONS:5

```
Wrong output = `"CONNECTIONS:5`

**Comment by TheWitness** [comment]
Post your script please.

**Comment by bredis** [comment]
A script that will receive the number of connections. Executed on the end device:

```
#!/bin/sh


data=`ndmq -p "show ip nat" -x | grep protocol | wc -l`
data=${data}


echo CONNECTIONS:$data
```
It is called from the snmpd.conf file with the line:
``
exec connections /bin/sh /opt/etc/snmp/connections.sh
``

Script from cacti:
```
<?php
/* do NOT run this script through a web browser */
if (!isset($_SERVER["argv"][0]) || isset($_SERVER['REQUEST_METHOD'])  || isset($_SERVER['REMOTE_ADDR'])) {
   die("<br><strong>This script is only meant to run at the command line.</strong>");
}
$no_http_headers = true;
    $hostname  = $_SERVER["argv"][1];
    $snmp_port = $_SERVER["argv"][2];
    $community = $_SERVER["argv"][3];
    $object_id = ".1.3.6.1.4.1.2021.8.1.101.2";
    $ifAlias = snmp2_get("$hostname:$snmp_port", "$community", "$object_id",7200000);
    $ifAlias=preg_replace('/STRING: /','',$ifAlias);
    echo $ifAlias;
?>
```

**Comment by TheWitness** [comment]
Can you trim the quotes in the connections.sh script?

**Comment by bredis** [comment]
I can’t remove the quotes because of the syntax of the "ndmq" utility.
[https://github.com/ndmsystems/ndmq](url)

Connections.sh script output:
```
~ # /opt/etc/snmp/connections.sh
CONNECTIONS:72
~ #
```

**Comment by bredis** [comment]
The problem persists in version 1.2.15.
In the "Graph in Real-Time" mode, this problem is not.

**Comment by netniV** [comment]
You do not need to remove the quotes from the command, but from the returned output.

**Comment by bredis** [comment]
I do not understand something. When using the poller type "cmd.php", there are no quotes in the output.

**Comment by bredis** [comment]
What should I change in the script to remove the quotes?
Running my script from the shell:
```
root@ns:~# runuser -l www-data -s /var/www/cacti/scripts/keen_con.sh 192.168.100.254 10161 public
UCD-SNMP-MIB::extOutput.2 = STRING: CONNECTIONS:63
```
The same script launched with spine from cacti:
```
2020-11-20 11:21:02 - SPINE: Poller[Main Poller] PID[5177] WARNING: Invalid Response, Device[192.168.100.254] HT[1] DS[192.168.100.254 - Keenetic - Connections] Graphs[192.168.100.254 - Keenetic - Connections]
SCRIPT: /bin/sh /var/www/cacti/scripts/keen_con.sh '192.168.100.254' '10161' 'public' , output: iso.3.6.1.4.1.2021.8.1.101.2 = STRING: "CONNECTIONS:65**
```
Poller cmd.php works correctly with these scripts.
The spine poller from cacti 0.8.8b worked correctly, but after the update, a double quote appeared in the output.

**Comment by TheWitness** [comment]
Just trim this in your script using 

```
echo blah | awk -F":" '{print $2}'
```

**Comment by bredis** [comment]
Either I am explaining that something is wrong or you do not understand me.
Your hint will not help me.
How can I use it with this kind of output?
```
root@ns:~# php -f /usr/share/cacti/site/scripts/query_freeradius.php -- radius.home 161 public
REQUESTS:13447 ACCEPTS:0 REJECTS:0 CHALLENGES:0 RESPONSES:0 DUPLICATE:0 MALFORMED:0 INVALID:0 DROPPED:0 UNKNOWN:0
root@ns:~#
```
Here's the output from cacti:
```
2020/11/23 18:29:06 - SPINE: Poller[1] Device[13] HT[1] DS[223] SCRIPT: /usr/bin/php /usr/share/cacti/site/scripts/query_freeradius.php 'radius.home' '161' 'public' , output: "REQUESTS:13432 ACCEPTS:0 REJECTS:0 CHALLENGES:0 RESPONSES:0 DUPLICATE:0 MALFORMED:0 INVALID:0 DROPPED:0 UNKNOWN:0
```
I will repeat in version 0.8.8b there is no problem with this script. There is no double quote in the output.
Wrong output from cacti spine = `"REQUESTS:13432`
