### ISSUE TITLE
Special characters may not always be ignored properly

### ISSUE THREAD

**Issue by DanielMarquezCortes** [Cacti/spine#166]
# Describe the bug

I have upgraded my Cacti Server into a new one with the last version of CentOS and sw. I was able to configure all data into the new server, but I have problems with temperature data.

I use two types of data in my graphs: Interface speed and Temperature. In the new server I got wrong temperature values. I have reviewed every single step in my configuration, but at last the only difference in the two servers was the sw version of Spine and Cacti.

So I installed the same Spine version from my old Cacti Server into the new One, and solved!. No need to make any configuration change.

Before date, my switch temperatures were between 700-900 ºC, then the proper ones (25-30ºC).

Spine affected versions: Spine-1.2.14 and Spine-1.2.13
It worked properly with Spine-1.1.24. No change are required.

## To Reproduce

1. The switches are from HP ARUBA.
2. In order to get the temperature by using a SNMP query, we use the following oid .1.3.6.1.4.1.11.2.14.11.1.2.8.1.1.3 
3. We will have a Data Source Template, a Graph Template, a Data Query (with "Get SNMP Data (Indexed)" as a Data Input Method)
4. We can test the spine result by using the following cli command.

	 /usr/local/spine/bin/spine -f <deviceID> -l <deviceID> --verbosity=5

We will have the following output for the oid requested:

A) Spine affected versions: Spine-1.1.24
2020-08-10 13:25:20 - SPINE: Poller[1] Device[36] TH[1] DS[259] SNMP: v3: <switchIp*>, dsname: tempv4_2, oid: .1.3.6.1.4.1.11.2.14.11.1.2.8.1.1.3.0, value: 34

B) Spine affected versions: Spine-1.2.14 and Spine-1.2.13
2020/08/10 13:17:10 - SPINE: Poller[1] PID[472594] Device[36] HT[1] DS[259] SNMP: v3: <switchIp*>, dsname: tempv4_2, oid: .1.3.6.1.4.1.11.2.14.11.1.2.8.1.1.3.0, value: 844

* For security concerns, I don't write the switch IP.

5. We don't need any special configuration, just use the new Spine version 1.2.x insted of the Spine 1.1.X to have this bug.

## Expected behavior

Temperature is not properly measured. Instead of ca. 25C we have 700.800 C!

## Desktop (please complete the following information)

- OS: CENTOS

- Browser Firefox and Chrome.

- Version anyone.

**Comment by DanielMarquezCortes** [comment]
Hi,

I have used the following command with spine-1.1.24 and spine-1.2.14:

/usr/local/spine/bin/spine -f 36 -l 36 -R --verbosity=5 --conf=/usr/local/spine/etc/spine.conf 

Then, I have compared the result by using Notepad++ with the Compare plugin. 

**A) spine-1.2.14 provides these output lines and 1.1.14 doesn't**

2020/08/12 09:28:39 - SPINE: Poller[1] PID[771750] DEBUG: The boost_rrd_update_enable variable is 0
2020/08/12 09:28:39 - SPINE: Poller[1] PID[771750] DEBUG: Spine running as 0 UID, 0 EUID
2020/08/12 09:28:39 - SPINE: Poller[1] PID[771750] DEBUG: Spine has got ICMP
2020/08/12 09:28:39 - SPINE: Poller[1] PID[771750] DEBUG: In Poller, About to Start Polling of Device for Device ID 0
2020/08/12 09:28:39 - SPINE: Poller[1] PID[771750] Device[0] HT[1] Total Time: 0.019 Seconds
2020/08/12 09:28:39 - SPINE: Poller[1] PID[771750] Device[0] HT[1] DEBUG: HOST COMPLETE: About to Exit Device Polling Thread Function
2020/08/12 09:28:39 - SPINE: Poller[1] PID[771750] DEBUG: The Value of Active Threads is 0 for Device ID 0
2020/08/12 09:28:39 - SPINE: Poller[1] PID[771750] POLLER: Active Threads is 0, Pending is 0
2020/08/12 09:28:39 - SPINE: Poller[1] PID[771750] DEBUG: Valid Thread to be Created
2020/08/12 09:28:39 - SPINE: Poller[1] PID[771750] SPINE: Active Threads is 1, Pending is 1
2020/08/12 09:28:39 - SPINE: Poller[1] PID[771750] Device[36] INFO: SNMP Device '<my_switch_ip_address>' has timeout 500000 (500), retries 3
2020/08/12 09:28:39 - SPINE: Poller[1] PID[771750] NOTE: Device[36] Checking for System Information Update
2020/08/12 09:28:39 - SPINE: Poller[1] PID[771750] Device[36] INFO: SNMP Device 'my_switch_ip_address' has timeout 500000 (500), retries 3

**B) These are the information about the oid providing by both spines:**

---- spine-1.1.24:

2020/08/12 09:28:39 - SPINE: Poller[1] PID[771750] Device[36] HT[1] DS[284] SNMP: v3: <my_switch_ip_address>, dsname: tempv4_1, oid: .1.3.6.1.4.1.11.2.14.11.1.2.8.1.1.3.0, value: 812
2020/08/12 09:28:39 - SPINE: Poller[1] PID[771750] Device[36] HT[1] DS[284] SNMP: v3: <my_switch_ip_address>, dsname: tempv4_2, oid: .1.3.6.1.4.1.11.2.14.11.1.2.8.1.1.3.0, value: 812
2020/08/12 09:28:39 - SPINE: Poller[1] PID[771750] Device[36] HT[1] DS[284] SNMP: v3: <my_switch_ip_address>, dsname: tempv4_3, oid: .1.3.6.1.4.1.11.2.14.11.1.2.8.1.1.3.0, value: 812
2020/08/12 09:28:39 - SPINE: Poller[1] PID[771750] Device[36] HT[1] DS[284] SNMP: v3: <my_switch_ip_address>, dsname: tempv4_4, oid: .1.3.6.1.4.1.11.2.14.11.1.2.8.1.1.3.0, value: 812

--- spine-1.2.14:

020-08-12 09:26:34 - SPINE: Poller[1] Device[36] TH[1] DS[284] SNMP: v3: <my_switch_ip_address>, dsname: tempv4_1, oid: .1.3.6.1.4.1.11.2.14.11.1.2.8.1.1.3.0, value: 32
2020-08-12 09:26:34 - SPINE: Poller[1] Device[36] TH[1] DS[284] SNMP: v3: <my_switch_ip_address>, dsname: tempv4_2, oid: .1.3.6.1.4.1.11.2.14.11.1.2.8.1.1.3.0, value: 32
2020-08-12 09:26:34 - SPINE: Poller[1] Device[36] TH[1] DS[284] SNMP: v3: <my_switch_ip_address>, dsname: tempv4_3, oid: .1.3.6.1.4.1.11.2.14.11.1.2.8.1.1.3.0, value: 32
2020-08-12 09:26:34 - SPINE: Poller[1] Device[36] TH[1] DS[284] SNMP: v3: <my_switch_ip_address>, dsname: tempv4_4, oid: .1.3.6.1.4.1.11.2.14.11.1.2.8.1.1.3.0, value: 32

**Comment by TheWitness** [comment]
That's quite unusual.  This is due to the missing strip_alpha() function.  34C in hex is 814 in decimal.

**Comment by TheWitness** [comment]
Update to the latest 1.2.x branch and let me know if the output is correct again.

**Comment by DanielMarquezCortes** [comment]
As I have written at the beginning of the issue, that happens, at least, with spine versions:  Spine-1.2.14 and Spine-1.2.13, which are the last published ones (https://www.cacti.net/downloads/spine/).

**Comment by TheWitness** [comment]
Right, you need to get the latest 1.2.x branch from Github:

```
git clone -b 1.2.x https://github.com/cacti/spine.git
```

**Comment by TheWitness** [comment]
No feedback.

**Comment by DanielMarquezCortes** [comment]
Last versión 1.2.16 works properly. Thank you so much!
