### ISSUE TITLE
 ERROR: Spine Timed Out While Processing Devices Internal

### ISSUE THREAD

**Issue by zhangjian420** [Cacti/spine#169]
cacti ver:1.2.4
spine:1.2.4
Devices 126
Graphs 3871
Centos7.6
crontab 1min
The log keeps outputting: ERROR: Spine Timed Out While Processing Devices Internal
![微信截图_20200827232327](https://user-images.githubusercontent.com/293321/91462360-ae0ffb00-e8bc-11ea-889b-c601a3226001.png)
![微信截图_20200827232348](https://user-images.githubusercontent.com/293321/91462383-b23c1880-e8bc-11ea-827f-d28266545ab1.png)

I also ran the command： ./spine -R -V 5 -S > a.txt
[a.zip](https://github.com/Cacti/cacti/files/5137349/a.zip)

I don't know where the problem occurred, please help me, thank you

**Comment by TheWitness** [comment]
I looked at the zip file, you are only using 1 thread.  You need to bump that up a bit higher.

**Comment by TheWitness** [comment]
These guys don't help either.

```
Device[212] HT[1] Total Time:    12 Seconds
Device[186] HT[1] Total Time:   2.8 Seconds
Device[122] HT[1] Total Time:   2.7 Seconds
Device[187] HT[1] Total Time:     2 Seconds
Device[185] HT[1] Total Time:     2 Seconds
Device[153] HT[1] Total Time:     2 Seconds
Device[132] HT[1] Total Time:     2 Seconds
Device[131] HT[1] Total Time:     2 Seconds
Device[130] HT[1] Total Time:     2 Seconds
Device[123] HT[1] Total Time:     2 Seconds
Device[117] HT[1] Total Time:     2 Seconds
Device[182] HT[1] Total Time:   1.8 Seconds
Device[16] HT[1] Total Time:   1.3 Seconds
Device[56] HT[1] Total Time:     1 Seconds
```

**Comment by TheWitness** [comment]
So, that's a bunch of down hosts, that are not responding to ping.  If you make the threads 15, should take ~12 seconds based upon device 212's polling time.
