### ISSUE TITLE
Spine V1.2.6 Signal Number: '6' [6, No such device or address] (Spine thread) 

### ISSUE THREAD

**Issue by picc8** [Cacti/spine#174]
Spine V1.2.6 / Cacti V 1.2.7

Randomly Spine crashes

cacti.log

> 2020/11/18 08:51:26 - SPINE: Poller[1] PID[12330] FATAL: Spine Encountered An Unhandled Exception Signal Number: '6' [6, No such device or address] (Spine thread)
> 2020/11/18 08:51:26 - PHPSVR ERROR: Input Expected, Script Server Terminating
> 2020/11/18 08:51:26 - PHPSVR ERROR: Input Expected, Script Server Terminating
> 2020/11/18 08:51:26 - PHPSVR ERROR: Input Expected, Script Server Terminating
> 2020/11/18 08:51:26 - PHPSVR ERROR: Input Expected, Script Server Terminating
> 2020/11/18 08:51:26 - PHPSVR ERROR: Input Expected, Script Server Terminating
> 2020/11/18 08:51:26 - PHPSVR ERROR: Input Expected, Script Server Terminating
> 2020/11/18 08:51:26 - PHPSVR ERROR: Input Expected, Script Server Terminating
> 2020/11/18 08:51:26 - PHPSVR ERROR: Input Expected, Script Server Terminating
> 2020/11/18 08:51:26 - PHPSVR ERROR: Input Expected, Script Server Terminating
> 2020/11/18 08:51:26 - PHPSVR ERROR: Input Expected, Script Server Terminating
> 2020/11/18 08:51:26 - PHPSVR ERROR: Input Expected, Script Server Terminating
> 2020/11/18 08:51:26 - PHPSVR ERROR: Input Expected, Script Server Terminating
> 2020/11/18 08:52:00 - POLLER: Poller[1] Maximum runtime of 58 seconds exceeded. Exiting.

cacti_stderr.log

> 7f1ba2f5d000-7f1ba315d000 ---p 00002000 103:*** Error in `/bin/spine': double free or corruption (out): 0x00007f1b8800b9d0 ***
> *** Error in `/bin/spine': double free or corruption (out): 0x00007f1b7400b9d0 ***
> 02 111734                    /usr/lib64/libdl-2.17.so
> 7f1ba315d000-7f1ba315e000 r--p 00002000 103:02 111734                    /usr/lib64/libdl-2.17.so
> 7f1ba315e000-7f1ba315f000 rw-p 00003000 103:02 111734                    /usr/lib64/libdl-2.17.so
> 7f1ba315f000-7f1ba3176000 r-xp 00000000 103:02 1502644                   /usr/lib64/libpthread-2.17.so
> 7f1ba3176000-7f1ba3375000 ---p 00017000 103:02 1502644                   /usr/lib64/libpthread-2.17.so
> 7f1ba3375000-7f1ba3376000 r--p 00016000 103:02 1502644                   /usr/lib64/libpthread-2.17.so
> 7f1ba3376000-7f1ba3377000 rw-p 00017000 103:02 1502644                   /usr/lib64/libpthread-2.17.so
> 7f1ba3377000-7f1ba337b000 rw-p 00000000 00:00 0 
> 7f1ba337b000-7f1ba3390000 r-xp 00000000 103:02 88213                     /usr/lib64/libz.so.1.2.7
> 7f1ba3390000-7f1ba358f000 ---p 00015000 103:02 88213                     /usr/lib64/libz.so.1.2.7
> 7f1ba358f000-7f1ba3590000 r--p 00014000 103:02 88213                     /usr/lib64/libz.so.1.2.7
> 7f1ba3590000-7f1ba3======= Backtrace: =========
> /lib64/libc.so.6(+0x81299)[0x7f1ba26f6299]
> /bin/spine[0x41e6f8]
> /bin/spine[0x41c238]
> /bin/spine[0x41a968]
> /bin/spine[0x41983e]
> /bin/spine[0x40f2ad]
> /bin/spine[0x4119ed]
> /lib64/libpthread.so.0(+0x7ea5)[0x7f1ba3166ea5]
> /lib64/libc.so.6(clone+0x6d)[0x7f1ba27738dd]

gdb ./spine
 run -V 3 -f XXX -l XXX -S
> (gdb) run -V 3 -f XXX -l XXX -S
> Starting program: /usr/bin/spine -V 3 -f XXX -l XXX -S
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/lib64/libthread_db.so.1".
> SPINE: Using spine config file [/etc/spine.conf]
> SPINE: Version 1.2.6 starting
> NOTE: Spine will support multithread device polling.
> DEBUG: Initial Value of Active Threads is 0
> [New Thread 0x7fffee96c700 (LWP 3124)]
> SPINE: Active Threads is 1, Pending is 1
> Device[0] HT[1] Total Time: 0.0032 Seconds
> POLLER: Active Threads is 0, Pending is 0
> [Thread 0x7fffee96c700 (LWP 3124) exited]
> SPINE: The Final Value of Threads is 0
> Time: 0.1227 s, Threads: 45, Devices: 1
> [Inferior 1 (process 3120) exited normally]

**Comment by TheWitness** [comment]
Update to latest spine.  If the problem persists, ensure poller user can write a core, then upload to this ticket, or forward to developers at cacti dot net.

**Comment by picc8** [comment]
> Update to latest spine. If the problem persists, ensure poller user can write a core, then upload to this ticket, or forward to developers at cacti dot net.

Can i update to latest spine if i have Cacti 1.2.7?

**Comment by TheWitness** [comment]
Yes

**Comment by picc8** [comment]
That solved the error 6 but have random FATAL: Spine Encountered a Segmentation Fault [11, Resource temporarily unavailable] (Spine thread)

**Comment by TheWitness** [comment]
Collect and upload the core file once you have enabled it.  You can modify your cron like this:

```*/5 * * * * apache ulimit -a unlimited && php ...```

**Comment by picc8** [comment]
> Collect and upload the core file once you have enabled it. You can modify your cron like this:
> 
> `*/5 * * * * apache ulimit -a unlimited && php ...`

* * * * *       eleum       /usr/bin/php /var/www/vhosts/eleum/httpdocs/poller.php > /dev/null 2>&1
in this case i should do:
* * * * *       eleum ulimit -a unlimited &&   /usr/bin/php /var/www/vhosts/eleum/httpdocs/poller.php > /dev/null 2>&1

? Thanks

**Comment by TheWitness** [comment]
Well, you are missing something.  What's your cron interval?

**Comment by TheWitness** [comment]
Also, how often are you getting the 58 second errors?  Boost enabled?

**Comment by TheWitness** [comment]
Also, post the "SYSTEM STATS:" from around the time that there errors occurred.

**Comment by picc8** [comment]
My cron interval is every minute.
Boost is not enabled and i get the 58 second error 4-5 times every day


> 2020/11/23  01:05:20 - SYSTEM STATS: Time:19.5310 Method:spine Processes:2  Threads:45 Hosts:16 HostsPerProcess:8 DataSources:816 RRDsProcessed:698
> --
> 2020/11/23 01:04:21 - SYSTEM STATS: Time:20.3596 Method:spine  Processes:2 Threads:45 Hosts:16 HostsPerProcess:8 DataSources:816  RRDsProcessed:698
> 2020/11/23 01:03:22 - SYSTEM STATS: Time:20.5562 Method:spine  Processes:2 Threads:45 Hosts:16 HostsPerProcess:8 DataSources:816  RRDsProcessed:698
> 2020/11/23 01:03:02 - SYSTEM WARNING: Primary Admin account notifications disabled!  Unable to send administrative Email.
> 2020/11/23 01:03:02 - POLLER: Poller[Main Poller] WARNING: There are 2 processes detected as overrunning a polling cycle, please investigate
> 2020/11/23 01:03:00 - SYSTEM STATS: Time:59.2315 Method:spine  Processes:2 Threads:45 Hosts:16 HostsPerProcess:8 DataSources:816  RRDsProcessed:698
> 2020/11/23 01:03:00 - SNMPAGENT WARNING: No notification receivers  configured for event: cactiNotifyPollerRuntimeExceeding (CACTI-MIB),  severity: high
> 2020/11/23 01:03:00 - SYSTEM WARNING: Primary Admin account notifications disabled!  Unable to send administrative Email.
> 2020/11/23 01:03:00 - POLLER: Poller[Main Poller] Maximum runtime of 58 seconds exceeded. Exiting.
> 2020/11/23 01:02:38 - PHPSVR ERROR: Input Expected, Script Server Terminating
> 2020/11/23 01:02:38 - PHPSVR ERROR: Input Expected, Script Server Terminating
> 2020/11/23 01:02:38 - PHPSVR ERROR: Input Expected, Script Server Terminating
> 2020/11/23 01:02:38 - PHPSVR ERROR: Input Expected, Script Server Terminating
> 2020/11/23 01:02:38 - PHPSVR ERROR: Input Expected, Script Server Terminating
> 2020/11/23 01:02:38 - PHPSVR ERROR: Input Expected, Script Server Terminating
> 2020/11/23 01:02:38 - PHPSVR ERROR: Input Expected, Script Server Terminating
> 2020/11/23 01:02:38 - PHPSVR ERROR: Input Expected, Script Server Terminating
> 2020/11/23 01:02:38 - PHPSVR ERROR: Input Expected, Script Server Terminating
> 2020/11/23 01:02:38 - PHPSVR ERROR: Input Expected, Script Server Terminating
> 2020/11/23 01:02:38 - PHPSVR ERROR: Input Expected, Script Server Terminating
> 2020/11/23 01:02:38 - PHPSVR ERROR: Input Expected, Script Server Terminating
> 2020/11/23 01:02:38 - SPINE: Poller[Main Poller] PID[15273] FATAL: Spine Encountered a Segmentation Fault [11, Resource temporarily unavailable] (Spine thread)
> 2020/11/23 01:02:38 - SPINE: Poller[Main Poller] PID[15278] FATAL: Spine Encountered a Segmentation Fault [11, Resource temporarily unavailable] (Spine thread)
> 2020/11/23 01:01:21 - SYSTEM STATS: Time:20.4926 Method:spine  Processes:2 Threads:45 Hosts:16 HostsPerProcess:8 DataSources:816  RRDsProcessed:698


> 2020/11/23  08:28:22 - SYSTEM STATS: Time:20.5220 Method:spine Processes:2  Threads:45 Hosts:16 HostsPerProcess:8 DataSources:816 RRDsProcessed:698
> --
> 2020/11/23 08:28:01 - SYSTEM WARNING: Primary Admin account notifications disabled!  Unable to send administrative Email.
> 2020/11/23 08:28:01 - POLLER: Poller[Main Poller] WARNING: There are 2 processes detected as overrunning a polling cycle, please investigate
> 2020/11/23 08:28:00 - SYSTEM STATS: Time:59.1776 Method:spine  Processes:2 Threads:45 Hosts:16 HostsPerProcess:8 DataSources:816  RRDsProcessed:698
> 2020/11/23 08:28:00 - SNMPAGENT WARNING: No notification receivers  configured for event: cactiNotifyPollerRuntimeExceeding (CACTI-MIB),  severity: high
> 2020/11/23 08:28:00 - SYSTEM WARNING: Primary Admin account notifications disabled!  Unable to send administrative Email.
> 2020/11/23 08:28:00 - POLLER: Poller[Main Poller] Maximum runtime of 58 seconds exceeded. Exiting.
> 2020/11/23 08:27:29 - PHPSVR ERROR: Input Expected, Script Server Terminating
> 2020/11/23 08:27:29 - PHPSVR ERROR: Input Expected, Script Server Terminating
> 2020/11/23 08:27:29 - PHPSVR ERROR: Input Expected, Script Server Terminating
> 2020/11/23 08:27:29 - PHPSVR ERROR: Input Expected, Script Server Terminating
> 2020/11/23 08:27:29 - PHPSVR ERROR: Input Expected, Script Server Terminating
> 2020/11/23 08:27:29 - PHPSVR ERROR: Input Expected, Script Server Terminating
> 2020/11/23 08:27:29 - PHPSVR ERROR: Input Expected, Script Server Terminating
> 2020/11/23 08:27:29 - PHPSVR ERROR: Input Expected, Script Server Terminating
> 2020/11/23 08:27:29 - PHPSVR ERROR: Input Expected, Script Server Terminating
> 2020/11/23 08:27:29 - PHPSVR ERROR: Input Expected, Script Server Terminating
> 2020/11/23 08:27:29 - PHPSVR ERROR: Input Expected, Script Server Terminating
> 2020/11/23 08:27:29 - PHPSVR ERROR: Input Expected, Script Server Terminating
> 2020/11/23 08:27:29 - SPINE: Poller[Main Poller] PID[27414] FATAL: Spine Encountered a Segmentation Fault [11, Resource temporarily unavailable] (Spine thread)
> 2020/11/23 08:27:29 - SPINE: Poller[Main Poller] PID[27405] FATAL: Spine Encountered a Segmentation Fault [11, Resource temporarily unavailable] (Spine thread)
> 2020/11/23 08:26:22 - SYSTEM STATS: Time:20.6873 Method:spine  Processes:2 Threads:45 Hosts:16 HostsPerProcess:8 DataSources:816  RRDsProcessed:698
> 2020/11/23 08:25:22 - SYSTEM STATS: Time:20.5937 Method:spine  Processes:2 Threads:45 Hosts:16 HostsPerProcess:8 DataSources:816  RRDsProcessed:698
> 2020/11/23 08:24:22 - SYSTEM STATS: Time:20.8428 Method:spine  Processes:2 Threads:45 Hosts:16 HostsPerProcess:8 DataSources:816  RRDsProcessed:698

**Comment by TheWitness** [comment]
Core file please.

**Comment by picc8** [comment]
> Core file please.

I don't know how to edit my cron job to collect core file

**Comment by TheWitness** [comment]
```
*/n * * * * ulimit -a unlimited && php /blah/poller.php --force
```

Replace n with whatever you have today.

**Comment by TheWitness** [comment]
Then, read up on using gdb to backtrace a core file.  No need to upload it, but rather just send the backtrace once the core file is created.

**Comment by TheWitness** [comment]
Here is an interesting article on plucking around with core files too:

https://www.suse.com/support/kb/doc/?id=000015982

**Comment by TheWitness** [comment]
If you update to the latest spine, it will output the stack trace to standard error.  Hopefully that'll give a clue.  You will use the 1.2.x branch.  I just committed the change.

**Comment by picc8** [comment]
Thanks about the article.

Yup, I updated to latest spine and i have many of those errors:

ls: cannot access /proc/18684/fd/: No such file or directory
ls: cannot access /proc/18685/fd/: No such file or directory
ls: cannot access /proc/18993/fd/: No such file or directory
ls: cannot access /proc/21287/fd/: No such file or directory
ls: cannot access /proc/21337/fd/: No such file or directory
ls: cannot access /proc/21437/fd/: No such file or directory
ls: cannot access /proc/21448/fd/: No such file or directory
ls: cannot access /proc/21803/fd/: No such file or directory
ls: cannot open directory /proc/23307/fd/: No such file or directory
ls: cannot access /proc/23983/fd/: No such file or directory
ls: cannot access /proc/24865/fd/: No such file or directory
ls: cannot access /proc/24896/fd/: No such file or directory
ls: cannot access /proc/25386/fd/: No such file or directory
ls: cannot access /proc/25534/fd/: No such file or directory
ls: cannot access /proc/25534/fd/: No such file or directory
ls: cannot access /proc/25567/fd/: No such file or directory
ls: cannot access /proc/27979/fd/: No such file or directory
ls: cannot access /proc/27979/fd/: No such file or directory
ls: cannot access /proc/28231/fd/: No such file or directory
ls: cannot access /proc/28645/fd/: No such file or directory

**Comment by TheWitness** [comment]
Post that output once you have it.

**Comment by TheWitness** [comment]
Those errors look like maybe nifty popen issues.  There is a make option to use standard popen.  See if that helps.

**Comment by picc8** [comment]
> Those errors look like maybe nifty popen issues. There is a configure option to use standard popen. See if that helps.

Where I can find it?

**Comment by TheWitness** [comment]
```sh
./configure --help
```

**Comment by picc8** [comment]
> ```shell
> ./configure --help
> ```

ok, found it. Thanks.
I recompiled Spine to 1.2.16 with standard popen: let me doing some tests and give you a feedback.

**Comment by picc8** [comment]
Problem solved changing some slow query log by PHP scripts. Thanks a lot! :)
