### ISSUE TITLE
Spine Encountered An Unhandled Exception Signal Number: '6' [11, Resource temporarily unavailable] (Spine thread)

### ISSUE THREAD

**Issue by hariesfn** [Cacti/spine#177]
Hi, 

Actually i have issue in https://github.com/Cacti/cacti/issues/3948. 
Already followed the suggestion but the issue still happened. I also have increased the RAM from 8GB to 12 GB.

My finding, if I got "Spine Encountered An Unhandled Exception Signal Number: '6' [11, Resource temporarily unavailable] (Spine thread)", I will get error about exceeded of poller-time log. ( Maximum runtime of 298 seconds exceeded. Exiting).
But what made me curious is between the last message of spine and message of system stats has 4 minutes of time gaps. 

What makes the polling time exceed 298 seconds ? Since Spine has finished the task after 50 seconds.

Log for last message of spine and Cacti system stats:
[cacti-spine-system_stat.txt](https://github.com/Cacti/spine/files/5605877/cacti-spine-system_stat.txt)

Log for PID 29100 that brings "Spine, Resource temporarily unavailable" message:
[spine_pid29100.txt](https://github.com/Cacti/spine/files/5605884/spine_pid29100.txt)

**Comment by TheWitness** [comment]
How often is this occurring?  What OS and version?  Which GCC version?

**Comment by TheWitness** [comment]
Let's also see if this is reproducible.  I think it's tied to Device[10].  So, open a shell on the server, cd to the spine directory and run spine this way:

```sh
./spine -R -V 5 -S -f 10 -l 10
```

Let's see if it reliably crashes on that device.

**Comment by TheWitness** [comment]
If you update to the latest spine, it will output the stack trace to standard error.  Hopefully that'll give a clue.  You will use the 1.2.x branch.

**Comment by hariesfn** [comment]
Hi @TheWitness ,

I already use spine 1.2.15 btw
- gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
- Ubuntu 18.04.4 LTS 
- Usually it happens once or twice within 2 hours, but why i got error that poller was overrun although the spine only needs 50-60 seconds to finish its task. (as i mentioned earlier)

I made a script to query that device consecutively and I want to query that device 5000 times. So far already did 1025 times  by using the command you asked.
[spine_query_result.txt](https://github.com/Cacti/spine/files/5610703/spine_query_result.txt)

And the longest time took 84 second to finish the query. 
[spine-result_28Nov2020_175909.txt](https://github.com/Cacti/spine/files/5610704/spine-result_28Nov2020_175909.txt)

**Comment by TheWitness** [comment]
How many device threads are you using BTW?  Does that help?

**Comment by TheWitness** [comment]
So, make sure you update spine to the latest 1.2.x branch.  That way we will find out in your cacti_stderr.log where the code is getting signaled.

**Comment by hariesfn** [comment]
Hi @TheWitness ,

I tried again to query by using your previous command for all the devices. And the longest duration is 84 seconds.
I use 10 threads :

DEBUG: The log_destination variable is 4 (STDOUT)
DEBUG: The path_php variable is /usr/bin/php
DEBUG: The availability_method variable is 4
DEBUG: The ping_recovery_count variable is 3
DEBUG: The ping_failure_count variable is 2
DEBUG: The ping_method variable is 1
DEBUG: The ping_retries variable is 1
DEBUG: The ping_timeout variable is 400
DEBUG: The snmp_retries variable is 3
DEBUG: The log_perror variable is 1
DEBUG: The log_pwarn variable is 1
DEBUG: The boost_redirect variable is 1
DEBUG: The boost_rrd_update_enable variable is 1
DEBUG: The log_pstats variable is 1
DEBUG: The threads variable is 10
DEBUG: The polling interval is 300 seconds
DEBUG: The number of concurrent processes is 1
DEBUG: The script timeout is 25
DEBUG: The selective_device_debug variable is
DEBUG: The spine_log_level variable is 1
DEBUG: The number of php script servers to run is 5
DEBUG: StartDevice='1', EndDevice='26', TotalPHPScripts='0
DEBUG: The PHP Script Server is Not Required
DEBUG: The Maximum SNMP OID Get Size is 10
Version 1.2.15 starting

And I've seen cacti_stderr.log. It has : 
free(): double free detected in tcache 2
double free or corruption (!prev)
free(): double free detected in tcache 2
free(): double free detected in tcache 2
free(): double free detected in tcache 2
free(): double free detected in tcache 2
free(): double free detected in tcache 2
free(): double free detected in tcache 2
free(): double free detected in tcache 2
free(): double free detected in tcache 2
free(): double free detected in tcache 2
free(): double free detected in tcache 2
free(): double free detected in tcache 2

**Comment by TheWitness** [comment]
device_threads is something completely different.  Edit the device, and look for the setting for the Device that has the longest average collect time.  Then, double the Device Threads there.  Report back.  Those double free's are useful, just need to trace where they are coming from.  Have you compiled the new spine and started using it yet?

**Comment by hariesfn** [comment]
Hi,

About the device threads, i will double it up and report back. I already use latest spine, it's 1.2.15 right ? I have used it from the first install. So I assume the double free message is not a problem then.

**Comment by TheWitness** [comment]
No, per my previous instructions, you have to download the 1.2.x branch from here.

**Comment by hariesfn** [comment]
Sorry.

Maybe i missed in following your instruction. What i did was following https://github.com/Cacti/spine and download and install from https://www.cacti.net/spine_download.php (stable version).CMIIW

**Comment by TheWitness** [comment]
I instructed you to download the latest branch 1.2.x from Github, which is something completely different.  You should google how to do that, but if you are on linux, you can simply run:

```sh
git clone -b 1.2.x https://github.com/Cacti/spine.git
```

**Comment by hariesfn** [comment]
Sorry. I just knew that it's already 1.2.16 in this branch.

**Comment by TheWitness** [comment]
So, when you run:

```sh
./spine --version
```

You get 1.2.16?

**Comment by TheWitness** [comment]
That's what you should get, otherwise, you are not running the right version.

**Comment by hariesfn** [comment]
Hi @TheWitness ,

I have updated my spine and the version  is 1.2.16. The "resource temporarily unavailable" already gone. 
Now I see new column in the cacti log (TT column).
2020-11-30 13:45:42 - SPINE: Poller[1] PID[9146] Device[26] HT[1] DS[32379] TT[43.47] SNMP: v2: 10.255.10.63, dsname: ifspeed, oid: .1.3.6.1.2.1.2.2.1.5.193681, value: 15360000.

Does it mean duration in milisecond to get OID query answered? 
Sometimes, I get poller overrun log. I think I need to add more thread to those devices.

**Comment by TheWitness** [comment]
Yes, TT is the time required to get the single value.

**Comment by hariesfn** [comment]
Hi

Is it possible to let the poller overrun from 298 seconds ? 
Since we have conditions that sometimes the device become slow to response snmp query. 
I've tried to increase amount of OID to query in a time (Maximum OID per request), the device won't respond the query at all. 

Will it impacting other plugins such as boost or thold ? Or maybe do you have any experience about that kind of issue

**Comment by TheWitness** [comment]
You have to be careful with max OIDS as you are finding out.  It might be safer to use two threads or purchase a device with a more robust snmp agent next time.

**Comment by TheWitness** [comment]
What device type is it BTW?

**Comment by hariesfn** [comment]
It's a CMTS box. 
Do you have any experience that might the same condition as me ?

**Comment by TheWitness** [comment]
Yea, like old Cisco 4500's back in the day, and some old Junipers.  Both had horrible snmp agents.  This is why Max OIDS was created, to minimize the impact of RTL on data collection.

Device Threads was written for devices that have tens of thousands of data sources using something fast, like the script server and local data.

**Comment by hariesfn** [comment]
So, I assume the best apporach is to get more cacti servers for slow-response devices.

**Comment by TheWitness** [comment]
Well, it depends on what you mean.  But if you have a device that is distant, say 200ms away, and you have 1000 values to fetch, do the math.  It's quite simple, and there are two ways to overcome on a single server setup, more device Threads or more kids per get request 

The third option, possiblesince Cacti 1.0, is to place a data collector closer to the switches.  Some people are using even devices like raspberry pis for this.  It does not take that much.

**Comment by TheWitness** [comment]
More long term, we will likely look to something telemetry for some of this stuff.  But because I'm not in the network space these days, and my time is short, it'll likely have to come from others.

**Comment by TheWitness** [comment]
I recommend that you test the latest 1.2.x branch.  There have been a number of changes lately.  Check them out.  I'll close this in hopes that it resolved the issues.  If not, let me know.
