### ISSUE TITLE
spine v.1.1.2 make problem

### ISSUE THREAD

**Issue by aminli** [Cacti/spine#18]
OS : freebsd v11
net-snmpd v5.7.3

Problem during make command:
_# make
cc -DHAVE_CONFIG_H -I. -I./config -I/usr/local/include/mysql -g -O2 -MT sql.o -MD -MP -MF .deps/sql.Tpo -c -o sql.o sql.c
In file included from sql.c:34:
./common.h:134:10: fatal error: 'net-snmp/net-snmp-config.h' file not found
#include <net-snmp/net-snmp-config.h>
^
1 error generated.
*** Error code 1

Stop.
make: stopped in /usr/home/amin/cacti-spine-1.1.2_

**Comment by cigamit** [comment]
See the other ticket.  If you can figure out what you are doing wrong, or what is wrong with the configure script.  Please submit a pull request.  Until then, I will close.
