### ISSUE TITLE
Force tcp instead of udp

### ISSUE THREAD

**Issue by Lejooohn** [Cacti/spine#181]
Hi there !

a long time ago we could use this trick : tcp:hostname:port to force using tcp instead of udp.

We using now the latest version of cacti (and spine) and this trick doesn't work anymore.

How can we do to force tcp connexion now? (we dont want use tcp connexion on all of ours devices, just few of them).

Regards

**Comment by netniV** [comment]
I have made a change for this, but I think it may need verifying and extending.  You should review it @TheWitness as it may change/break some functionality.
