### ISSUE TITLE
[1.2.17] cygwin compile execinfo.h missing

### ISSUE THREAD

**Issue by BSOD2600** [Cacti/spine#185]
Documenting the bug from an earlier conversation.

compiling under cygwin, it fails due to the following:

`configure:14024: checking if we can support backtracing
configure:14051: gcc -o conftest.exe -I/usr/include/net-snmp -I/usr/include/net-snmp/.. -I/usr/include/mysql -g -O2  -L/usr/lib -L/usr/lib  conftest.c -lnetsnmp -lmysqlclient -lm -ldl -lmysqlclient -lm -ldl -lcrypto -lz -lpthread -ldl -lm -lpthread -lssl  >&5
conftest.c:65:14: fatal error: execinfo.h: No such file or directory
   65 |     #include <execinfo.h>
      |              ^~~~~~~~~~~~
compilation terminated.
`

Quick Googling, looks like this is a known issue with cygwin, as execinfo.h is apparently only available on Linux: 
https://stackoverflow.com/questions/44109274/execinfo-h-missing-when-installing-xgboost-in-cygwin 
http://cygwin.1069669.n5.nabble.com/backtrace-3-in-Cygwin-td116597.html 
https://github.com/orangeduck/Cello/issues/85
https://github.com/marbl/canu/issues/689

**Comment by TheWitness** [comment]
Chris, it does not break anything.  The file is missing on many other platforms.  I reviewed libvirt, and though it's there, it's not in use.  Something is wrong with your build environment as I just checked out the 1.2.x branch and it built just fine on the latest Cygwin.
