### ISSUE TITLE
[SPINE] latest 1.2.x branch - FATAL: Spine Encountered a Segmentation Fault

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/spine#189]
**Describe the bug**
if you compile from sources with the latest commits you get the error in the logs:
FATAL: Spine Encountered a Segmentation Fault 

**To Reproduce**
/usr/local/spine/bin/spine -R -S -V 3
2021/02/16 16:47:08 - SPINE: Poller[1] PID[42821] FATAL: Unable to read configuration file! (Spine init)
Generating backtrace...4 line(s)...
2021/02/16 16:47:08 - SPINE: Poller[1] PID[42821] FATAL: Spine Encountered a Segmentation Fault (Spine init)
Generating backtrace...7 line(s)...
Segmentation fault (core dumped)

**Compiling (please complete the following information):**
I have reverted to commit --> a0a254fa51903873fc1d24d74b44437ac375f4f7 (HEAD -> 1.2.x) Fixing Issue #184
After compiling there were no more problems.

**Comment by TheWitness** [comment]
Oh, interesting.

**Comment by TheWitness** [comment]
So, the change that was made originally bothered me.  We only really care about a stacktrace with a segfault.  So, I've moved the code around.  It's cleaner now in my opinion.

**Comment by anarkia1976** [comment]
Very good, fixed now. thanks a lot as always.
