### ISSUE TITLE
MySQL SSL Key capability check does not work

### ISSUE THREAD

**Issue by jjthiessen** [Cacti/spine#202]
The following lines do `#ifdef`s over what appear to be `enum` values (see `mysql.h` in either the MySQL or MariaDB C client library source). I was unable to find corresponding `#define`s in current versions of spine, current MySQL client library headers, and current MariaDB client library headers.

* https://github.com/Cacti/spine/blob/develop/sql.c#L247
* https://github.com/Cacti/spine/blob/develop/sql.c#L251
* https://github.com/Cacti/spine/blob/develop/sql.c#L256

This results in the enclosed blocks always being skipped/never getting compiled in.
In particular, this precludes the use of SSL/TLS (as configured with `spine.conf`, at least — I haven't tried using `my.cnf`, but I think that we'd have to set the `MYSQL_READ_DEFAULT_FILE` or `MYSQL_READ_DEFAULT_GROUP` options for that to work).

You can validate this by reading the associated referenced code, running an example like the following to see `#define` _vs_ `enum` label behaviour, and load spine up in `gdb` (continuing over a break point on `mysql_options` to verify that nothing in the referenced `#ifdef` enclosed blocks are ever run).

**`enum` _vs_ `#define`**:
```
$ cat test.c 
int main () {
  enum foo {
    QWER,
    ASDF,
    ZXCV
  };

  #ifdef ASDF
    return 1;
  #else
    #define ASDF hi
  #endif

  #ifdef ASDF
  return 2;
  #endif

  return 0;
}

$ gcc test.c; ./a.out; echo $?
2
```

I think that we can just remove the conditional `#ifdef` directives (leaving the contents in tact), and everything should be fine? If we're worried about header additions/removals over time, maybe these should be switched to MySQL _vs_ MariaDB + ` MYSQL_VERSION_ID` checks?

I don't think that there's a straightforward way to validate/verify the existence of the individual `enum` labels in C (I'm also assuming that was the original intent of including the `#ifdef`s). I'm not terribly proficient in C, but I'm not sure how I would do this at all for `enum`s that are defined externally.

**Comment by netniV** [comment]
If I recall correctly, the defines should come from running the configure system. So, whilst they may appear to be the same as the enum names they are in fact a separate entity. 

Some defines are set by MySQL and/or MariaDB development header files but again those are separate to any enum or field definitions. 

It may be that configure isn't setting the defines because it couldn't correctly locate the header files.

**Comment by TheWitness** [comment]
I tested by breaking the backtrace functionality and the config/config.h properly commented out the constant.  So, unless the linux variant includes an execinfo.h, and not the glibc library, it should compile.

**Comment by jjthiessen** [comment]
@TheWitness, I think that your comment is for issue #201

@netniV, I also thought it might be autotools magic, but then I'd expect `MYSQL_OPT_SSL_KEY` to show up somewhere in spine's `configure.ac` or generated `configure` (or at least a reference to a header file that would include an associated `#define`). The only place that `MYSQL_OPT_SSL_KEY` shows up in the spine codebase is in `sql.c`. The only upstream MySQL header that's brought in by spine (conditionally or otherwise) is the main `mysql.h` header.

I'm still failing to see where the `MYSQL_OPT_*` `#define`s are supposed to exist.

**Comment by jjthiessen** [comment]
I ask about whether SSL/TLS is for sure working as implemented because spine doesn't set `MYSQL_OPT_SSL_MODE`. If `require_secure_transport` isn't manually set on the MySQL server and the connecting user doesn't have `REQUIRE SSL` (or another related SSL/TLS option) set for it, MySQL will automatically fallback to using an unencrypted connection if there are any problems establishing an encrypted connection (and everything will look like it's working correctly). This is really easy to miss in testing if you aren't taking `tcpdump`s (or `tail`ing the `general_log`) to verify things.

**Comment by netniV** [comment]
I don't have a mariadb with SSL keys setup right now to test against, but I can see the problem with configure.ac and I spotted another too with bracktracing support that will never work.
