### ISSUE TITLE
Poller overrunning (Spine 1.2.17)

### ISSUE THREAD

**Issue by skyjou** [Cacti/spine#205]
**Describe the bug**
After upgrade to version 1.2.17, Cacti complains poller "overrunning a polling cycle".

**To Reproduce**
Upgrade from 1.2.16 to 1.2.17

**Expected behavior**
Should be end normally in each cycle.

**Screenshots**
![Screenshot from 2021-05-13 08-42-35](https://user-images.githubusercontent.com/13309854/118061361-689e4a00-b3c7-11eb-8203-d8ac5571857c.png)

**Server (please complete the following information):**
 - OS: [Ubuntu 18.04]
 - Version [Cacti 1.2.17]

**Compiling (please complete the following information):**

 - compiler: [gcc 7.5.0]
 - autoconf: [2.69]
 - glibc: [2.27]
 - source: [release 1.2.17]

**Additional context**
It's working fine on Ubuntu 20.04, but both of our Ubuntu 18.04 servers are affected by this issue.
(Spine seems get and write data correctly)
When I downgrade Spine from 1.2.17 to 1.2.16, poller can end successfully in each cycle.

**Comment by netniV** [comment]
Have you tried runnning spine in debug mode to see what output you get ?

**Comment by TheWitness** [comment]
No feedback.
