### ISSUE TITLE
1.2.17 SPINE: Poller[Main Poller] PID[23312] ERROR: Spine Timed Out While Waiting for xxx Threads to End

### ISSUE THREAD

**Issue by terrellgf** [Cacti/spine#206]
# Describe the bug

Cacti often fails to collect monitoring data.
![图片](https://user-images.githubusercontent.com/54665471/122184554-e8d03780-cebe-11eb-8236-f6077698102a.png)

There are SPINE errors in the Cacti log:
![图片](https://user-images.githubusercontent.com/54665471/122184708-10270480-cebf-11eb-8ca1-e20d4a53ea37.png)

I changed the collection frequency of each indicator to once every 10 seconds:
![图片](https://user-images.githubusercontent.com/54665471/122185254-86c40200-cebf-11eb-8f56-923f393863d6.png)
![图片](https://user-images.githubusercontent.com/54665471/122185277-8cb9e300-cebf-11eb-8fe8-e59e84bb51f8.png)

My server hardware configuration is as follows:
Two CPU: 2 x Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz (8 Cores/16 Threads every cpu )
RAM: 128GB

I have made some performance optimizations for SPINE:
![图片](https://user-images.githubusercontent.com/54665471/122184898-42d0fd00-cebf-11eb-8888-7a7cfd571a1b.png)

![图片](https://user-images.githubusercontent.com/54665471/122185445-afe49280-cebf-11eb-8b29-e6548ee93259.png)

![图片](https://user-images.githubusercontent.com/54665471/122185954-1e295500-cec0-11eb-8ec0-afeba61d62ff.png)

![图片](https://user-images.githubusercontent.com/54665471/122185508-bbd05480-cebf-11eb-908b-8720f7083782.png)

![图片](https://user-images.githubusercontent.com/54665471/122185576-c8ed4380-cebf-11eb-9348-37fc93da2cb7.png)

## To Reproduce

I can often see that the graph is not continuous. And the moment of the problem is shown in all the charts.

![图片](https://user-images.githubusercontent.com/54665471/122186139-4e70f380-cec0-11eb-817a-dd52acc98e88.png)

## Desktop (please complete the following information)

- OS: Windows

- Browser chrome/firefox

- Version chrome  91.0.4472.106/firefox 87.0

**Comment by terrellgf** [comment]
> So this suggests that the thread is being aborted due to an error. I have just pushed an update to spine which may help this [9e1f588](https://github.com/Cacti/spine/commit/9e1f58838f886814d6aa74d3fee7cef7e0fe47d6). I had an issue with a timeout so I have attempted a fix for it.
> 
> Unfortunately, I hadn't seen this issue until after I posted or I would have relocated this to the correct repository and tagged it.

Thanks a lot! But I have to wait until the next version is updated to verify. Currently I have reverted to version 1.2.15 because it has a minor problem than version 1.2.17.

**Comment by TheWitness** [comment]
The spine parent will attempt to kill itself after the poller timeout - 2 seconds.  It's real old code.  With today's cacti, we could allow the threads to run longer, but we don't want to risk having them stack up.  I would suggest you find the source of the blockage (could be a high timeout when polling a downed device backing things up).  You can always either toss more threads at the problem, or distribute the data collection to multiple collectors.

**Comment by TheWitness** [comment]
Okay, 10 second collection.  Bleeding edge.  Yea, this environment will be real sensitive to timeouts.  Won't be able to have too many devices.  A stream protocol might be better for something like this as not all devices answer questions right away, some snmp queries, if the snmp agent is poorly designed, can take a few milliseconds to a second to respond.  It's not been my experience with the modern net-snmp protocol, but things like Windows are absolutely horrible at snmp, and some older network hardware was not better.

**Comment by TheWitness** [comment]
Also, 320 threads, that's insane.  I would suggest that you need to distribute the poller.  MySQL does not handle that may queries against a single table too well.  You can insert, no problem, but that select query with 320 threads trying to point mysql at the same time, you are best served by adding more pollers with their own databases.  They don't have to be huge, an 8 core Rasberry Pi might even to it.

**Comment by TheWitness** [comment]
Most 'wise' installs never go above say 60 threads accross all processes.  And you box needs threads for both the database connections, and the spine connections.  So, if you have a 96 thread EPYC box, if you set threads at 48, and a single process, that might be just right.

**Comment by TheWitness** [comment]
With that said, I'm going to close this one.  You should be able to take this one up on the forums.
