### ISSUE TITLE
Failed to obtain script execution lock

### ISSUE THREAD

**Issue by eschoeller** [Cacti/spine#219]
Upgraded from spine 1.2.17 to 1.2.18 and immediately started getting dozens of these messages:

```
2021/07/16 20:16:26 - SPINE: Poller[1] PID[118133] ERROR: PT[140633848370944] Device[670]: Failed to obtain a script execution lock within 10 seconds
2021/07/16 20:16:26 - SPINE: Poller[1] PID[118133] ERROR: PT[140633327003392] Device[834]: Failed to obtain a script execution lock within 10 seconds
2021/07/16 20:16:26 - SPINE: Poller[1] PID[118133] ERROR: PT[140632748168960] Device[727]: Failed to obtain a script execution lock within 10 seconds
2021/07/16 20:16:26 - SPINE: Poller[1] PID[118133] ERROR: PT[140631724783360] Device[724]: Failed to obtain a script execution lock within 10 seconds
2021/07/16 20:16:26 - SPINE: Poller[1] PID[118133] ERROR: PT[140631036909312] Device[670]: Failed to obtain a script execution lock within 10 seconds
2021/07/16 20:16:26 - SPINE: Poller[1] PID[118133] ERROR: PT[140632798525184] Device[724]: Failed to obtain a script execution lock within 10 seconds
2021/07/16 20:16:26 - SPINE: Poller[1] PID[118133] ERROR: PT[140632773347072] Device[665]: Failed to obtain a script execution lock within 10 seconds
2021/07/16 20:16:27 - SPINE: Poller[1] PID[118133] ERROR: PT[140631003338496] Device[669]: Failed to obtain a script execution lock within 10 seconds
2021/07/16 20:16:27 - SPINE: Poller[1] PID[118133] ERROR: PT[140631674427136] Device[665]: Failed to obtain a script execution lock within 10 seconds
```

I reverted back to 1.2.17. Any tips on what I should be looking into, let me know. I am running on new hardware, and I haven't done a lot of performance tuning yet.

**Comment by eriksejr** [comment]
Reconfigure & recompile with a higher value for max-scripts. I had a similar issue, the default was too low for my environment.

**Comment by eschoeller** [comment]
I guess my confusion stems from the fact that 1.2.17 runs fine and 1.2.18 doesn't. Same configure options, same environment. So what changed in spine?

**Comment by jdcoats** [comment]
1.2.18 spine is broken period. I'm unsure why it is still sitting there for download. Use 1.2.17 until another release or it is at least fixed in 1.2.x branch.

**Comment by netniV** [comment]
Yes, despite being tested on several systems, there are some issues out in the wild.  We will hopefully have another build soon to test with.

**Comment by TheWitness** [comment]
Any updates guys?  @eschoeller or @jdcoats ?

**Comment by jdcoats** [comment]
Working good for me so far. Thanks!

**Comment by eschoeller** [comment]
What changed? I don't see a new release yet.

**Comment by netniV** [comment]
@eschoeller we are trying to do some pre-release testing here if you can.  You'd need to download the branch code, which can be done from the Code tab clicking on the Code button:

![image](https://user-images.githubusercontent.com/9052188/132733516-e497086b-349d-45f0-addf-a744cca12e0c.png)

**Comment by eschoeller** [comment]
Gotcha. I don't really have a test environment. And I can't really risk de-stabilizing production right now, I'm switching jobs (internally) and it's not entirely clear how much time I'll have for Cacti moving forward :(

**Comment by TheWitness** [comment]
Well that sucks @eschoeller.  Me too.  I'm pretty certain I'll still be contributing.  Good luck in your new role.

**Comment by netniV** [comment]
> eschoeller and it's not entirely clear how much time I'll have for Cacti, but I'm going to make damn sure my replacement loves it!

Aww thanks :D  Congratulations on the (pro)motion!

**Comment by eschoeller** [comment]
Just upgraded from 1.2.17 to 1.2.19. Still getting the script execution lock errors.

**Comment by eschoeller** [comment]
I recompiled with max-scripts=48. No change.
Then I reduced the number of PHP script servers from 10 to 5. That didn't help. 
Then I started tinkering around with the "Script and Script Server Timeout Value". I had it set at '20'. I bumped it to '45' and the errors went away. Then I dropped it down to '30' and they came back, but in less frequency/quantity. Then I bumped it to '32'. and the frequency nearly went away, but a few still leaked in every other poller run. So I bumped it back up to '40' and changed the 'Number of PHP Script Servers' from '5' back to '10'. I ran for 20 polling cycles with no errors. 
Then I went back and re-complied with the standard max-scripts. Ran for another 10 polling cycles with no problem.

So, I dunno what the heck is going on, but I think there is some kind of race condition related to the 'Script and Script Server Timeout Value'. If it's set less than 30, this execution lock really kicks in. I can't spend any more time digging into it, but I have a work-around now to just increase this setting, I guess. 

Sorry I wasn't around to do this testing when you needed it .... I wasn't really supposed to be working on this stuff in my old role that I had for the last 10 years, and now I'm *really* not "supposed" to be doing this stuff anymore (but I guess it really depends on how you look at it / justify it) ... but there's nobody else here capable (or willing) to inherit all this from me. 

Oh, and let me know if you want me to open a new issue for this since it was closed.

**Comment by eschoeller** [comment]
Oh, and just an FYI. Yes, I'll openly admit I have a lot of really crappy scripts running. Oh well. But my poller runtime is 13-14 seconds on the main poller right now (where these errors were cropping up) so I can't imagine anything is really 'timing out', since my original 20 second timeout value was larger than the entire length of the polling cycle. 

Hope this all helps.

**Comment by eschoeller** [comment]
However, now I've just noticed that 2/5 of my remote pollers are tossing out about 5 script execution lock errors every polling cycle. Increasing the script timeout value even further to 50 seconds doesn't seem to help. Hopefully I'm not actually losing data. I may have to downgrade the remote pollers back to 1.2.17, not sure. I bet these two pollers are running a lot more scripts than the others are.

**Comment by eschoeller** [comment]
Sorry to report, the errors are still there. Snagged version d4de19a6dc0c70138bf42809ded465af51eb6be9 from 1.2.x branch.

**Comment by eschoeller** [comment]
Any update on this?

**Comment by netniV** [comment]
Sorry, I haven't had chance to circle back around, not enough free time.

**Comment by eschoeller** [comment]
No problem. We seem to be running OK despite continually getting these errors. I don't exactly know what is "broken" because of it, but I guess ignorance is bliss. Someday I suppose I'll notice some blank graphs somewhere ... but for now I'm not looking too hard for them:) Thanks for all your efforts on this project!

**Comment by eschoeller** [comment]
I've upgraded cacti and spine to 1.2.21 and I'm still getting these errors :(

**Comment by TheWitness** [comment]
Try the 1.2.x branch.  Also, consider increasing your script timeout as that is what is burning you.

**Comment by eschoeller** [comment]
OK, I'll grab the latest code from the 1.2x branch. The script timeout was already set at 50 seconds. I can't go much higher than that with a 1 minute poller. I also just re-compiled with --max-scripts=100 and upped the number of php script servers to 30.

**Comment by TheWitness** [comment]
Oh, BTW, how would you like to test drive our new Packaging Plugin?  You can export Device Packages easily and publish them, on GitHub for example.

**Comment by TheWitness** [comment]
Same to your @jdcoats.  Both you guys been around for years and years.  It's not quite 100% ready for release and in it's release form will require 1.2.22 at a minimum, but I know you guys will give good feedback.  Here is an animation for it.  I'm working on the last two aspects right now which include selective import and certificate handling.  Let me know.  It won't be for a week or two as it's vacation season and I'm going on one, but soon thereafter.

![PackagePluginPreviewNew](https://user-images.githubusercontent.com/1439914/176669160-fd851d11-6a86-4b2b-8b03-0db031c55c4d.gif)
