### ISSUE TITLE
failed install Spine on MariaDB 10.2 (MariaDB 10.1 works fine)

### ISSUE THREAD

**Issue by Izmenoff** [Cacti/spine#22]
discussion on the cacti forum - http://forums.cacti.net/viewtopic.php?f=2&t=57563

libtool: link: gcc -I/usr/include/mysql -g -O2 -o spine sql.o spine.o util.o snmp.o locks.o poller.o nft_popen.o php.o ping.o keywords.o error.o  -L/usr/lib64 -lssl -lmysqlclient -lcrypto -lz -lpthread -lm
/usr/bin/ld: cannot find -lmysqlclient

but, all dependenses has been installed:
Cacti 1.1.9
Spine 1.1.8
CentOS 7
net-snmp 
mariadb-libs-5.5.52-1.el7.x86_64 is obsoleted by MariaDB-compat-10.2.6-1.el7.centos.x86_64 which is already installed 
MariaDB-common-10.2.6-1.el7.centos.x86_64
MariaDB-client-10.2.6-1.el7.centos.x86_64
MariaDB-shared-10.2.6-1.el7.centos.x86_64
MariaDB-server-10.2.6-1.el7.centos.x86_64
MariaDB-compat-10.2.6-1.el7.centos.x86_64
MariaDB-devel-10.2.6-1.el7.centos.x86_64 

- See more at: https://mariadb.com/resources/blog/mariadb-102-beta
Other useful enhancements
libmysqlclient has been removed from the server. It has been replaced by MariaDB’s own Connector/C.
INFORMATION_SCHEMA includes USER_VARIABLES which lists all user defined variables.
EXPLAIN FORMAT=JSON has been expanded to include the used sort_key in filesort and outer_ref_condition in SELECTs.
Analytical query performance improvement - If a derived table, view or CTE includes a GROUP BY clause it would be internally processed with temporary tables, which would then be materialized and used by the parent query. If the parent query has restrictions on the GROUP BY columns, this new optimization applies them early to exclude non-matching groups from materialization.

**Comment by max-sparker** [comment]
I also encountered such a problem. There were no ways to solve it?

**Comment by Izmenoff** [comment]
No, I'm waiting for new version Spine. But you can try install mariaDB 10.1. There is no problem 30.06.2017, 12:49, "Maxim Isaev" <notifications@github.com>:I also encountered such a problem. There were no ways to solve it?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by cigamit** [comment]
Just verified with MariaDB that this issue will be fixed in 10.2.7.  It's not a spine issue.

**Comment by misterguitar** [comment]
I'm running MariaDB 10.2.9 And I'm having the same problem with spine 1.1.24. Did MAriaDB fix this?

**Comment by Izmenoff** [comment]
yes it was fixed in 10.2.8
