### ISSUE TITLE
IPv6 devices are not properly parsed

### ISSUE THREAD

**Issue by choefing** [Cacti/spine#221]
**Describe the bug**
spine 1.2.18 breaks "Device Status" of ipv6 hosts. Therefore device down detection disables all polls. Devices are snmp and icmp reachable from host. Device overview on topleft of "host.php?action=edit&id=xxx" shows proper uptime and snmp info. Device down detection is set tp "snmp uptime". "snmp uptime OR ping" fails as well for either type of ping.

**To Reproduce**
1. Have a running Cacti 1.2.17 + Spine 1.2.17 with ipv6 hosts "[some::ip:v:6:add:ress:]" from https://www.cacti.net/info/downloads
2. Update Cacti and Spine to 1.2.18 from https://www.cacti.net/info/downloads
Uptime will break
3. Stop cactid
4. start with spine 1.2.17 again fixes it immediately even with cacti 1.2.18

**Expected behavior**
Having ipv6 devices not marked as down.

**Server (please complete the following information):**
 - OS: Debian Buster

**Comment by netniV** [comment]
Yes, we introduced a new function to attempt to breakdown addresses starting with TCP or UDP: but that appears to have broken those without the prefix.

```
test 127.0.0.1 = 127.0.0.1
test TCP:127.0.0.1 = 127.0.0.1
test ::1 = [
test 12:6A:33::10:1 = 6A
```

**Comment by netniV** [comment]
With the above commit, the output from my test was now

```
test 127.0.0.1 = 127.0.0.1
test TCP:127.0.0.1 = 127.0.0.1
test ::1 = [::1]
test 12:6A:33::10:1 = [12:6A:33::10:1]
```
