### ISSUE TITLE
`thread_mutex_trylock`: error: control reaches end of non-void function [-Werror=return-type]

### ISSUE THREAD

**Issue by andreasstieger** [Cacti/spine#227]
**Describe the bug**

1.2.18 build fails when treating on-void returns as errors.

```
[   94s] gcc -DHAVE_CONFIG_H -I. -I./config     -I/usr/include/net-snmp -I/usr/include/net-snmp/.. -I/usr/include/mysql -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -c -o locks.o locks.c
[   94s] locks.c: In function 'thread_mutex_trylock':
[   94s] locks.c:238:1: error: control reaches end of non-void function [-Werror=return-type]
[   94s]   238 | }
```

**To Reproduce**

Build with `-Werror=return-type`.

**Expected behavior**

The `int thread_mutex_trylock` function should actually return something.
See https://github.com/Cacti/spine/pull/223/files#diff-fde72ea96652c9cc626c72761023f4a5aefe6f49c5652ad9e026ad9d4a941775R264

(and the others)

**Screenshots**

N/A

**Server (please complete the following information):**
 - OS: openSUSE Tumbleweed
 - Version 2021-08-ish

**Compiling (please complete the following information):**

 - compiler: gcc 11
 - autoconf: 2.69
 - glibc: 2.33
 - source: all

**Additional context**

#223

**Comment by netniV** [comment]
Is this against the latest 1.2.x branch ?

**Comment by andreasstieger** [comment]
This is on cacti-spine 1.2.18, as in https://files.cacti.net/spine/cacti-spine-1.2.18.tar.gz
And per #223 also against the develop branch. 
And the issue appeared new in 1.2.18 (vs. 1.2.17).

**Comment by netniV** [comment]
Yes. Try the 1.2.x branch as that is where the latest patches are for 1.2.x.  We have spent some time addressing and testing the issues the updates to 1.2.18 introduced for spine.  Hopefully, all being well, that should fix things for you.

**Comment by andreasstieger** [comment]
Uhm... there was zero change in the file, and this is file-local error? So sure why you are asking for that.
Anyway, fails on 1.2.x branch as of 0dc0348104895b550ac0c4d8b1892e7b4c309473. Introduced by @netniV in 9e1f58838f886814d6aa74d3fee7cef7e0fe47d6.

**Comment by netniV** [comment]
Thanks for the commit @andreasstieger and you also highlighted to me that someone messed (in a bad way) with the CHANGELOG hence the confusion over version numbers.  I have now corrected that as well.
