### ISSUE TITLE
make Spine error /usr/bin/ld: cannot find -lmysqlclient

### ISSUE THREAD

**Issue by nguyenhappy92** [Cacti/spine#23]
I have useed Mariadb 10.2.7 and have installed yum install mariadb-devel
I have run command line for install Spine 1.1.13:
./configure them make error
/bin/sh ./libtool  --tag=CC   --mode=link gcc  -I/usr/include/mysql -g -O2  -L/usr/lib64 -lpthread -lssl -lm  -o spine sql.o spine.o util.o snmp.o locks.o poller.o nft_popen.o php.o ping.o keywords.o error.o  -lmysqlclient -lcrypto -lz -lpthread -lm 
libtool: link: gcc -I/usr/include/mysql -g -O2 -o spine sql.o spine.o util.o snmp.o locks.o poller.o nft_popen.o php.o ping.o keywords.o error.o  -L/usr/lib64 -lssl -lmysqlclient -lcrypto -lz -lpthread -lm
/usr/bin/ld: cannot find -lmysqlclient
collect2: error: ld returned 1 exit status
make: *** [spine] Error 1
Please help me?

**Comment by cigamit** [comment]
This is an issue with MariaDB 10.2.7.  We thought they were going to have it fixed in that release but apparantly not.  Easy fix, you just have to symlink the libmysqlclient*.so of your choice to libmysqlclient.so.  You can find that library in /usr/lib64/

**Comment by cihanakgun** [comment]
Is this fixed? I'm still getting errors with cacti spine 1.1.38

**Comment by netniV** [comment]
It's a development environment issue, not one that we will fix.  You have to ensure that the libraries are correctly linked as libmysqlclient.so.  CentOS, for example, does not bother to create a symlink to any of the libmysqlclient.so.?? libraries it does install when you install the -libs package.

**Comment by cigamit** [comment]
Please test the develop (1.2) version.  Though -lmysqlclient on most OS' works if the libraries and headers are in 'standard' locations.  Again, if you are runnning MariaDB 10.x, this is likely not a Cacti issue.

**Comment by tbilan** [comment]
In my Centos 7 install with Maria 10.3.13 the following commands worked.  Don't forget to rerun ./configure on spine after.

cd /usr/lib64
ln -s libmysqlclient.so.18.0.0 libmysqlclient.so

Spine then compiled successfully.
