### ISSUE TITLE
An improper locking due to the unreleased lock before program exit 

### ISSUE THREAD

**Issue by ycaibb** [Cacti/spine#231]
Hi developers, in the below codes, the lock` ListMutex` could be not released before program's `exit_exit(127);`. I think it is better to write `pthread_mutex_unlock(&ListMutex);` before `exit_exit(127);` for better resource management and code symmetry. Thanks!

```
int nft_popen(const char * command, const char * type) {
	...;
	pthread_mutex_lock(&ListMutex);

		for (p = PidList; p; p = p->next)
			(void)close(p->fd);

		/* Execute the command. */
		#if defined(__CYGWIN__)
		if (set.cygwinshloc == 0) {
			execve("sh.exe", argv, environ);
		}else{
			execve("/bin/sh", argv, environ);
		}
		#else
		execve("/bin/sh", argv, environ);
		#endif
		_exit(127); // add pthread_mutex_unlock(&ListMutex);
		/* NOTREACHED */
	}

	...;

	...;
	pthread_mutex_unlock(&ListMutex);
	pthread_setcancelstate(cancel_state, NULL);

	return fd;
}
```

https://github.com/Cacti/spine/blob/f80f20f53629384b14d20c697be668bd7491c934/nft_popen.c#L147-L228

**Comment by TheWitness** [comment]
Read this to understand why I'm closing this.

https://www.man7.org/linux/man-pages/man2/execve.2.html
