### ISSUE TITLE
MySQL 8.0 compatibility fix for spine - VALUES function

### ISSUE THREAD

**Issue by Kveri** [Cacti/spine#233]
**Describe the bug**
MySQL 8.0 marked SQL non-standard 'VALUES function' as deprecated and it will be removed in future release. This is now throwing warnings during execution of INSERT statements from Spine (specifically during inserting into poller_output table). Poller output suffix string which is added at the end of the INSERT SQL statement uses this VALUES function currently.

This is the warning thrown by MySQL Server 8.0:
![image](https://user-images.githubusercontent.com/3380181/133117214-99ba4e9e-5b41-4762-b816-ddf9aa336c5f.png)

Current code:

```
    snprintf(posuffix, BUFSIZE,
      " ON DUPLICATE KEY UPDATE output=VALUES(output)");
```

According to the standard the correct way to do this is to alias the output to "outx" and then refer to specific column using outx.<column> - in our case that is outx.output.

```
    snprintf(posuffix, BUFSIZE,
      " AS outx ON DUPLICATE KEY UPDATE output=outx.output");
```

I'll provide a patch within a day. It needs to be modified at line 337 and 413 of poller.c.

This applies to at least 1.2.18 and 1.2.17.

References:
https://dev.mysql.com/worklog/task/?id=13325
https://stackoverflow.com/questions/63609570/mysql-values-function-is-deprecated

**Comment by TheWitness** [comment]
I'll be damned.  This is good and bad.  I wonder if this will become SQL Standard.  PostgreSQL has something very close.  MERGE syntax in Oracle sucks.

**Comment by Kveri** [comment]
I just checked and it seems this is incompatible with MySQL 7 and lower, so we can't just easily change it because lower versions would stop working. Any suggestions? Ignore it for now since it's just a warning and leave it for the future? :-)

**Comment by TheWitness** [comment]
Yea, I know.  Oracle poisoning the well unfortunately.  The best thing would to create a configure option for duplicate key violation updates.  Not too complicated to do.

**Comment by TheWitness** [comment]
Another option would be to check the server version on startup.  That's easy too.

**Comment by netniV** [comment]
I was going to suggest the latter.  We already check for other things don't we? Or is that just in the core system?

**Comment by TheWitness** [comment]
@Kveri, can  you run the same command in your MySQL 8 environment?

```sh
MariaDB [(none)]> show global variables like '%version%';
+-----------------------------------+------------------------------------------+
| Variable_name                     | Value                                    |
+-----------------------------------+------------------------------------------+
| in_predicate_conversion_threshold | 1000                                     |
| innodb_version                    | 10.5.10                                  |
| protocol_version                  | 10                                       |
| slave_type_conversions            |                                          |
| system_versioning_alter_history   | ERROR                                    |
| system_versioning_asof            | DEFAULT                                  |
| tls_version                       | TLSv1.1,TLSv1.2,TLSv1.3                  |
| version                           | 10.5.10-MariaDB                          |
| version_comment                   | MariaDB Server                           |
| version_compile_machine           | x86_64                                   |
| version_compile_os                | Linux                                    |
| version_malloc_library            | system                                   |
| version_source_revision           | 3f55c569514679d98e09e71286ca28a8ac667a71 |
| version_ssl_library               | OpenSSL 1.1.1k  FIPS 25 Mar 2021         |
| wsrep_patch_version               | wsrep_26.22                              |
+-----------------------------------+------------------------------------------+
15 rows in set (0.001 sec)
```

**Comment by Kveri** [comment]
Sure, here you go

mysql> show global variables like '%version%';
+--------------------------+-------------------------------+
| Variable_name            | Value                         |
+--------------------------+-------------------------------+
| admin_tls_version        | TLSv1,TLSv1.1,TLSv1.2,TLSv1.3 |
| innodb_version           | 8.0.26                        |
| protocol_version         | 10                            |
| replica_type_conversions |                               |
| slave_type_conversions   |                               |
| tls_version              | TLSv1,TLSv1.1,TLSv1.2,TLSv1.3 |
| version                  | 8.0.26-0ubuntu0.20.04.2       |
| version_comment          | (Ubuntu)                      |
| version_compile_machine  | x86_64                        |
| version_compile_os       | Linux                         |
| version_compile_zlib     | 1.2.11                        |
+--------------------------+-------------------------------+
11 rows in set (0.00 sec)

**Comment by TheWitness** [comment]
You've got to love that.  But we can manage, MariaDB always puts `-MariaDB` in their version name.

**Comment by TheWitness** [comment]
This is fixed as much as I want it fixed for now.
