### ISSUE TITLE
Spine will not look at non-timetics uptime when sysUpTimeInstance overflows

### ISSUE THREAD

**Issue by arno-st** [Cacti/spine#237]
**Describe the bug**
When you have a device with a long uptime (for sur over than 250days), and if you use the Down device detection to be ping AND snmp Uptime, the status in set to down
It dosen't happen on ping or snmp uptime.

Cacti was fixed (big int on the DB for sysSnmpUptime).
It's not releated to the version of snmp (2 or 3), since I have both and the same happen.
When you open the device, I can see all the SNMP sysinformation, so the switch is reachable.

This happen on Cacti 1.2.18, but not on cacti 1.2.17.
Both where running on Centos 7 64 bit with php-SNMP.
The value of the snmpSysUptime on the DB is stored correctly:
cacti 1.2.17 4165077143
cacti 1.2.18 4192683188

Here is the output of a spine debug for one device who is up and running since 240d, and In State 368d. But that's what I have on Cacti 1.2.17, on 1.2.18 it's displayed Uptime N/A and In state 7d.

./spine -S -H 3160 --verbosity=5 --conf=../etc/spine.conf
SPINE: Using spine config file [../etc/spine.conf]
Total[0.0064] DEBUG: The path_php_server variable is /usr/share/cacti/script_server.php
Total[0.0065] DEBUG: The path_cactilog variable is /usr/share/cacti/log/cacti.log
Total[0.0065] DEBUG: The log_destination variable is 4 (STDOUT)
Total[0.0067] DEBUG: The path_php variable is /bin/php
Total[0.0069] DEBUG: The availability_method variable is 4
Total[0.0070] DEBUG: The ping_recovery_count variable is 6
Total[0.0071] DEBUG: The ping_failure_count variable is 4
Total[0.0072] DEBUG: The ping_method variable is 1
Total[0.0073] DEBUG: The ping_retries variable is 1
Total[0.0074] DEBUG: The ping_timeout variable is 400
Total[0.0074] DEBUG: The snmp_retries variable is 3
Total[0.0075] DEBUG: The log_perror variable is 1
Total[0.0076] DEBUG: The log_pwarn variable is 1
Total[0.0077] DEBUG: The boost_redirect variable is 1
Total[0.0078] DEBUG: The boost_rrd_update_enable variable is 0
Total[0.0079] DEBUG: The log_pstats variable is 1
Total[0.0080] DEBUG: The threads variable is 13
Total[0.0081] DEBUG: The polling interval is 60 seconds
Total[0.0082] DEBUG: The number of concurrent processes is 2
Total[0.0083] DEBUG: The script timeout is 25
Total[0.0084] DEBUG: The selective_device_debug variable is 3160,3159
Total[0.0085] DEBUG: The spine_log_level variable is 0
Total[0.0086] DEBUG: The number of php script servers to run is 5
Total[0.0087] DEBUG: Device List to be polled='3160', TotalPHPScripts='1'
Total[0.0087] DEBUG: The PHP Script Server is Required
Total[0.0088] DEBUG: The Maximum SNMP OID Get Size is 10
Total[0.0088] DEBUG: Selective Debug Devices 3160,3159
Total[0.0090] DEBUG: Total Connections made 1
Total[0.0090] DEBUG: Creating Local Connection Pool of 13 threads.
Total[0.0090] DEBUG: Creating Local Connection 0.
Total[0.0092] DEBUG: Total Connections made 2
Total[0.0096] DEBUG: Creating Local Connection 1.
Total[0.0098] DEBUG: Total Connections made 3
Total[0.0101] DEBUG: Creating Local Connection 2.
Total[0.0103] DEBUG: Total Connections made 4
Total[0.0107] DEBUG: Creating Local Connection 3.
Total[0.0109] DEBUG: Total Connections made 5
Total[0.0113] DEBUG: Creating Local Connection 4.
Total[0.0115] DEBUG: Total Connections made 6
Total[0.0119] DEBUG: Creating Local Connection 5.
Total[0.0120] DEBUG: Total Connections made 7
Total[0.0124] DEBUG: Creating Local Connection 6.
Total[0.0126] DEBUG: Total Connections made 8
Total[0.0130] DEBUG: Creating Local Connection 7.
Total[0.0132] DEBUG: Total Connections made 9
Total[0.0136] DEBUG: Creating Local Connection 8.
Total[0.0138] DEBUG: Total Connections made 10
Total[0.0142] DEBUG: Creating Local Connection 9.
Total[0.0143] DEBUG: Total Connections made 11
Total[0.0147] DEBUG: Creating Local Connection 10.
Total[0.0149] DEBUG: Total Connections made 12
Total[0.0153] DEBUG: Creating Local Connection 11.
Total[0.0155] DEBUG: Total Connections made 13
Total[0.0159] DEBUG: Creating Local Connection 12.
Total[0.0161] DEBUG: Total Connections made 14
Total[0.0166] DEBUG: Version 1.2.18 starting
Total[0.0166] DEBUG: MySQL is Thread Safe!
Total[0.0166] DEBUG: Spine running as 0 UID, 0 EUID
Total[0.0167] DEBUG: Spine is running as root.
Total[0.0167] DEBUG: Spine has got ICMP
Total[0.0167] DEBUG: Initializing Net-SNMP API
Total[0.0167] DEBUG: Issues with SNMP Header Version information, assuming old version of Net-SNMP.
Total[0.0180] DEBUG: Initializing PHP Script Server(s)
Total[0.0180] DEBUG: SS[0] PHP Script Server Routine Starting
Total[0.0180] DEBUG: SS[0] PHP Script Server About to FORK Child Process
Total[0.0185] DEBUG: SS[0] PHP Script Server Child FORK Success
Total[0.1668] DEBUG: SS[0] Confirmed PHP Script Server running using readfd[20], writefd[19]
Total[0.1668] DEBUG: SS[1] PHP Script Server Routine Starting
Total[0.1668] DEBUG: SS[1] PHP Script Server About to FORK Child Process
Total[0.1670] DEBUG: SS[1] PHP Script Server Child FORK Success
Total[0.3097] DEBUG: SS[1] Confirmed PHP Script Server running using readfd[22], writefd[21]
Total[0.3097] DEBUG: SS[2] PHP Script Server Routine Starting
Total[0.3097] DEBUG: SS[2] PHP Script Server About to FORK Child Process
Total[0.3099] DEBUG: SS[2] PHP Script Server Child FORK Success
Total[0.4525] DEBUG: SS[2] Confirmed PHP Script Server running using readfd[24], writefd[23]
Total[0.4525] DEBUG: SS[3] PHP Script Server Routine Starting
Total[0.4525] DEBUG: SS[3] PHP Script Server About to FORK Child Process
Total[0.4527] DEBUG: SS[3] PHP Script Server Child FORK Success
Total[0.6048] DEBUG: SS[3] Confirmed PHP Script Server running using readfd[26], writefd[25]
Total[0.6048] DEBUG: SS[4] PHP Script Server Routine Starting
Total[0.6049] DEBUG: SS[4] PHP Script Server About to FORK Child Process
Total[0.6050] DEBUG: SS[4] PHP Script Server Child FORK Success
Total[0.7482] DEBUG: SS[4] Confirmed PHP Script Server running using readfd[28], writefd[27]
Total[0.7492] Spine will support multithread device polling.
Total[0.7497] DEBUG: Initial Value of Available Threads is 13 (0 outstanding)
Total[0.7499] DEBUG: Valid Thread to be Created
Total[0.7500] DEBUG: Available Threads is 12 (1 outstanding)
Total[0.7500] DEBUG: In Poller, About to Start Polling of Device for Device ID 0
Total[0.7500] DEBUG: Traversing Local Connection Pool for free connection.
Total[0.7500] DEBUG: Checking Local Pool ID 0.
Total[0.7500] DEBUG: Allocating Local Pool ID 0.
Total[0.7502] DEBUG: Valid Thread to be Created
Total[0.7502] DEBUG: Available Threads is 11 (2 outstanding)
Total[0.7502] WARNING: Spine Sleeping While Waiting for 2 Threads to End
Total[0.7502] DEBUG: In Poller, About to Start Polling of Device for Device ID 3160
Total[0.7503] Device[0] HT[1] Updating Poller Items for Next Poll
Total[0.7503] DEBUG: Traversing Local Connection Pool for free connection.
Total[0.7503] DEBUG: Checking Local Pool ID 0.
Total[0.7503] DEBUG: Checking Local Pool ID 1.
Total[0.7503] DEBUG: Allocating Local Pool ID 1.
Total[0.7506] Device[0] HT[1] Total Time: 0.00064 Seconds
Total[0.7508] get_namebyhost(10.1.128.10) - Allocating name_t
Total[0.7508] get_namebyhost(10.1.128.10) - Token #1
Total[0.7508] get_hostbyname(10.1.128.10) - No matching method for 11 chars: 10.1.128.10
Total[0.7508] get_namebyhost(10.1.128.10) - Setting hostname: 10.1.128.10
Total[0.7508] DEBUG: Freeing Local Pool ID 0
Total[0.7508] DEBUG: Device[0] HT[1] DEBUG: HOST COMPLETE: About to Exit Device Polling Thread Function
Total[0.7509] Device[3160] INFO: SNMP Device '10.1.128.10' has timeout 500000 (500), retries 3
Total[0.7770] Device[3160] IPv4 address 10.1.128.10 (10.1.128.10)

Total[0.7770] Device[3160] DEBUG: Entering ICMP Ping
Total[0.7771] WARNING: Spine Sleeping While Waiting for 1 Threads to End
Total[0.7778] WARNING: Spine Sleeping While Waiting for 1 Threads to End
Total[0.7778] WARNING: Spine Sleeping While Waiting for 1 Threads to End
Total[0.7778] WARNING: Spine Sleeping While Waiting for 1 Threads to End
Total[0.7779] Device[3160] DEBUG: Entering SNMP Ping
Total[0.7823] Device[3160] PING Result: ICMP: Destination address not specified
Total[0.7823] Device[3160] SNMP Result: Device responded to SNMP

Total[0.7851] Device[3160] HT[1] NOTE: There are '350' Polling Items for this Device
Total[0.7852] DEBUG: Setting up writes to local database
Total[0.7854] Device[3160] HT[1] Updating Poller Items for Next Poll
Total[0.7865] Device[3160] HT[1] Total Time: 0.036 Seconds
Total[0.7867] DEBUG: Freeing Local Pool ID 1
Total[0.7867] DEBUG: Device[3160] HT[1] DEBUG: HOST COMPLETE: About to Exit Device Polling Thread Function
Total[1.2779] The Final Value of Threads is 0
Total[1.2786] DEBUG: Closing Local Connection Pool ID 0
Total[1.2786] DEBUG: Closing Local Connection Pool ID 1
Total[1.2787] DEBUG: Closing Local Connection Pool ID 2
Total[1.2787] DEBUG: Closing Local Connection Pool ID 3
Total[1.2787] DEBUG: Closing Local Connection Pool ID 4
Total[1.2787] DEBUG: Closing Local Connection Pool ID 5
Total[1.2787] DEBUG: Closing Local Connection Pool ID 6
Total[1.2787] DEBUG: Closing Local Connection Pool ID 7
Total[1.2787] DEBUG: Closing Local Connection Pool ID 8
Total[1.2787] DEBUG: Closing Local Connection Pool ID 9
Total[1.2788] DEBUG: Closing Local Connection Pool ID 10
Total[1.2788] DEBUG: Closing Local Connection Pool ID 11
Total[1.2788] DEBUG: Closing Local Connection Pool ID 12
Total[1.2788] DEBUG: Thread Cleanup Complete
Total[1.2788] DEBUG: SS[0] Script Server Shutdown Started
Total[1.3289] DEBUG: SS[1] Script Server Shutdown Started
Total[1.3790] DEBUG: SS[2] Script Server Shutdown Started
Total[1.4291] DEBUG: SS[3] Script Server Shutdown Started
Total[1.4793] DEBUG: SS[4] Script Server Shutdown Started
Total[1.5294] DEBUG: PHP Script Server Pipes Closed
Total[1.5294] DEBUG: Allocated Variable Memory Freed
Total[1.5294] DEBUG: MYSQL Free & Close Completed
Total[1.5295] DEBUG: Net-SNMP Close Completed
Total[1.5295] Time: 1.2779 s, Threads: 13, Devices: 2

The cacti bug releated is closed and number 4428

I'm looking into Spine (actually poller.c), but didn't find yet anything, I keep looking.

**Comment by TheWitness** [comment]
If that works, we might have a solution.
