### ISSUE TITLE
Failed build against MariaDB 10.6.4

### ISSUE THREAD

**Issue by dsclassen** [Cacti/spine#239]
**Describe the bug**
make produces an error:

```
 make
gcc -DHAVE_CONFIG_H -I. -I./config     -I/usr/include/net-snmp -I/usr/include/net-snmp/.. -I/usr/include/mysql -g -O2 -MT sql.o -MD -MP -MF .deps/sql.Tpo -c -o sql.o sql.c
In file included from spine.h:602:0,
                 from sql.c:35:
locks.h:39:77: error: expected ‘;’, ‘,’ or ‘)’ before ‘abstime’
 extern int thread_cond_timedwait(int mutex, const struct timespec *restrict abstime);
                                                                             ^
```

**To Reproduce**
1. install MariaDB 10.6.4 from community repo
2. attempt to build spine.
```
cd /usr/local/src
git clone https://github.com/Cacti/spine.git
cd spine/
sh bootstrap 
./configure
make
```

**Expected behavior**
I was hoping it would complete and produce a binary 

**Server (please complete the following information):**
 - OS: CentOS7
 - Version: CentOS Linux release 7.9.2009 (Core)

**Compiling (please complete the following information):**

 - compiler: 4.8.5
 - autoconf: 2.6.9
 - glibc: 2.17
 - source: GitHub

**Comment by netniV** [comment]
This is an old issue that has already been resolved. Ensure you have the latest sources from the 1.2.x branch.

**Comment by dsclassen** [comment]
Aha... I had forgotten that I should be on the 1.2.x branch. That fixed it. Thanks.

**Comment by netniV** [comment]
Will get around to merging the latest changes into develop
