### ISSUE TITLE
FreeBSD13 compilation fail

### ISSUE THREAD

**Issue by donatid** [Cacti/spine#243]
Can't compile spine 1.2.19 in FreeBSD 13-RELEASE

**To Reproduce**
1. wget https://github.com/Cacti/spine/archive/release/1.2.19.tar.gz
2. tar -zxvf 1.2.19.tar.gz
3. cd spine-release-1.2.19
4. ./bootstrap 
5. ./configure --prefix=/usr/local/spine1219
6. make

**Expected results**
make should be complete without error

**Actual results**
```
/bin/sh ./libtool  --tag=CC    --mode=link gcc  -I/usr/local/include/net-snmp -I/usr/local/include/net-snmp/.. -I/usr/local/include/mysql -g -O2   -L/usr/local/lib -L/usr/local/lib/mysql -o spine sql.o spine.o util.o  snmp.o locks.o poller.o  nft_popen.o php.o ping.o  keywords.o error.o  -lnetsnmp -lmysqlclient_r -lm -ldl -lmysqlclient -lm -ldl -lcrypto -lz -lpthread -ldl -lm -lpthread -lssl
libtool: link: gcc -I/usr/local/include/net-snmp -I/usr/local/include/net-snmp/.. -I/usr/local/include/mysql -g -O2 -o spine sql.o spine.o util.o snmp.o locks.o poller.o nft_popen.o php.o ping.o keywords.o error.o  -L/usr/local/lib -L/usr/local/lib/mysql -lnetsnmp -lmysqlclient_r -lmysqlclient -lcrypto -lz -ldl -lm -lpthread -lssl
/usr/local/bin/ld: error.o: in function `spine_signal_handler':
/root/spine-release-1.2.19/error.c:68: undefined reference to `backtrace'
/usr/local/bin/ld: /root/spine-release-1.2.19/error.c:69: undefined reference to `backtrace_symbols'
collect2: error: ld returned 1 exit status
*** Error code 1

Stop.
make: stopped in /root/spine-release-1.2.19
```

**Server (please complete the following information):**
 - OS: FreeBSD 
 - Version 13-RELEASE 64bit

**Compiling (please complete the following information):**

 - compiler:  gcc version 10.3.0 (FreeBSD Ports Collection) 
 - autoconf: autoconf 2.69
 - glibc: 
 - source: v1.2.19

It's also happened since version 1.2.16 in the same OS version.

Thank you

**Comment by netniV** [comment]
Try this patch:

```diff
diff --git a/error.h b/error.h
index 33c5e27..824f9cb 100644
--- a/error.h
+++ b/error.h
@@ -33,5 +33,7 @@

 extern void install_spine_signal_handler(void);
 extern void uninstall_spine_signal_handler(void);
+#ifdef HAVE_EXECINFO_H
 extern char ** backtrace_symbols();
 extern int backtrace();
+#endif
```

**Comment by netniV** [comment]
Hmm, that suggests that HAVE_EXECINOF_H is returned true but on FreeBSD having that doesn't give you backtrace_symbols which from when I did a quick google that it's in a separate library and even stores it's return values slightly differently.

**Comment by netniV** [comment]
Can you make sure that you have the libexecinfo library installed?

**Comment by donatid** [comment]
Hi @netniV

I'm afraid that the libexecinfo is unavailable and has been removed since 2017.
I'm just curious why the problem isn't exists in version 1.2.15 in the same OS version.

Thank you,

**Comment by netniV** [comment]
Backtrace was probably only recently introduced if you look through the source history.

**Comment by donatid** [comment]
I  was able to install spine 1.2.19 in FreeBSD13 after removing all backtraces in error.h and error.c, or simply use file error.h and error.c from version 1.2.15.

Thanks

**Comment by netniV** [comment]
From what i've read, I think you have to use ports to get the backtrace working again on FreeBSD.  Annoying, given it's useful to have trace information at times when things go wrong.  Probably need a way in the configure.ac to identify that missing requirement on FreeBSD but i'm a little under the weather right now and not sure how to do it, so it'll have to wait unless you can create a PR for it?  We would want to keep it for all other systems though.

**Comment by TheWitness** [comment]
We can IFDEF around it too.

**Comment by TheWitness** [comment]
Should be resolved now.

**Comment by thomasbuesser** [comment]
still open in 1.2.22

**Comment by TheWitness** [comment]
Can you fix it and create a pull request?

**Comment by thomasbuesser** [comment]
in which branch (master, 1.2.x or develop)? 

*** spine-release-1.2.20/error.c        Tue Apr  5 02:47:51 2022
--- spine-release-1.2.20_mod/error.c    Mon Nov 21 15:32:50 2022
***************
*** 57,85 ****
                        break;
                case SIGSEGV:
                        fprintf(stderr, "FATAL: Spine Encountered a Segmentation Fault\n");
- 
-                       #ifdef HAVE_EXECINFO_H
-                       int row = 0;
-                       char **exit_strings = NULL;
- 
-                       fprintf(stderr, "Generating backtrace...%ld line(s)...\n", set.exit_size);
- 
-                       if (set.exit_size) {
-                               set.exit_size = backtrace(set.exit_stack, set.exit_size);
-                               exit_strings  = backtrace_symbols(set.exit_stack, set.exit_size);
- 
-                               if (exit_strings) {
-                                       for (row = 0; row < set.exit_size; row++) {
-                                               fprintf(stderr, "%3d: %s\n", row, exit_strings[row]);
-                                       }
- 
-                                       free(exit_strings);
-                               }
-                       }
-                       #endif
- 
                case SIGBUS:
                        fprintf(stderr, "FATAL: Spine Encountered a Bus Error\n");

**Comment by netniV** [comment]
I would not want to remove the code entirely. That is the reason for the #ifdef on EXECINFO_H so that it can be used on systems that support it
