### ISSUE TITLE
[1.2.19]  SQL sytax error for remote pollers 

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/spine#244]
Hey Guys 

After pulling down the latest changes on 1.2.x  on remote pollers the log is flooded with 

``shell
2021-12-01 16:36:08 - SPINE: Poller[New Poller] PID[10547] PT[140627475388544] ERROR: SQL Failed! Error:'1064', Message:'You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'team (2289,
``  Along with the other data from the poll cycle to be inserted  the errors come After each poll cycle

I have not updated Spine so its something on the Cacti end 
I disabled all devices on the poller and yet the errors are still being logged 

I am working to trace where this syntax could be as I am not sure what the team keyword would be from

**Comment by TheWitness** [comment]
This might have been a dup for #241.  I did a small commit to increase the buffer in any case.  Try the new spine.

**Comment by TheWitness** [comment]
@bmfmancini tested yet?

**Comment by bmfmancini** [comment]
Testing now looks good so far!

**Comment by seanmancini** [comment]
30 Mins in no more errors I think we are safe to say this is resolved !
