### ISSUE TITLE
SNMPv3 with SHA256 throws "SHA256 is not supported on this system. Upgrade the Net-SNMP API to 5.8+"

### ISSUE THREAD

**Issue by j66h** [Cacti/spine#247]
**Describe the bug**
Changed a host from "SNMPv3, SHA, AES128" to "SNMPv3, SHA256, AES128". 
Reason: SHA is dropped from recent Versions of Cisco IOSXE and Checkpoint Cluster XL.

Not sure, if this is caused by my installation/OS or if it is a bug. Please give me information, how I can analyze this further.

**To Reproduce**
1. Edit host settings
2. change to SNMPv3 with SHA256
3. look into cacti.log
4. Error "2022.01.17 15:20:28 - SPINE: Poller[Main Poller] PID[2549121] PT[139752486971136] SNMP: Error SHA256 is not supported on this system. Upgrade the Net-SNMP API to 5.8+" appears

Or: run spine or host with SNMPv3 and SHA256:
 ./spine -R -V 5 -H 882
SPINE: Using spine config file [/etc/spine.conf]
...
2022.01.17 15:25:21 - SPINE: Poller[1] PID[2556407] PT[140069274136960] DEBUG: Initializing Net-SNMP API
2022.01.17 15:25:21 - SPINE: Poller[1] PID[2556407] PT[140069274136960] DEBUG: Issues with SNMP Header Version information, assuming old version of Net-SNMP.
...
2022.01.17 15:25:22 - SPINE: Poller[1] PID[2556407] PT[140069262612224] SNMP: Error SHA256 is not supported on this system.  Upgrade the Net-SNMP API to 5.8+

**Expected behavior**
Working SNMPv3 with higher encryption algorithms.

**Screenshots**
![image](https://user-images.githubusercontent.com/54892435/149788045-c42503cc-2bce-480b-8837-9f218720bb31.png)

**Server (please complete the following information):**
 - OS: Debian Bullseye
 - Version 11
 - net-snmp Version 5.9 installed

**Compiling (please complete the following information):**
 - compiler: gcc version 10.2.1 20210110 (Debian 10.2.1-6)
 - autoconf: autoconf (GNU Autoconf) 2.69
 - glibc: Debian GLIBC 2.31-13+deb11u2
 - source: cacti 1.2.20 downloaded from github at 01/04/2022, spine 1.2.20 downloaded from github at 01/11/2022

**Additional context**
php-snmp is not installed:
![image](https://user-images.githubusercontent.com/54892435/149788990-12efa526-1e30-40cf-be90-4e533ff1d7c2.png)

**Comment by j66h** [comment]
Forgot to mention: Device status information is shown on device status page, allthough set to SHA256
![image](https://user-images.githubusercontent.com/54892435/149791361-63d27d07-0f5c-40b9-862b-b02bac3384e1.png)

Screenshot of netsnmp:
![image](https://user-images.githubusercontent.com/54892435/149791703-a8dc0570-26db-4424-a8ba-7a44d51f75ba.png)

**Comment by TheWitness** [comment]
You need to goto the Linux distro and check what they are using for build options.  The message is pretty strait forward.  You may have to download net-snmp separately and build it yourself. Either way, the Linux vendor should be notified.

**Comment by TheWitness** [comment]
It does strike me as odd that the cli works though.  Maybe they changed something in the 5.9 release.

**Comment by TheWitness** [comment]
Maybe no longer "DRAFT".  See the below lines.

![image](https://user-images.githubusercontent.com/1439914/149812508-f36585d4-2838-4486-96d8-b229379eaa0d.png)

**Comment by TheWitness** [comment]
Edit snmp.c and remove the items with the red line in them and recompile.  See if it works then...

![image](https://user-images.githubusercontent.com/1439914/149813260-212b6898-4f16-4ef8-8868-91660e573268.png)

**Comment by j66h** [comment]
I'm still on AES128, but trying to use SHA256. ;-)
But I took your suggestion and did the same for SHA256. BTW, are that typos/copy&paste errors, what I marked red?
![image](https://user-images.githubusercontent.com/54892435/149888338-bf86b21f-2fc0-4f3f-8932-8c7b1a203b70.png)

Error which says to upgrade Net-SNMP API is gone now. But I'm running into timeouts for all values now. I'll try to find out, whats going on.

**Comment by j66h** [comment]
Hmmhh. Deleted and recreated device. Ok now. no timeouts anymore. But I think, that is a different issue. I'll look for it and create a different case, if needed...

Regarding the SNMPv3 and higher encryption levels problem: Is removal of these conditions the final solution?

If so:
Will it help, if I test other combinations? I can do SHA256|SHA512 and combine it with AES256. That is, what Checkpoint offers.
With some more effort, I can test with a cisco router. I think these provide more options...

**Comment by j66h** [comment]
Found the issue with timeouts. Poller cache was not updated for network interfaces while changing from SNMPv2 to SNMPv3.
After recreating whole device or just interfaces it wokred again. Below I recreated eth1 up to eth4 and left eth5 to eth8 as they where with timeout errors.
![image](https://user-images.githubusercontent.com/54892435/150111214-bc2d6557-ffcb-4e04-8d4e-6ce59c3d077e.png)
I changed to SNMP Version 3 manually by updating entries in table poller_item. Everythign started to work. But after hitting "Repopulate Poller Cache" on device edit page interfaces where set back to SNMPv2.
I have that problem with 4 new Checkpojnt firewalls. I tried to create this situation with several other devices and changed SNMP Version back and forth several times. I was not able to create that error situation for other devices.
So I would leave this for now. If this comes back, I'll create an issue in cacti repository.

So what's left:
Your suggested code changes solved the problem for the combination of SHA256 with AES128. Sadly I'm unable to test different combinations. I have no idea how to go on with that "Error generating SNMPv3 Ku" message.
Only the for me more cosmetic issue at spine startup is left.

So for me verything works now. Thanks a lot for your fast help and all your valuable work.
If I still can assist and test things for this issue, please aks.
Sadly I'm unable to work with git and provide a changed snmp.c in thre right way. :-(

**Comment by TheWitness** [comment]
How did you change the snmp settings?  Was it done through the GUI or did you make the changes in a different way?  Did you also provide your pho version?

**Comment by j66h** [comment]
PHP Version is 7.4.25.
I did the changes to the SNMP settings in WebUI.

**Comment by j66h** [comment]
played arround a bit with settings. changed cacti to snmpv2 while firewall only allows v3. changed fw also to v2. changed cacti back to v3 with AES256, which can not work because my net-snmp doesn't support it. changed back to SHA in cacti with FW still on SNMPv2. Changed fw to SNMPv3 with SHA256 since it doesn't support SHA. Changed Cacti to SHA256 again.
I allowed spine everytime to run a few poller cycles.
Timeout Errors / corrupted poller cache did not come back.
I did not change snmp.c back to original. That would hit more than one device...

**Comment by TheWitness** [comment]
Are you running the 1.2.x branch of a release?

**Comment by j66h** [comment]
Cacti on 4th of January: git clone -b 1.2.x  https://github.com/Cacti/cacti.git
Spine on 11th of January: git clone -b 1.2.x  https://github.com/Cacti/spine.git

**Comment by TheWitness** [comment]
Okay, I have gotten the time today since I'm off on medical to track this down.  I can confirm that it's working now.  Just pull the latest 1.2.x branch of spine and remake.
