### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by surichard** [Cacti/spine#25]
CentOS 7.3 
mariadb-server 10.2.7
Package MariaDB-client-10.2.7-1.el7.centos.x86_64 already installed and latest version

spine 1.1.6

[root@localhost ~]# cd spine
[root@localhost spine]# ls -lh
total 976K
-rw-rw-r--. 1 1000 1000  43K Jul 30 10:00 aclocal.m4
drwxr-xr-x. 2 1000 1000  118 Jul 30 10:00 autom4te.cache
-rwxrwxr-x. 1 1000 1000 2.6K Jul 30 10:00 bootstrap
-rw-rw-r--. 1 1000 1000  19K Jul 30 10:00 ChangeLog
-rw-rw-r--. 1 1000 1000 4.3K Jul 30 10:00 common.h
drwxr-xr-x. 2 1000 1000  143 Jul 30 10:00 config
-rwxrwxr-x. 1 1000 1000 459K Jul 30 10:00 configure
-rw-rw-r--. 1 1000 1000  12K Jul 30 10:00 configure.ac
-rw-rw-r--. 1 1000 1000 4.9K Jul 30 10:00 error.c
-rw-rw-r--. 1 1000 1000 2.4K Jul 30 10:00 error.h
-rw-rw-r--. 1 1000 1000  16K Jul 30 10:00 INSTALL
-rw-rw-r--. 1 1000 1000 6.9K Jul 30 10:00 keywords.c
-rw-rw-r--. 1 1000 1000 2.6K Jul 30 10:00 keywords.h
-rw-rw-r--. 1 1000 1000  26K Jul 30 10:00 LICENSE
-rw-rw-r--. 1 1000 1000 6.9K Jul 30 10:00 locks.c
-rw-rw-r--. 1 1000 1000 2.5K Jul 30 10:00 locks.h
drwxrwxr-x. 2 1000 1000  104 Jul 30 10:00 m4
-rw-rw-r--. 1 1000 1000  438 Jul 30 10:00 Makefile.am
-rw-rw-r--. 1 1000 1000  31K Jul 30 10:01 Makefile.in
-rw-rw-r--. 1 1000 1000  11K Jul 30 10:00 nft_popen.c
-rw-rw-r--. 1 1000 1000 2.5K Jul 30 10:00 nft_popen.h
-rw-rw-r--. 1 1000 1000  17K Jul 30 10:00 php.c
-rw-rw-r--. 1 1000 1000 2.5K Jul 30 10:00 php.h
-rw-rw-r--. 1 1000 1000  40K Jul 30 10:00 ping.c
-rw-rw-r--. 1 1000 1000 5.3K Jul 30 10:00 ping.h
-rw-rw-r--. 1 1000 1000  79K Jul 30 10:00 poller.c
-rw-rw-r--. 1 1000 1000 2.7K Jul 30 10:00 poller.h
-rw-rw-r--. 1 1000 1000 4.0K Jul 30 10:00 README.md
-rw-rw-r--. 1 1000 1000  24K Jul 30 10:00 snmp.c
-rw-rw-r--. 1 1000 1000 3.1K Jul 30 10:00 snmp.h
-rw-rw-r--. 1 1000 1000  28K Jul 30 10:00 spine.c
-rw-rw-r--. 1 1000 1000 3.3K Jul 30 10:00 spine.conf.dist
-rw-rw-r--. 1 1000 1000  16K Jul 30 10:00 spine.h
-rw-rw-r--. 1 1000 1000  12K Jul 30 10:00 sql.c
-rw-rw-r--. 1 1000 1000 2.7K Jul 30 10:00 sql.h
-rw-rw-r--. 1 1000 1000  37K Jul 30 10:00 util.c
-rw-rw-r--. 1 1000 1000 4.0K Jul 30 10:00 util.h
[root@localhost spine]# sh bootstrap
INFO: Starting Spine build process
INFO: Removing cache directories
INFO: Running auto-tools to verify buildability
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `config'.
libtoolize: copying file `config/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
libtoolize: Consider adding `-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
INFO: Spine bootstrap process completed

  These instructions assume the default install location for spine
  of /usr/local/spine.  If you choose to use another prefix, make
  sure you update the commands as required for that new path.

  To compile and install Spine using MySQL versions 5.5 or higher
  please do the following:

  ./configure
  make
  make install
  chown root:root /usr/local/spine/bin/spine
  chmod +s /usr/local/spine/bin/spine

  To compile and install Spine using MySQL versions previous to 5.5
  please do the following:

  ./configure --with-reentrant
  make
  make install
  chown root:root /usr/local/spine/bin/spine
  chmod +s /usr/local/spine/bin/spine

[root@localhost spine]# ./configure
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gawk... (cached) gawk
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking whether ln -s works... yes
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking whether to enable -Wall... no
checking for help2man... /usr/bin/help2man
checking for help2man... /usr/bin/help2man
checking for threadsafe gethostbyname()... no
checking for gethostbyname_r in -lnls... no
checking for socket in -lsocket... no
checking for floor in -lm... yes
checking for pthread_exit in -lpthread... yes
checking for deflate in -lz... yes
checking for kstat_close in -lkstat... no
checking for CRYPTO_realloc in -lcrypto... yes
checking for ANSI C header files... (cached) yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/select.h usability... yes
checking sys/select.h presence... yes
checking for sys/select.h... yes
checking sys/wait.h usability... yes
checking sys/wait.h presence... yes
checking for sys/wait.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking assert.h usability... yes
checking assert.h presence... yes
checking for assert.h... yes
checking ctype.h usability... yes
checking ctype.h presence... yes
checking for ctype.h... yes
checking errno.h usability... yes
checking errno.h presence... yes
checking for errno.h... yes
checking signal.h usability... yes
checking signal.h presence... yes
checking for signal.h... yes
checking math.h usability... yes
checking math.h presence... yes
checking for math.h... yes
checking malloc.h usability... yes
checking malloc.h presence... yes
checking for malloc.h... yes
checking netdb.h usability... yes
checking netdb.h presence... yes
checking for netdb.h... yes
checking for signal.h... (cached) yes
checking stdarg.h usability... yes
checking stdarg.h presence... yes
checking for stdarg.h... yes
checking stdio.h usability... yes
checking stdio.h presence... yes
checking for stdio.h... yes
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking for netinet/in_systm.h... yes
checking for netinet/in.h... yes
checking for netinet/ip.h... yes
checking for netinet/ip_icmp.h... yes
checking for unsigned long long... yes
checking for long long... yes
checking for an ANSI C-conforming const... yes
checking for size_t... yes
checking whether time.h and sys/time.h may both be included... yes
checking whether struct tm is in sys/time.h or time.h... time.h
checking return type of signal handlers... void
checking for malloc... yes
checking for calloc... yes
checking for gettimeofday... yes
checking for strerror... yes
checking for strtoll... yes
checking priv.h usability... no
checking priv.h presence... no
checking for priv.h... no
checking whether we are using Solaris privileges... no
checking sys/capability.h usability... no
checking sys/capability.h presence... no
checking for sys/capability.h... no
checking whether we are using Linux Capabilities... no
checking if Net-SNMP needs crypto support... no
checking for snmp_timeout in -lnetsnmp... no
checking for the spine results buffer size... 1024 bytes
checking for the maximum simultaneous spine scripts... 20
checking for the maximum MySQL buffer size... 65536
checking whether we are using traditional popen... no
checking whether to verify net-snmp library vs header versions... no
checking for glibc gethostbyname_r... no
checking for Solaris/Irix gethostbyname_r... no
checking for HP-UX gethostbyname_r... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config/config.h
config.status: executing depfiles commands
config.status: executing libtool commands
[root@localhost spine]# make
gcc -DHAVE_CONFIG_H -I. -I./config     -I/usr/include/mysql -g -O2 -MT sql.o -MD -MP -MF .deps/sql.Tpo -c -o sql.o sql.c
mv -f .deps/sql.Tpo .deps/sql.Po
gcc -DHAVE_CONFIG_H -I. -I./config     -I/usr/include/mysql -g -O2 -MT spine.o -MD -MP -MF .deps/spine.Tpo -c -o spine.o spine.c
mv -f .deps/spine.Tpo .deps/spine.Po
gcc -DHAVE_CONFIG_H -I. -I./config     -I/usr/include/mysql -g -O2 -MT util.o -MD -MP -MF .deps/util.Tpo -c -o util.o util.c
mv -f .deps/util.Tpo .deps/util.Po
gcc -DHAVE_CONFIG_H -I. -I./config     -I/usr/include/mysql -g -O2 -MT snmp.o -MD -MP -MF .deps/snmp.Tpo -c -o snmp.o snmp.c
mv -f .deps/snmp.Tpo .deps/snmp.Po
gcc -DHAVE_CONFIG_H -I. -I./config     -I/usr/include/mysql -g -O2 -MT locks.o -MD -MP -MF .deps/locks.Tpo -c -o locks.o locks.c
mv -f .deps/locks.Tpo .deps/locks.Po
gcc -DHAVE_CONFIG_H -I. -I./config     -I/usr/include/mysql -g -O2 -MT poller.o -MD -MP -MF .deps/poller.Tpo -c -o poller.o poller.c
mv -f .deps/poller.Tpo .deps/poller.Po
gcc -DHAVE_CONFIG_H -I. -I./config     -I/usr/include/mysql -g -O2 -MT nft_popen.o -MD -MP -MF .deps/nft_popen.Tpo -c -o nft_popen.o nft_popen.c
mv -f .deps/nft_popen.Tpo .deps/nft_popen.Po
gcc -DHAVE_CONFIG_H -I. -I./config     -I/usr/include/mysql -g -O2 -MT php.o -MD -MP -MF .deps/php.Tpo -c -o php.o php.c
mv -f .deps/php.Tpo .deps/php.Po
gcc -DHAVE_CONFIG_H -I. -I./config     -I/usr/include/mysql -g -O2 -MT ping.o -MD -MP -MF .deps/ping.Tpo -c -o ping.o ping.c
mv -f .deps/ping.Tpo .deps/ping.Po
gcc -DHAVE_CONFIG_H -I. -I./config     -I/usr/include/mysql -g -O2 -MT keywords.o -MD -MP -MF .deps/keywords.Tpo -c -o keywords.o keywords.c
mv -f .deps/keywords.Tpo .deps/keywords.Po
gcc -DHAVE_CONFIG_H -I. -I./config     -I/usr/include/mysql -g -O2 -MT error.o -MD -MP -MF .deps/error.Tpo -c -o error.o error.c
mv -f .deps/error.Tpo .deps/error.Po
/bin/sh ./libtool  --tag=CC   --mode=link gcc  -I/usr/include/mysql -g -O2  -L/usr/lib64 -lpthread -lssl -lm  -o spine sql.o spine.o util.o snmp.o locks.o poller.o nft_popen.o php.o ping.o keywords.o error.o  -lmysqlclient -lcrypto -lz -lpthread -lm 
libtool: link: gcc -I/usr/include/mysql -g -O2 -o spine sql.o spine.o util.o snmp.o locks.o poller.o nft_popen.o php.o ping.o keywords.o error.o  -L/usr/lib64 -lssl -lmysqlclient -lcrypto -lz -lpthread -lm
/usr/bin/ld: cannot find -lmysqlclient
collect2: error: ld returned 1 exit status
make: *** [spine] Error 1
[root@localhost spine]#

**Comment by vsltimkay** [comment]
You'll need to install MariaDB-shared to get the vanilla .so file (and mariadb client.cnf) files otherwise there is no library stub provided by the Mariadb RPMs - personally I think think this is confusing (as this error report shows) but there you go:

[pre install]
<pre>
~$ ld -lmysqlclient --verbose 
attempt to open /usr/x86_64-redhat-linux/lib64/libmysqlclient.so failed
attempt to open /usr/x86_64-redhat-linux/lib64/libmysqlclient.a failed
attempt to open /usr/lib64/libmysqlclient.so failed
attempt to open /usr/lib64/libmysqlclient.a failed
attempt to open /usr/local/lib64/libmysqlclient.so failed
attempt to open /usr/local/lib64/libmysqlclient.a failed
attempt to open /lib64/libmysqlclient.so failed
attempt to open /lib64/libmysqlclient.a failed
attempt to open /usr/x86_64-redhat-linux/lib/libmysqlclient.so failed
attempt to open /usr/x86_64-redhat-linux/lib/libmysqlclient.a failed
attempt to open /usr/local/lib/libmysqlclient.so failed
attempt to open /usr/local/lib/libmysqlclient.a failed
attempt to open /lib/libmysqlclient.so failed
attempt to open /lib/libmysqlclient.a failed
attempt to open /usr/lib/libmysqlclient.so failed
attempt to open /usr/lib/libmysqlclient.a failed
ld: cannot find -lmysqlclient
</pre>

Install
<pre>
# yum install MariaDB-shared
# rpm -ql MariaDB-shared
/etc/my.cnf.d
/etc/my.cnf.d/client.cnf
/usr/lib64/libmariadb.so
/usr/lib64/libmariadb.so.3
/usr/lib64/libmysqlclient.a
/usr/lib64/libmysqlclient.so
/usr/lib64/libmysqlclient_r.a
/usr/lib64/libmysqlclient_r.so
</pre>
[post install]
<pre>
~$ ld -lmysqlclient --verbose 
attempt to open /usr/x86_64-redhat-linux/lib64/libmysqlclient.so failed
attempt to open /usr/x86_64-redhat-linux/lib64/libmysqlclient.a failed
attempt to open /usr/lib64/libmysqlclient.so succeeded
-lmysqlclient (/usr/lib64/libmysqlclient.so)
</pre>

**Comment by cigamit** [comment]
This is a known issue with MariaDB 10.2.  Thought it was going to be fixed in 10.2-7, but you will have to wait for MariaDB.org to fix their RPM's.
