### ISSUE TITLE
Cacti Sending False Device Reboot Notifications

### ISSUE THREAD

**Issue by tamanullah** [Cacti/spine#259]
I am getting false reboot notifications for few of the firewalls. I am seeing below logs:
PCOMMAND Device[DEVICE-ID] NOTE: Recache Event Detected for Device
SPINE: Poller[Main Poller] PID[19385] PT[140673498670848] Device[DEVICE-ID] HT[1] DQ[SNMP - Interface Statistics] RECACHE ASSERT FAILED: '8342400<4000'

**Comment by TheWitness** [comment]
You failed to State your versions

**Comment by tamanullah** [comment]
> You failed to State your versions

Spine Version: 1.2.19
Cacti Version: 1.2.19

**Comment by TheWitness** [comment]
This was a known issue.  Goto spine 1.2.20.  Might have to do Cari 1.2.20+.  We just released 1.2.20, but ran into a few bugs.  The 1.2.x is stable now.

**Comment by TheWitness** [comment]
This was fixed in the 1.2.20 release, but wait for 1.2.21.
