### ISSUE TITLE
Spine 1.2.19 - Recache Event Detected for Device and RECACHE ASSERT FAILED: '3350528951<1008612900'  issue 

### ISSUE THREAD

**Issue by kasimanikandan** [Cacti/spine#262]
**Describe the bug**

Im using spine v1.2.19 for SNMP data collection for cacti (v1.2.18) and getting below messages in the cacti logs and those devices graph comes with blank. could you please help me how to fix this issue. When i do realtime polling its working fine... getting the traffic from the devices. 

i have tried to debug the issue by re-indexing the data query, but that didn't helped and also i have tried to remove and re-added associated data query didn't helped either.

Note: I have similar 700+ devices are getting polled without any issues except these ~5 to 10 devices.

Could you please advise how to fix this issue ?

![image](https://user-images.githubusercontent.com/85684729/166101265-502c3963-32a5-419a-8e49-aeafc933b5c3.png)

Graph:
![image](https://user-images.githubusercontent.com/85684729/166101548-817c848e-1d41-4e6c-b865-827811262491.png)

**To Reproduce**
Add devices for polling with spine (1.2.19) poller 

**Server (please complete the following information):**
 - OS: RedHat 7
 - Version : Spine 1.2.19 & Cacti 1.2.18

Thanks,
Mani

**Comment by TheWitness** [comment]
You might want to download spine 1.2.20, and the truncate the poller reindex table for good measure.

**Comment by kasimanikandan** [comment]
Thanks @TheWitness for quick response. 

This issue is fixed now by changing the re-indexing type from uptime to index count. 

Do you have architectural design documents for cacti ? 

Cheers,
Mani

**Comment by TheWitness** [comment]
@kasimanikandan, reach out to @bmfmancini he can help you with your inquiries.
