### ISSUE TITLE
Spine 1.2.19 Segmentation fault 

### ISSUE THREAD

**Issue by kasimanikandan** [Cacti/spine#264]
Hi,

im using large cacti system with 1 main poller and 3 remote pollers collecting ~ 3000 network devices every 5 mins and facing some random issues with spine getting Segmentation fault and Spine DB connection failed and at the same time those polling cycle breaching 5min limit and getting exited...  could you please advise what could be the probable root cause of this issue ?

Spine FATAL: Spine Encountered a Segmentation Fault
![image](https://user-images.githubusercontent.com/85684729/167301696-cd053e3c-3e3b-4c26-a083-7a25be283ed0.png)

DB Connection failure 

![image](https://user-images.githubusercontent.com/85684729/167301666-a833f0e2-4d15-4065-8518-125b15d7a9f7.png)

 Error Trend 
i can see there is coincidence between spine Segmentation fault issue with DB connection or vice versa.
![image](https://user-images.githubusercontent.com/85684729/167301863-9cc837d8-3df7-4084-b7ab-30fe4c78e1ed.png)

Cacti Version : 1.2.18
Spine Version : 1.2.19
Mariadb : 10.3

Operating System:
Redhat 7
Main poller Sys Spec : 24 Core CPU & 45 GB RAM
Remote Poller Sys Spec: 12 Core CPU & 16 GB RAM

Thanks,
Mani

**Comment by TheWitness** [comment]
Any core files?  Can you get a full backtrace.

**Comment by TheWitness** [comment]
Any core files?  Can you get a full backtrace. Also, post a screen shot of your data collectors page and technical support pages.

**Comment by kasimanikandan** [comment]
Thanks @TheWitness  for quick response.

Please find below for data collector and technical support page screenshots.

Data collector:
![image](https://user-images.githubusercontent.com/85684729/167322122-e27a4daa-22b0-4b70-bb50-f2053532017a.png)

Technical Support:
![image](https://user-images.githubusercontent.com/85684729/167322271-fa7c7c20-b0b0-4c26-906f-6242cc83a317.png)

![image](https://user-images.githubusercontent.com/85684729/167322359-7bc7eef8-3c4f-4de4-a36e-5476fa99a2c8.png)

![image](https://user-images.githubusercontent.com/85684729/167327874-2b8acef7-0a65-43e5-885b-1a2faed57969.png)

could you please advise how i can get backtrace ? is there any command to execute ?

Thanks,
Mani

**Comment by kasimanikandan** [comment]
Thanks  @TheWitness ... reducing the collector process/thread count fixed this issue... in last 24 hours no issues.

DB connection its seems max used connection is 744 and its looks fine.

Thanks,
Mani

**Comment by TheWitness** [comment]
You can run:

```sql
FLUSH STATUS;
```

And it will reset the max used connections to zero, then you can watch it for it's new peak.

**Comment by kasimanikandan** [comment]
Yeahh sure... i will try this.

Thanks a lot @TheWitness

**Comment by kasimanikandan** [comment]
now its reduced to ~200 max used connection.. i can see polling time also reduced significantly last 2 days.. no more warnings and error... 

Really appreciate for your support and thanks a lot @TheWitness  

Cheers,
Mani
