### ISSUE TITLE
spine not honouring my.cnf for socket location when using localhost

### ISSUE THREAD

**Issue by rb83** [Cacti/spine#268]
We're using a non-standard socket location. The mysql/mariadb client configuration has been adjusted accordingly. The spine configuration simply points to localhost - but instead of using a TCP connection, spine (or the mysql libs) attempt to use a UNIX socket instead (which is fine).

As described in #171, spine should honour the mysql client configuration - but it doesn't, and attempts to use the default location of mysql's socket. Explicitly setting the socket location in spine.cfg solves the issue.

Not sure wether this is intended behaviour (i.e. this is a documentation issue) or a true bug in either spine or the mysql client libs.

**To Reproduce**
1. Use a non-standard socket location for mysql, set client config in my.cnf as well.
2. Set `localhost`as DB server in spine.cfg
3. Attempt a manual poller run

**Server (please complete the following information):**
 - OS: RHEL7
 - MariaDB 5.5
 - Spine 1.2.21

**Comment by TheWitness** [comment]
I thought we allowed the DB_Hostname to point to a socket file.  Been a long time since I looked at it.

**Comment by rb83** [comment]
> I thought we allowed the DB_Hostname to point to a socket file. Been a long time since I looked at it.

Yes, that's what we do now. The problem that we observed is that when one sets it to `localhost`, spine (or the mysql libs) silently attempt to use a UNIX socket in the default location instead.

**Comment by TheWitness** [comment]
Yea, that would appear to be a client setup issue.  Did you update your client.cnf?

**Comment by rb83** [comment]
> Yea, that would appear to be a client setup issue. Did you update your client.cnf?

Yup.

**Comment by TheWitness** [comment]
Did you strace to see what variables it was looking for in the client.cnf or even if it was opening it?  Seems like an API bug.

**Comment by TheWitness** [comment]
Looking the doco, MariaDB supports a `[client-server]` section where you are supposed to put the socket, port, etc.  Maybe use that approach in server.cnf and likely client.cnf.

![image](https://user-images.githubusercontent.com/1439914/172932955-37a03306-45e8-4481-a643-c464aa1809ed.png)

https://mariadb.com/kb/en/configuring-mariadb-with-option-files/

**Comment by TheWitness** [comment]
This...

![image](https://user-images.githubusercontent.com/1439914/172933371-8af61b43-b763-4d96-92a8-51d962ad0687.png)

**Comment by TheWitness** [comment]
This...

![image](https://user-images.githubusercontent.com/1439914/172933524-0b9b213c-b240-4cbf-9090-3652fe966c66.png)

**Comment by netniV** [comment]
Pretty sure that by default, mysql will use a socket connection if localhost is specified, not TCP.  You can force the protocol by putting the protocol before the hostname, if I remember rightly.

**Comment by TheWitness** [comment]
What about a nice strace?

**Comment by rb83** [comment]
I'll try to clear up some time to provide you with an strace etc.

> Pretty sure that by default, mysql will use a socket connection if localhost is specified, not TCP. 

Correct, that has worked as expected. But it seems that the libraries do not use a configured (in my.cnf), non-standard socket location. Spine has to be explicitly told.

**Comment by TheWitness** [comment]
In spine.conf, for hostname, you can provide the path to the socket file.

**Comment by TheWitness** [comment]
We kind of went round and round on this.  The good thing is my last comment.  So, just closing.
