### ISSUE TITLE
somebody prepared cacti 1.2.x branch for 1.2.22 release but didn't prepare spine :)

### ISSUE THREAD

**Issue by jdcoats** [Cacti/spine#275]
somebody prepared cacti 1.2.x branch for 1.2.22 release but didn't prepare spine :)

**Comment by TheWitness** [comment]
Be nice, I have lot's of grey hair ;)

**Comment by netniV** [comment]
They may be prepared at different times, depending on why they are ready or need an upgrade test.  Only when the release/1.2.22 is tagged, should they both be in sync.

**Comment by TheWitness** [comment]
Resolved.
