### ISSUE TITLE
Failed to compile spine for 1.2.x (struct config_struct has no member named ‘cacti_version’)

### ISSUE THREAD

**Issue by simonpunk** [Cacti/spine#278]
[Environment]
OS: Arch Linux, 5.19.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Sun, 21 Aug 2022 18:55:22 +0000 x86_64 GNU/Linux
Cacti: 1.2.22, released Aug 14, 2022. (download from [https://www.cacti.net/info/downloads](https://www.cacti.net/info/downloads))
Spine: 1.2.x, clone from github

[Issue]
struct config_struct has no member named ‘cacti_version’
> [xxx@xxxx spine]$ ./compile.sh 
 rm -f spine
rm -rf .libs _libs
rm -f *.o
rm -f *.lo
gcc -DHAVE_CONFIG_H -I. -I./config     -I/usr/include/net-snmp -I/usr/include/net-snmp/.. -I/usr/include/mysql -g -O2 -MT util.o -MD -MP -MF .deps/util.Tpo -c -o util.o util.c
gcc -DHAVE_CONFIG_H -I. -I./config     -I/usr/include/net-snmp -I/usr/include/net-snmp/.. -I/usr/include/mysql -g -O2 -MT locks.o -MD -MP -MF .deps/locks.Tpo -c -o locks.o locks.c
gcc -DHAVE_CONFIG_H -I. -I./config     -I/usr/include/net-snmp -I/usr/include/net-snmp/.. -I/usr/include/mysql -g -O2 -MT poller.o -MD -MP -MF .deps/poller.Tpo -c -o poller.o poller.c
gcc -DHAVE_CONFIG_H -I. -I./config     -I/usr/include/net-snmp -I/usr/include/net-snmp/.. -I/usr/include/mysql -g -O2 -MT nft_popen.o -MD -MP -MF .deps/nft_popen.Tpo -c -o nft_popen.o nft_popen.c
util.c: In function ‘read_config_options’:
util.c:372:12: error: ‘config_t’ {aka ‘struct config_struct’} has no member named ‘cacti_version’
  372 |         set.cacti_version = get_cacti_version(&mysql, LOCAL);
      |            ^
util.c:372:29: warning: implicit declaration of function ‘get_cacti_version’ [-Wimplicit-function-declaration]
  372 |         set.cacti_version = get_cacti_version(&mysql, LOCAL);
      |                             ^~~~~~~~~~~~~~~~~
In file included from util.c:35:
util.c:375:70: error: ‘config_t’ {aka ‘struct config_struct’} has no member named ‘cacti_version’
  375 |         SPINE_LOG_DEBUG(("DEBUG: The binary Cacti version is %s", set.cacti_version));
      |                                                                      ^
spine.h:128:103: note: in definition of macro ‘SPINE_LOG_DEBUG’
  128 | #define SPINE_LOG_DEBUG(format_and_args)  (void)(set.log_level >= POLLER_VERBOSITY_DEBUG && spine_log format_and_args)
      |                                                                                                       ^~~~~~~~~~~~~~~
make: *** [Makefile:503: util.o] Error 1
make: *** Waiting for unfinished jobs....
mv -f .deps/nft_popen.Tpo .deps/nft_popen.Po
mv -f .deps/locks.Tpo .deps/locks.Po
mv -f .deps/poller.Tpo .deps/poller.Po

[possibly fix]
after adding `int    cacti_version;` to `typedef struct config_struct` and appending `extern int get_cacti_version(MYSQL *psql, int mode);` to the end of `util.h`, it succeeded to compile.

**Comment by TheWitness** [comment]
Glad you brought that up.  For got to commit it.  Will do that this morning.  Check back on the ticket and when you see the commit, you can re-pull the spine.h.

**Comment by TheWitness** [comment]
Okay, it's committed now.
