### ISSUE TITLE
TCP and UDP Ping Failure

### ISSUE THREAD

**Issue by sujunmin** [Cacti/spine#28]
I used CACTI 1.1.17 with latest spine, ubuntu 16.04.3 xenial, php 7, and set the hosts down/up alerts for Ping only.

And I found out that worked on Ping for ICMP, but did not work on TCP and UDP Ping.

I found again and again from cacti logs, and I got a conclusion for this issue.

If I set the "Ping Timout Interval" less then 1000 ms, the TCP and UDP Ping seemed to be worked (but it caused up and down frequently), and if more than 1000 ms, the spine log said the process was timeout (in about 60 secs).

The spine setting I used at 0.8.8a cacti before, and it was ok at that time.

How can I solve this problem?

**Comment by cigamit** [comment]
Please perform a tcp dump of the specific ports you are polling and run a read only spine manual run at debug level concurrently.

`tcpdump [port options] -w /tmp/filetoupload.pcap &`
`./spine -R -V 5 -S > /tmp/filetoupload.out`

Upload those two files.

**Comment by sujunmin** [comment]
Thanks for responding. 
These days I debugged this issue and got some results, I found out there was something wrong on `ping_tcp()` in spine.

This was the result of Device id 739, Ping Timeout Interval **1500**, `./spine -f 739 -l 739`
And the Device Status on the web was UP after running this.
```
SPINE: Initializing PHP Script Server(s)
NOTE: Spine will support multithread device polling.
DEBUG: Initial Value of Active Threads is 0
DEBUG: Valid Thread to be Created
DEBUG: In Poller, About to Start Polling of Device for Device ID 739
SPINE: Active Threads is 1, Pending is 1
Device[739] DEBUG: Entering TCP Ping
Device[739] DEBUG: TCP Device Alive, Try Count:1, Time:11.8258 ms
Device[739] PING: Result TCP: Device is Alive
Device[739] TH[1] Device has no information for recache.
Device[739] TH[1] Total Time: 0.014 Seconds
Device[739] TH[1] DEBUG: HOST COMPLETE: About to Exit Device Polling Thread Function
DEBUG: The Value of Active Threads is 0 for Device ID 739
POLLR: Active Threads is 0, Pending is 0
SPINE: The Final Value of Threads is 0
DEBUG: Thread Cleanup Complete
DEBUG: PHP Script Server Pipes Closed
DEBUG: Allocated Variable Memory Freed
DEBUG: MYSQL Free & Close Completed
DEBUG: Net-SNMP Close Completed
Time: 1.0167 s, Threads: 20, Devices: 1
```
This was the result of Device id 739, Ping Timeout Interval **1500**, but I made typo on Hostname and made the host down,  `./spine -f 739 -l 739`
And the Device Status on the web was **still UP**  after running this.
```
SPINE: Initializing PHP Script Server(s)
NOTE: Spine will support multithread device polling.
DEBUG: Initial Value of Active Threads is 0
DEBUG: Valid Thread to be Created
SPINE: Active Threads is 1, Pending is 1
DEBUG: In Poller, About to Start Polling of Device for Device ID 739
Device[739] DEBUG: Entering TCP Ping
ERROR: Spine Timed Out While Waiting for Threads to End
SPINE: The Final Value of Threads is 1
DEBUG: Thread Cleanup Complete
DEBUG: PHP Script Server Pipes Closed
DEBUG: Allocated Variable Memory Freed
DEBUG: MYSQL Free & Close Completed
DEBUG: Net-SNMP Close Completed
Time: 60.0385 s, Threads: 20, Devices: 1
```
This was the result of Device id 739, Ping Timeout Interval **900**, and I still made typo on Hostname and made the host down,  `./spine -f 739 -l 739`
And the Device Status on the web was changed to **DOWN** after running this.
```
SPINE: Initializing PHP Script Server(s)
NOTE: Spine will support multithread device polling.
DEBUG: Initial Value of Active Threads is 0
DEBUG: Valid Thread to be Created
DEBUG: In Poller, About to Start Polling of Device for Device ID 739
SPINE: Active Threads is 1, Pending is 1
Device[739] DEBUG: Entering TCP Ping
Device[739] PING Result: TCP: Cannot connect to host
Device[739] TH[1] Total Time:   2.7 Seconds
Device[739] TH[1] DEBUG: HOST COMPLETE: About to Exit Device Polling Thread Function
DEBUG: The Value of Active Threads is 0 for Device ID 739
POLLR: Active Threads is 0, Pending is 0
SPINE: The Final Value of Threads is 0
DEBUG: Thread Cleanup Complete
DEBUG: PHP Script Server Pipes Closed
DEBUG: Allocated Variable Memory Freed
DEBUG: MYSQL Free & Close Completed
DEBUG: Net-SNMP Close Completed
Time: 3.0133 s, Threads: 20, Devices: 1
```

**Comment by cigamit** [comment]
I will be committing a changes shortly.  Please see if the behavior is a bit more consistent for ping timeouts above 1 second.

**Comment by sujunmin** [comment]
Hi, thanks for your fix.
But There are still some issues for this fix.

1. Ping Timeout Interval **1500**, The **right** hostname: OK.
2. Ping Timeout Interval **1500**, The **wrong** hostname: Not OK. (Got timeout and the host still be UP on the web)
3. Ping Timeout Interval **900**, The **wrong** hostname: **Not OK** (Got timeout and the host still be UP on the web), and this is different from previous version.

**Comment by cigamit** [comment]
This is a GUI problem.  Please retest on Cacti 1.1.20.  The GUI based availability has been re-verified.  Also note that the UDP ping method reliability varies by OS and php version due to some socket reporting issues.  It's important that with UDP ping that you ping an unused port on the device.

**Comment by cigamit** [comment]
Also please note that under the Console > Settings > Poller, you need to have by default 3 successive failures before the device is marked down, and 2 good responses before the device is marked up.  If you change both values to 1, then the response will be more realtime.  Also, note that when using the -R (read only), no database writes take place, including device status.

**Comment by sujunmin** [comment]
Thanks, but the third test ,Ping Timeout Interval **900**, The **wrong** hostname, that is different before the commit of ping.c and after, I think that is not GUI problem, and I don't use -R is easy to test only.
