### ISSUE TITLE
Error on SPINE

### ISSUE THREAD

**Issue by Bochi75** [Cacti/spine#282]
Hello Team,

I just installer poller Spine on my Cacti and I have some issues, find bellow logs : 

SPINE: Poller[Main Poller] PID[1] PT[1] ERROR: Device[XXX] polling timed out while waiting for 1 Threads to End
SPINE: Poller[Main Poller] PID[1] PT[1] ERROR: Device[XXX] HT[1] Spine Timed Out While Processing Devices External
SPINE: Poller[Main Poller] PID[1] PT[1] ERROR: Device[XXX] HT[1] polling timed out while acquiring Available Thread Lock

My config is : 

Ubuntu 20.04
Cacti : Version 1.2.21
Spine : 1.2.22

And attached poller parameters.

Thanks for your help
<img width="541" alt="Conf 2" src="https://user-images.githubusercontent.com/114311163/194884091-00fa072b-92b6-4f70-8716-51a239d81559.png">
<img width="531" alt="Conf 1" src="https://user-images.githubusercontent.com/114311163/194884101-b54be8c6-aa91-4ea1-b426-01cdd65e788a.png">

**Comment by TheWitness** [comment]
The 80/20 you have shown is ridiculous.  Had to say it.  MySQL for one does not handle that well.

**Comment by Bochi75** [comment]
Hello @TheWitness ,

What is the right parameter ?

Regards,

**Comment by TheWitness** [comment]
How many CPUs, memory, devices and poller items?

**Comment by Bochi75** [comment]
Sorry for late reply :(

My machine has : 4 vCPU and 24 Go Ram
I monitor 100 devices and  arount 1000 items.

**Comment by TheWitness** [comment]
I would use 1 process and 10 threads top with only 4vCPU.  You make this change in `Console > Data Collection > Data Collectors`
