### ISSUE TITLE
Graphs are not displayed

### ISSUE THREAD

**Issue by densenator** [Cacti/spine#283]
Maybe After update spine to latest version, my graphs are not displayed.
![image](https://user-images.githubusercontent.com/18443709/194049259-7c189243-693d-49e8-9fd3-68c537bbcce3.png)
Log:
05.Oct.2022 14:16:47 - PCOMMAND Device NOTE: Recache Event Detected for Device

SPINE: Poller[[Main Poller](https://cacti.satgate.net/pollers.php?action=edit&id=1)] PID[2852065] PT[139630544393984] Device HT[1] DQ[[SNMP - Interface Statistics](https://cacti.satgate.net/data_queries.php?action=edit&id=4)] RECACHE ASSERT FAILED: '2630130<'

This is for all devices.

**Comment by TheWitness** [comment]
No feedback.
