### ISSUE TITLE
Poller Execution Exceed Maximum Runtime

### ISSUE THREAD

**Issue by tamanullah** [Cacti/spine#284]
I am getting below logs often
POLLER: Poller[[Main Poller] PID[8432] Maximum runtime of 58 seconds exceeded. Exiting.

It seems that there is one device which is taking too long to respond to query.

I have checked and server stats are fine. I even increased resources and also increased processes and threads for spine. Issue still persists.

Is there a way that I can retrieve the host which is taking too long to respond?

Cacti Version: 1.2.21
Spine Version: 1.2.21

**Comment by TheWitness** [comment]
If you run spine in debug mode, you can see the timing for each call.  So run spine manually like the example below and post the results. 

```bash
./spine -R -S -V 3
```

**Comment by tamanullah** [comment]
[spine-output.txt](https://github.com/Cacti/spine/files/9996423/spine-output.txt)
Here is the output of spine.

**Comment by TheWitness** [comment]
Although Reindex Method "Verify All Fields" is there, I don't recommend it.

That takes a good bit of the polling time. 

So, Device ID Device[139] is using it.  If you don't know what I'm talking about, read up on Data Queries.

**Comment by TheWitness** [comment]
Closing.  These questions belong on the forums.
