### ISSUE TITLE
ifAlias and ifType are not polled

### ISSUE THREAD

**Issue by jorbanj** [Cacti/spine#288]
**Describe the bug**
ifAlias and ifType are not polled

**To Reproduce**
1. Do a verbose query for SNMP - Interface Statistics on a device
2. Scroll down to 'Click to show Data Query output for field 'ifAlias''
3. Click on 'Click to show Data Query output for field 'ifAlias''
4. See error that no data is displayed

**Expected behavior**
Expectation is to get data from interfaces, namely interface description in this case.

**Screenshots**
**before:**
![image](https://user-images.githubusercontent.com/44637130/203976957-8ecd496f-8ffd-4481-a08c-8e00c8389ffe.png)

**after removing "<output_format>ascii</output_format>" in interface.xml:**
![image](https://user-images.githubusercontent.com/44637130/203978584-e623b52d-4403-4dc0-84ad-16cc023d4b66.png)

**Server (please complete the following information):**
 - OS: Windows Server 2016
 - Version 1607

**Compiling (please complete the following information):**

[Windows All-In-One Installer [Cacti 1.2.22]](https://forums.cacti.net/viewtopic.php?t=14946&sid=4d125f4a8623dea6599c4f8627c0d723)

**Additional context**
Seems the issue is caused by "<output_format>ascii</output_format>" in interface.xml under /resource/snmp_queries/
This is only applied to ifAlias and ifType and neither of them works.
When commenting that line out, it works ok (screenshot "after").
Same applies for ifType.

**Comment by TheWitness** [comment]
You need to increase your timeout I think.

**Comment by TheWitness** [comment]
Also, our you ifAlias' in ASCII or a foreign language?

**Comment by jorbanj** [comment]
Why do you think so if modifying the interface.xml has a clear effect on fixing/breaking it?
Should be just standard characters.
Also I don't think ifType can be of any foreign language :)

![image](https://user-images.githubusercontent.com/44637130/203996543-f7df2912-79fb-452a-840f-1e864b8e84e8.png)

**Comment by jorbanj** [comment]
When I saw this ... https://github.com/php/php-src/pull/6633 ... I thought it was caused by me using old PHP, so I got 8.1.13 but still looks the same.

**Comment by TheWitness** [comment]
Do not use php-snmp unless you are not planning on having ipv6 devices.  Start there, uninstall php-snmp, restart php, increase the timeout and try re-indexing again.  Look to your cacti.log for errors too.  This really should be a issue in the Forums since this function is working for thousands of install right now.

**Comment by jorbanj** [comment]
Ah ok thanks.
