### ISSUE TITLE
Unable to upgrade Spine 1.21 to 1.2.22

### ISSUE THREAD

**Issue by darkness4773** [Cacti/spine#289]
**Describe the bug**
After extracting the cacti-spine-1.2.22.tar.gz, i go in the folder cacti-spine-1.2.22

I execute the commands 
        #sudo ./bootstrap
	#sudo ./configure
	#sudo make

The make command fails with the following messages:

gcc -DHAVE_CONFIG_H -I. -I./config     -I/usr/include/net-snmp -I/usr/include/net-snmp/.. -I/usr/include/mysql -g -O2 -MT sql.o -MD -MP -MF .deps/sql.Tpo -c -o sql.o sql.c
sql.c: In function ‘db_connect’:
sql.c:353:6: error: ‘ssl_key’ undeclared (first use in this function)
  if (ssl_key != NULL) {
      ^
sql.c:353:6: note: each undeclared identifier is reported only once for each function it appears in
sql.c:357:6: error: ‘ssl_ca’ undeclared (first use in this function)
  if (ssl_ca != NULL) {
      ^
sql.c:361:6: error: ‘ssl_cert’ undeclared (first use in this function)
  if (ssl_cert != NULL) {
      ^
make: *** [sql.o] Error 1

**Expected behavior**
It's not the first time i upgrade the CACTI SPINE and it's the first time i have this issue.
It looks like an issue because of the database but i don't understand why.

**Server (please complete the following information):**
 - CentOS 7
 - CACTI1.2.22

Any idea why i have this and what i have to do to be able to upgrade my Spine 1.2.21 to 1.2.22?

Thx

**Comment by TheWitness** [comment]
Please download the 1.2.x branch.  This issue has already been fixed and will be a part of the 1.2.23 release.
