### ISSUE TITLE
Changelog communication / documentation

### ISSUE THREAD

**Issue by eschoeller** [Cacti/spine#29]
I just noticed there have been a few spine changes that I wasn't really aware of, eager to get the new version up and running! A couple suggestions ...

Perhaps when Release notices are sent to cacti-announce about new Cacti versions (including the recent changelog) spine could be included in this e-mail notification as well? 
Also, the changelog on the web (https://cacti.net/spine_changelog.php) is missing a few entries from the changelog that I see in github.

Either one of these would help me (and maybe others) stay informed and up to date on spine. Thanks!

**Comment by ronytomen** [comment]
Good point to having the change log on the release emails/forum posts.  I will update the process to add those change logs.

It may or may not take me a bit, but I will review the change logs and what is on the main Cacti site to ensure they are correct.

**Comment by cigamit** [comment]
Closing.  We are doing as good as we can get now.
