### ISSUE TITLE
Enhance number recognition within Spine

### ISSUE THREAD

**Issue by eschoeller** [Cacti/spine#291]
Please take a look at Cacti/cacti#2662. I'm finding that text such as "15 Percent" and "14401 Watts" work just fine. But when I encounter "12609 Volt-Amps", it causes a problem. I suspect it's because of the '-' being interpreted as part of the numeric value and not the alphanumeric text that should be removed. I'm not sure if there's a graceful way to fix this ... but it would be super nice if it could get fixed :) 
Perhaps only accept a '-' character if it's at the beginning of the string, or, directly adjacent to the beginning of the numeric value.

**Comment by TheWitness** [comment]
@eschoeller, test out @netniV spine changes.  Develop branch.

**Comment by netniV** [comment]
@bmfmancini Would you also test this on your rigs?  Make sure it doesn't fall over in a big heap

**Comment by TheWitness** [comment]
Here is spine 1.2.25 as of today...

![image](https://github.com/Cacti/spine/assets/1439914/05278145-39cd-4ec3-9fc4-5f27aafeea6f)
