### ISSUE TITLE
1.2.x - Host SNMP uptime check broken

### ISSUE THREAD

**Issue by browniebraun** [Cacti/spine#299]
**Describe the bug**
Not sure what the main reason is, but after upgrading from 1.2.16 to 1.2.23 (1.2.x), a few hundreds hosts are down and marked as unreachable. They are reachable using the Cacti GUI as well as using SNMP at CLI level.

Spine in debug mode returns following info in respect of the host status:
`2023/01/25 12:47:07 - SPINE: Poller[1] PID[117131] PT[140101424420608] DEBUG: Device[0] HT[1] DEBUG: HOST COMPLETE: About to Exit Device Polling Thread Function
2023/01/25 12:47:07 - SPINE: Poller[1] PID[117131] PT[140101416027904] DEBUG: Device[11779] HT[1] In Poller, About to Start Polling
2023/01/25 12:47:07 - SPINE: Poller[1] PID[117131] PT[140101416027904] DEBUG: Traversing Local Connection Pool for free connection.
2023/01/25 12:47:07 - SPINE: Poller[1] PID[117131] PT[140101416027904] DEBUG: Checking Local Pool ID 0.
2023/01/25 12:47:07 - SPINE: Poller[1] PID[117131] PT[140101416027904] DEBUG: Allocating Local Pool ID 0.
2023/01/25 12:47:07 - SPINE: Poller[1] PID[117131] PT[140101416027904] get_namebyhost(***.***.***.228) - Allocating name_t
2023/01/25 12:47:07 - SPINE: Poller[1] PID[117131] PT[140101416027904] get_namebyhost(***.***.***.228) - No delimiter, assume full hostname
2023/01/25 12:47:07 - SPINE: Poller[1] PID[117131] PT[140101416027904] Device[11779] INFO: SNMP Device '***.***.***.228:161' has a timeout of 1200000 (1200), with 1 retries
2023/01/25 12:47:07 - SPINE: Poller[1] PID[117131] PT[140101416027904] Device[11779] DEBUG: Entering SNMP Ping
2023/01/25 12:47:07 - SPINE: Poller[1] PID[117131] PT[140101416027904] ERROR: Unknown error getting oid '.1.3.6.1.2.1.1.3.0' for Device[11779] with Status[1]
2023/01/25 12:47:07 - SPINE: Poller[1] PID[117131] PT[140101416027904] Device[11779] SNMP Ping Unknown Error
2023/01/25 12:47:07 - SPINE: Poller[1] PID[117131] PT[140101416027904] Device[11779] SNMP Result: Device did not respond to SNMP
2023/01/25 12:47:07 - SPINE: Poller[1] PID[117131] PT[140101416027904] Device[11779] HT[1] NOTE: There are '67' Polling Items for this Device
2023/01/25 12:47:07 - SPINE: Poller[1] PID[117131] PT[140101416027904] DEBUG: Setting up writes to local database
2023/01/25 12:47:07 - SPINE: Poller[1] PID[117131] PT[140101416027904] Device[11779] HT[1] Updating Poller Items for Next Poll
2023/01/25 12:47:07 - SPINE: Poller[1] PID[117131] PT[140101416027904] Device[11779] HT[1] Total Time: 0.0023 Seconds
`

Manual run returns:
snmpwalk -v 2c -c ********* ***.***.***.228 .1.3.6.1.2.1.1.3.0
`DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (3021577869) 349 days, 17:16:18.6`

Looks like Spine dislikes something like returned packet format.

**Comment by netniV** [comment]
There is a patch already for this if you look through the recent issues.  It comes because of a fatal error during the handling of uptime.  Grab the latest source and recompile from the 1.2.x branch.

**Comment by browniebraun** [comment]
Mark,
that is what I have already done on January, the 25th. The issue still remains and last commitment was more than a week ago. I'm remembering that the same issue already occurred in 1.2.16 and that was the reason why I had a modified version running. Maybe I can figure out what Larry and I had modified in the past as I cannot remember at the moment. This is not a duplicate.

**Comment by browniebraun** [comment]
From my point of view the errors lays in function snmp_get_base() around line 448 in snmp.c

![image](https://user-images.githubusercontent.com/5182348/215073212-6c24983e-f1e9-4f0b-bad5-6eb8e7cad1c9.png)


All hosts faultlessly marked as being down are EXTRANET devices only, while thousands of INTRANET hosts are fine.

**Comment by browniebraun** [comment]
It has been nailed down that local CSP setup has taken the complete path to the SPINE binary into consideration for the EXTRANET ruleset.
