### ISSUE TITLE
Compile problem under cygwin

### ISSUE THREAD

**Issue by Owned67** [Cacti/spine#30]
Hello,

 /cygdrive/c/wamp/www/cacti/spine
$ ./bootstrap
INFO: Starting Spine build process
INFO: Removing cache directories
INFO: Running auto-tools to verify buildability
Can't exec "aclocal": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf-2.69: failed to run aclocal: No such file or directory
ERROR: 'autoreconf' exited with errors

In C:\cygwin\usr\share folder, aclocal is here:
aclocal-1.15
aclocal

can you help me for build?

Cheers

**Comment by cigamit** [comment]
You are missing automake and likely help2man.  Just keep trying.

**Comment by Owned67** [comment]
automake and hel2map is installed....

**Comment by cigamit** [comment]
Type 'which aclocal', if you get back a path, you might have to install other versions of automake.  I compiled the 1.1.20 from Cygwin just fine yesterday.

**Comment by cigamit** [comment]
Also, I did update the cacti documentation/installation instructions for Cacti yesterday calling out the packages to install and download for compiling both spine and rrdtool yesterday, though I don't think that RRDtool will compile on Cygwin right now due to some bad commit's after RRDtool 1.4.5.

**Comment by Owned67** [comment]
`ric@W10-Revolution ~
$ which aclocal
which: no aclocal in (/usr/local/bin:/usr/bin:/cygdrive/b/Perl/bin:/cygdrive/c/ProgramData/Oracle/Java/javapath:/cygdrive/c/Windows/system32:/cygdrive/c/Windows:/cygdrive/c/Windows/System32/Wbem:/cygdrive/c/Windows/System32/WindowsPowerShell/v1.0)
`

i have try automake 1.09 to 1.14 and i get same error...

**Comment by Owned67** [comment]
Problem solved. compile under linux work
