### ISSUE TITLE
spine 1.2.23 segmentation fault

### ISSUE THREAD

**Issue by P4-blemire** [Cacti/spine#300]
After updating cacti and cacti-spine on my CentOS server, I am getting the error "FATAL: Spine Encountered a Segmentation Fault" in my cacti_stderr.log with a follow-up message "Generating backtrace...0 line(s)..."

If I manually execute  ./spine -R -V 3 -S I see the same error.  Oddly enough, my graphs still seem to be populating as expected, but the spine error is concerning.  What steps can I take to get additional data on the spine crash to provide more info for this bug report?

**Server (please complete the following information):**
 - OS: [e.g. CentOS 7] Centos 8 Stream
 - Version [e.g. 22] 1.2.23

**Comment by P4-blemire** [comment]
Running spine manually with a higher level of verbosity doesn't give any increased detail.

**Comment by P4-blemire** [comment]
gdb ./spine
GNU gdb (GDB) Red Hat Enterprise Linux 8.2-19.el8
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./spine...Reading symbols from /usr/lib/debug/usr/bin/spine-1.2.23-1.el8.x86_64.debug...done.
done.
(gdb) run
Starting program: /usr/bin/spine
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
SPINE: Using spine config file [/etc/spine.conf]
Version 1.2.23 starting
[Detaching after vfork from child process 40800]
[New Thread 0x7ffff5ea1700 (LWP 40801)]
[New Thread 0x7ffff56a0700 (LWP 40802)]
[New Thread 0x7ffff4e9f700 (LWP 40803)]
[Thread 0x7ffff5ea1700 (LWP 40801) exited]
[New Thread 0x7ffff5ea1700 (LWP 40804)]
[New Thread 0x7fffe7fff700 (LWP 40805)]
[New Thread 0x7fffe77fe700 (LWP 40806)]
[New Thread 0x7fffe6ffd700 (LWP 40807)]
[New Thread 0x7fffe67fc700 (LWP 40808)]
[New Thread 0x7fffe5ffb700 (LWP 40809)]
[New Thread 0x7fffe57fa700 (LWP 40810)]
[New Thread 0x7fffe4ff9700 (LWP 40811)]
[Thread 0x7ffff5ea1700 (LWP 40804) exited]
[Thread 0x7ffff4e9f700 (LWP 40803) exited]
[Thread 0x7fffe7fff700 (LWP 40805) exited]
[New Thread 0x7fffe7fff700 (LWP 40812)]
[New Thread 0x7ffff4e9f700 (LWP 40813)]
[New Thread 0x7ffff5ea1700 (LWP 40814)]
[Thread 0x7fffe4ff9700 (LWP 40811) exited]
[New Thread 0x7fffe4ff9700 (LWP 40815)]
[Thread 0x7fffe5ffb700 (LWP 40809) exited]
[New Thread 0x7fffe5ffb700 (LWP 40816)]
[Thread 0x7ffff56a0700 (LWP 40802) exited]
[New Thread 0x7ffff56a0700 (LWP 40817)]
[Thread 0x7fffe6ffd700 (LWP 40807) exited]
[New Thread 0x7fffe6ffd700 (LWP 40818)]
[Thread 0x7fffe57fa700 (LWP 40810) exited]
[New Thread 0x7fffe57fa700 (LWP 40819)]
[Thread 0x7fffe67fc700 (LWP 40808) exited]
[New Thread 0x7fffe67fc700 (LWP 40820)]
[Thread 0x7fffe77fe700 (LWP 40806) exited]
[Thread 0x7fffe7fff700 (LWP 40812) exited]
[New Thread 0x7fffe7fff700 (LWP 40821)]
[New Thread 0x7fffe77fe700 (LWP 40822)]
[Thread 0x7ffff5ea1700 (LWP 40814) exited]
[New Thread 0x7ffff5ea1700 (LWP 40823)]
[Thread 0x7fffe4ff9700 (LWP 40815) exited]
[New Thread 0x7fffe4ff9700 (LWP 40824)]
[Thread 0x7fffe6ffd700 (LWP 40818) exited]
[New Thread 0x7fffe6ffd700 (LWP 40825)]
[Thread 0x7fffe5ffb700 (LWP 40816) exited]
[New Thread 0x7fffe5ffb700 (LWP 40826)]
[Thread 0x7fffe67fc700 (LWP 40820) exited]
[New Thread 0x7fffe67fc700 (LWP 40827)]
[Thread 0x7ffff4e9f700 (LWP 40813) exited]
[New Thread 0x7ffff4e9f700 (LWP 40828)]
[Thread 0x7fffe77fe700 (LWP 40822) exited]
[Thread 0x7fffe7fff700 (LWP 40821) exited]
[New Thread 0x7fffe7fff700 (LWP 40829)]
[New Thread 0x7fffe77fe700 (LWP 40830)]
[Thread 0x7fffe57fa700 (LWP 40819) exited]
[New Thread 0x7fffe57fa700 (LWP 40831)]
[Thread 0x7ffff56a0700 (LWP 40817) exited]
[New Thread 0x7ffff56a0700 (LWP 40832)]
[Thread 0x7fffe5ffb700 (LWP 40826) exited]
[New Thread 0x7fffe5ffb700 (LWP 40833)]
[Thread 0x7ffff5ea1700 (LWP 40823) exited]
[New Thread 0x7ffff5ea1700 (LWP 40834)]
[Detaching after vfork from child process 40835]
[Thread 0x7fffe4ff9700 (LWP 40824) exited]
[New Thread 0x7fffe4ff9700 (LWP 40839)]
[Thread 0x7fffe7fff700 (LWP 40829) exited]
[New Thread 0x7fffe7fff700 (LWP 40840)]
[Detaching after vfork from child process 40841]
[Thread 0x7fffe77fe700 (LWP 40830) exited]
[New Thread 0x7fffe77fe700 (LWP 40845)]
[Thread 0x7fffe7fff700 (LWP 40840) exited]
[New Thread 0x7fffe7fff700 (LWP 40846)]
[Thread 0x7fffe67fc700 (LWP 40827) exited]
[New Thread 0x7fffe67fc700 (LWP 40847)]
[Thread 0x7fffe6ffd700 (LWP 40825) exited]
[New Thread 0x7fffe6ffd700 (LWP 40848)]

Thread 38 "spine" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe77fe700 (LWP 40845)]
0x00007ffff6143f5d in vsnprintf () from /lib64/libc.so.6

**Comment by P4-blemire** [comment]
More complete gdb output:

gdb ./spine
GNU gdb (GDB) Red Hat Enterprise Linux 8.2-19.el8
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./spine...Reading symbols from /usr/lib/debug/usr/bin/spine-1.2.23-1.el8.x86_64.debug...done.
done.
(gdb) run
Starting program: /usr/bin/spine
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
SPINE: Using spine config file [/etc/spine.conf]
Version 1.2.23 starting
[Detaching after vfork from child process 44801]
[New Thread 0x7ffff5ea1700 (LWP 44802)]
[New Thread 0x7ffff56a0700 (LWP 44803)]
[New Thread 0x7ffff4e9f700 (LWP 44804)]
[New Thread 0x7fffe7fff700 (LWP 44805)]
[Thread 0x7ffff5ea1700 (LWP 44802) exited]
[New Thread 0x7ffff5ea1700 (LWP 44806)]
[Thread 0x7ffff5ea1700 (LWP 44806) exited]
[Thread 0x7fffe7fff700 (LWP 44805) exited]
[New Thread 0x7fffe7fff700 (LWP 44807)]
[Thread 0x7ffff4e9f700 (LWP 44804) exited]
[New Thread 0x7ffff4e9f700 (LWP 44808)]
[New Thread 0x7ffff5ea1700 (LWP 44809)]
[Thread 0x7ffff56a0700 (LWP 44803) exited]
[New Thread 0x7ffff56a0700 (LWP 44810)]
[Detaching after vfork from child process 44811]
[Thread 0x7fffe7fff700 (LWP 44807) exited]
[New Thread 0x7fffe7fff700 (LWP 44815)]
[Thread 0x7ffff5ea1700 (LWP 44809) exited]
[New Thread 0x7ffff5ea1700 (LWP 44816)]
[Thread 0x7ffff4e9f700 (LWP 44808) exited]
[New Thread 0x7ffff4e9f700 (LWP 44817)]
[Thread 0x7ffff56a0700 (LWP 44810) exited]
[New Thread 0x7ffff56a0700 (LWP 44818)]
[Thread 0x7fffe7fff700 (LWP 44815) exited]
[New Thread 0x7fffe7fff700 (LWP 44819)]
[Thread 0x7ffff4e9f700 (LWP 44817) exited]
[New Thread 0x7ffff4e9f700 (LWP 44820)]
[Thread 0x7ffff5ea1700 (LWP 44816) exited]
[New Thread 0x7ffff5ea1700 (LWP 44821)]
[Thread 0x7ffff56a0700 (LWP 44818) exited]
[New Thread 0x7ffff56a0700 (LWP 44822)]
[Thread 0x7ffff4e9f700 (LWP 44820) exited]
[New Thread 0x7ffff4e9f700 (LWP 44823)]
[Thread 0x7ffff5ea1700 (LWP 44821) exited]
[New Thread 0x7ffff5ea1700 (LWP 44824)]
[Thread 0x7fffe7fff700 (LWP 44819) exited]
[New Thread 0x7fffe7fff700 (LWP 44825)]
[Thread 0x7ffff56a0700 (LWP 44822) exited]
[New Thread 0x7ffff56a0700 (LWP 44826)]
[Thread 0x7ffff5ea1700 (LWP 44824) exited]
[New Thread 0x7ffff5ea1700 (LWP 44827)]
[Thread 0x7fffe7fff700 (LWP 44825) exited]
[New Thread 0x7fffe7fff700 (LWP 44828)]
[Thread 0x7ffff4e9f700 (LWP 44823) exited]
[New Thread 0x7ffff4e9f700 (LWP 44829)]
[Thread 0x7ffff56a0700 (LWP 44826) exited]
[New Thread 0x7ffff56a0700 (LWP 44830)]
[Thread 0x7ffff5ea1700 (LWP 44827) exited]
[New Thread 0x7ffff5ea1700 (LWP 44831)]
[Thread 0x7fffe7fff700 (LWP 44828) exited]
[New Thread 0x7fffe7fff700 (LWP 44832)]
[Thread 0x7ffff4e9f700 (LWP 44829) exited]
[New Thread 0x7ffff4e9f700 (LWP 44833)]
[Thread 0x7fffe7fff700 (LWP 44832) exited]
[New Thread 0x7fffe7fff700 (LWP 44834)]
[Thread 0x7ffff5ea1700 (LWP 44831) exited]
[New Thread 0x7ffff5ea1700 (LWP 44835)]
[Thread 0x7ffff56a0700 (LWP 44830) exited]
[New Thread 0x7ffff56a0700 (LWP 44836)]
[Thread 0x7ffff4e9f700 (LWP 44833) exited]
[New Thread 0x7ffff4e9f700 (LWP 44837)]
[Detaching after vfork from child process 44838]
[Thread 0x7ffff56a0700 (LWP 44836) exited]
[New Thread 0x7ffff56a0700 (LWP 44842)]
[Thread 0x7fffe7fff700 (LWP 44834) exited]
[New Thread 0x7fffe7fff700 (LWP 44843)]
[Thread 0x7ffff4e9f700 (LWP 44837) exited]
[New Thread 0x7ffff4e9f700 (LWP 44844)]
[Thread 0x7ffff5ea1700 (LWP 44835) exited]
[New Thread 0x7ffff5ea1700 (LWP 44845)]
[Thread 0x7ffff56a0700 (LWP 44842) exited]
[New Thread 0x7ffff56a0700 (LWP 44846)]
[Detaching after vfork from child process 44847]
[Thread 0x7ffff4e9f700 (LWP 44844) exited]
[New Thread 0x7ffff4e9f700 (LWP 44851)]
[Thread 0x7ffff5ea1700 (LWP 44845) exited]
[New Thread 0x7ffff5ea1700 (LWP 44852)]
[Thread 0x7fffe7fff700 (LWP 44843) exited]
[New Thread 0x7fffe7fff700 (LWP 44853)]
[Thread 0x7ffff4e9f700 (LWP 44851) exited]
[New Thread 0x7ffff4e9f700 (LWP 44854)]
[Thread 0x7ffff56a0700 (LWP 44846) exited]
[New Thread 0x7ffff56a0700 (LWP 44855)]
[Thread 0x7ffff56a0700 (LWP 44855) exited]
[New Thread 0x7ffff56a0700 (LWP 44856)]

Thread 44 "spine" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff56a0700 (LWP 44856)]
_IO_vsnprintf (string=0x0, maxlen=<optimized out>, format=0x5555555756ca "%s", args=args@entry=0x7ffff567a760)
    at vsnprintf.c:112
112       string[0] = '\0';

**Comment by netniV** [comment]
This is actually a duplicate issue and has already been addressed for the upcoming 1.2.24 release.

**Comment by P4-blemire** [comment]
Can you link to the original issue so I can follow, or is this something hidden/internal?
