### ISSUE TITLE
undefined symbol: usmHMACMD5AuthProtocol

### ISSUE THREAD

**Issue by Tsvetk** [Cacti/spine#301]
**To Reproduce**
> spine
spine: symbol lookup error: spine: undefined symbol: usmHMACMD5AuthProtocol

**Server (please complete the following information):**
 Information for package cacti-spine:
------------------------------------
Repository     : openSUSE-Tumbleweed-Oss
Name           : cacti-spine
Version        : 1.2.23-1.1
Arch           : x86_64
Vendor         : openSUSE
Installed Size : 203.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : cacti-spine-1.2.23-1.1.src
Upstream URL   : https://www.cacti.net/spine_info.php
Summary        : Threaded poller for Cacti written in C

Information for package libsnmp40:
----------------------------------
Repository     : openSUSE-Tumbleweed-Oss
Name           : libsnmp40
Version        : 5.9.3-4.1
Arch           : x86_64
Vendor         : openSUSE
Installed Size : 4.0 MiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : net-snmp-5.9.3-4.1.src
Upstream URL   : https://sourceforge.net/projects/net-snmp

**Comment by netniV** [comment]
Since this is a pre-compiled package, we have no idea of the configuration used to make spine. You'll need to talk with the package maintainers first.  The above isn't enough to go on at this point.

**Comment by Tsvetk** [comment]
fix 


Information for package libsnmp40:
----------------------------------
Repository     : openSUSE-Tumbleweed-Oss
Name           : libsnmp40
Version        : 5.9.3-4.2
