### ISSUE TITLE
Device Status **Unknown** spine poller type

### ISSUE THREAD

**Issue by infinitynet2011** [Cacti/spine#316]
Hello!

I have this setup:

OS  Almalinux 9.2
Cacti Version	1.2.24
NET-SNMP Version	NET-SNMP version: 5.9.1
RRDtool Version Configured	1.7.2+
RRDtool Version Found	1.7.2
SPINE 1.2.24 

This error:

Device Status **Unknown** only when I switch on Spine as poller type.

Check the spine with  **/spine -R -V 3 -S**

Total[0.3135] DEBUG: Device[34] HT[2] DEBUG: HOST COMPLETE: About to Exit Device Polling Thread Function
Total[0.3396] DEBUG: Device[34] HT[3] DEBUG: HOST COMPLETE: About to Exit Device Polling Thread Function
Total[0.4244] DEBUG: Device[34] HT[1] DEBUG: HOST COMPLETE: About to Exit Device Polling Thread Function
Total[0.6175] DEBUG: Device[34] HT[4] DEBUG: HOST COMPLETE: About to Exit Device Polling Thread Function
Total[0.8104] Time: 0.8103 s, Threads: 10, Devices: 2

.. no errors there!

Thanks,
Gabe

**Comment by TheWitness** [comment]
Do `-V 5`

**Comment by TheWitness** [comment]
Also, `-R` does NOT write the host status. So, host stays Unknown.

**Comment by infinitynet2011** [comment]
I don't follow. I can fix it?

./spine -R -V 5 -S -R | grep COMPLETE
Total[0.2472] DEBUG: Device[0] HT[1] DEBUG: HOST COMPLETE: About to Exit Device Polling Thread Function
Total[0.2915] DEBUG: Device[34] HT[1] DEBUG: HOST COMPLETE: About to Exit Device Polling Thread Function
Total[0.8034] Time: 0.8033 s, Threads: 10, Devices: 2

Thanks,
Gabe

**Comment by netniV** [comment]
Please don't filter the output as we need to see what is going on in order to diagnose your problem fully.  You are free to mask hostnames and/or other sensitive info but we need to see the logs as they appear outside of that.

**Comment by gvoitis** [comment]
Hello!

My mistake. Please check this also.
I added an ESXi server (no spine this time)

1) **Unknown** in the Device list
2) No graph is generated
3) I disable and enable the host

![Screenshot_34](https://github.com/Cacti/spine/assets/42605037/de1dfbf7-a8d1-4277-aef8-18194660c868)
![Screenshot_29](https://github.com/Cacti/spine/assets/42605037/2d813523-9d4d-4303-aa2d-6e343ed7d2a8)
![Screenshot_32](https://github.com/Cacti/spine/assets/42605037/cbe06f6e-023b-4171-9f39-4e7d8429e33c)


Thanks,
Gabe

**Comment by TheWitness** [comment]
Closing as a non-issue, no feedback.
