### ISSUE TITLE
MySQL reconnect option is depreciated

### ISSUE THREAD

**Issue by server24** [Cacti/spine#317]
**Describe the bug**
Recent libmysqlclient-packages output an stderr warning when MYSQL_OPT_RECONNECT is used (even if set to false!) that fills up logs and maybe even e-mail messages.

**To Reproduce**
1. Perform an update to a recent version of libmysqlclient (8.0.34 and 8.1)
2. Run spine

**Expected behavior**
No STDERR output should be shown.

**Possible patch/fix**

--- sql.orig.c	2023-09-05 01:57:16.000000000 +0200
+++ sql.c	2023-09-20 23:15:37.933557926 +0200
@@ -277,7 +277,9 @@
 	MYSQL_SET_OPTION(MYSQL_OPT_READ_TIMEOUT, (int *)&rtimeout, "read timeout");
 	MYSQL_SET_OPTION(MYSQL_OPT_WRITE_TIMEOUT, (int *)&wtimeout, "write timeout");
 	MYSQL_SET_OPTION(MYSQL_OPT_CONNECT_TIMEOUT, (int *)&timeout, "general timeout");
+	#if MYSQL_VERSION_ID >= 50013 && MYSQL_VERSION_ID < 80034
 	MYSQL_SET_OPTION(MYSQL_OPT_RECONNECT, &reconnect, "reconnect");
+	#endif

 	#ifdef HAS_MYSQL_OPT_RETRY_COUNT
 	MYSQL_SET_OPTION(MYSQL_OPT_RETRY_COUNT, &tries, "retry count");

**Comment by server24** [comment]
Of course please verify how reconnections are handled and/or if handling is needed as this patch would effectively disable the automatic reconnection mechanism.

**Comment by TheWitness** [comment]
Is that built from MySQL or MoriaDB.  I'm suspecting MySQL.

**Comment by server24** [comment]
The change came from MySQL (they are no longer offering detailed/split up patches AFAIK).

But the problem is that this deprecation sends messages to stderr and this was marked as a MINOR package update in Ubuntu.

**Comment by TheWitness** [comment]
Resolved this one.

**Comment by TheWitness** [comment]
There is lot's of discussion about 'why' this was done in a minor release with little or no explanation of what customers 'should' do to accommodate for the change.  Not a good look for Oracle.
