### ISSUE TITLE
Support for SNMP noAuthNoPriv security level

### ISSUE THREAD

**Issue by dr4Ke** [Cacti/spine#32]
It's basically the same as v2c except that a context can be specified.

**Comment by cigamit** [comment]
Please test with the latest version of spine.  Example would be to run:

`./spine -R -f host_id -l host_id -S -V 3`

That will poll the host_id and not write the output to the database.  Close if resolved.  Otherwise, run the same command at "-V 5" and upload the results.

**Comment by cigamit** [comment]
I have confirmed that this is working.  In order to enable this in Cacti, you must update:

* lib/api_device.php
* include/global_arrays.php
* lib/snmp.php

From the develop branch.  You should also be running Cacti 1.1.30 before doing so too.
