### ISSUE TITLE
Poller may report the wrong number of devices polled

### ISSUE THREAD

**Issue by xmacan** [Cacti/spine#323]
Spine from actual 1.2 branch, run for one device (ping only device in my case):
spine --hostlist=261 -V=5

returns 
....
SPINE: Poller[1] PID[46998] PT[34376830976] Time: 0.5519 s, Threads: 20, **Devices: 2**

**Comment by TheWitness** [comment]
This is by design.  I guess we should fix the design.  Let me think about it.

**Comment by TheWitness** [comment]
This is resolved.  Please test.

**Comment by netniV** [comment]
Was this applied to 1.3.x?

**Comment by TheWitness** [comment]
@netniV, I will have one large merge closer to the 1.2.26 release.  Right now `develop` is pretty far behind.

**Comment by netniV** [comment]
Just need to be careful not to undo some of the develop work when we do.
