### ISSUE TITLE
Allow users to override the threads setting at the command line

### ISSUE THREAD

**Issue by TheWitness** [Cacti/spine#329]
**Is your feature request related to a problem? Please describe.**

In testing spine, it would be much easier for users to be able to specify the treads at the command line to determine how it impacts performance.

**Describe the solution you'd like**

Add the `-t X` or `--threads=X` options.

**Additional context**

Just for testing and unique uses of the new --ping option.

**Comment by netniV** [comment]
Was this applied to 1.3.x?
