### ISSUE TITLE
Spine does not honor the number of threads defined in the cacti GUI

### ISSUE THREAD

**Issue by eriksejr** [Cacti/spine#333]
**Describe the bug**
Spine does not honor the number of threads defined in the cacti GUI if the number of threads is not passed in on the command line, nor defined in spine.conf

The reason for this is in util.c and spine.h, where spine .h contains the following:

```
#define DEFAULT_THREADS 5
```

When spine starts in spine.c you set the value of set.threads=1, but then further down in the code call config_defaults(); from util.c which overwrites this value with the value from spine.h above.

```
/*! \fn void config_defaults(void)
 *  \brief populates the global configuration structure with default spine.conf file settings
 *  \param *set global runtime parameters
 *
 */
void config_defaults() {
        set.threads = DEFAULT_THREADS;
...
```

When you go to retrieve the value from the database in util.c you reach this conditional:

```
        /* get Cacti defined max threads override spine.conf */
        if (set.threads == 1) {
                if ((res = getpsetting(&mysql, mode, "threads")) != 0) {
                        set.threads = atoi(res);
                        free((char *)res);
                        if (set.threads > MAX_THREADS) {
                                set.threads = MAX_THREADS;
                        }
                }
        }
```

Due to the setting of set.threads earlier to the value of 5, this conditional can never be true and thus the user configured thread value for the poller is never retrieved from the database.

**To Reproduce**
Simply install spine 1.2.25 and specify the number of threads in the cacti GUI and nowhere else.

**Expected behavior**
The number of threads specified in the GUI/Database should be honored.

**Server (please complete the following information):**
 - OS: FreeBSD
 - Version 14.0

**Compiling (please complete the following information):**

 - compiler: FreeBSD clang version 16.0.6 (https://github.com/llvm/llvm-project.git llvmorg-16.0.6-0-g7cbf1a259152)
 - autoconf: autoconf (GNU Autoconf) 2.71
 - source: release 1.2.25 tarball

**Comment by eriksejr** [comment]
Note I didn't create a PR here because I'm not sure what the intent of this was. Do you want the default number of threads to be 5 or 1? Once decided it's a pretty easy fix.

**Comment by TheWitness** [comment]
Did you set the threads setting under Data Collectors or Settings?

**Comment by eriksejr** [comment]
Data Collectors, I know the settings one has been obsolete for a while. The database contains the correct value, only spine does not retrieve it:

```
cactiuser@localhost [cacti]> select name,threads from poller;
+-------------+---------+
| name        | threads |
+-------------+---------+
| Main Poller |      32 |
| YK Poller   |       2 |
+-------------+---------+
2 rows in set (0.000 sec)
```

Despite these values, spine on the main poller was running with 5 threads and I spent several hours wondering where it was getting that from. After tracing though the code as per above I found it in spine.h. I set DEFAULT_THREADS in spine.h to 1 and now spine correctly runs with 32 threads.

**Comment by TheWitness** [comment]
Yea, I just confirmed.  It'll take me a while to commit the fix. Later tonight. Thanks!

**Comment by TheWitness** [comment]
Okay, test out with the latest 1.2.x.

**Comment by eriksejr** [comment]
Thanks, I'm running it now and so far so good. I might do a fork and PR on some compiler warning fixes when I build under FreeBSD 14 for you. They are all minor but it's nice to have a clean build. I'm just testing the build I have over the weekend.

**Comment by TheWitness** [comment]
Would definitely be appreciated.
