### ISSUE TITLE
Fix Clang 16 compilation warnings under FreeBSD 14

### ISSUE THREAD

**Issue by eriksejr** [Cacti/spine#338]
These are just some compiler warnings generated under FreeBSD 14. These are all minor issues, mostly fixed with type cast.

#334 #335 #336 #337 

Note that I also compiled on Fedora 39 with these patches and had no warnings from GCC 13.2.1 either.

**Comment by TheWitness** [comment]
Feel free to log a pull request.

**Comment by eriksejr** [comment]
@TheWitness I don't think there's a need, you already committed all these changes?

**Comment by TheWitness** [comment]
Okay, cool.  Closing then.
