### ISSUE TITLE
configure should check for libsnmp-dev

### ISSUE THREAD

**Issue by eschoeller** [Cacti/spine#34]
I make it through a ./configure OK but during compile:

<pre>
gcc -DHAVE_CONFIG_H -I. -I./config     -I/usr/include/mysql -g -O2 -MT sql.o -MD -MP -MF .deps/sql.Tpo -c -o sql.o sql.c
In file included from sql.c:34:0:
common.h:134:38: fatal error: net-snmp/net-snmp-config.h: No such file or directory
 #include <net-snmp/net-snmp-config.h>
                                      ^
compilation terminated.
</pre>

<pre>
# apt-get install libsnmp-dev
The following NEW packages will be installed:
  libpci-dev libsensors4-dev libsnmp-dev libudev-dev libwrap0-dev
</pre>

Then make gets a bit further.

**Comment by eschoeller** [comment]
Configure should also check for help2man

**Comment by cigamit** [comment]
Resolved.
