### ISSUE TITLE
[1.3 QA] spine develop SQL Error with latest cacti develop

### ISSUE THREAD

**Issue by interceptor** [Cacti/spine#341]
**Describe the bug**
Running: ./spine --readonly --stdout --verbosity 5 against the latest cacti schema results in:

ERROR: The Query Was:'SELECT SQL_NO_CACHE id, device_threads, picount, picount/device_threads AS tppi FROM host LEFT JOIN (SELECT host_id, COUNT(*) AS picount FROM poller_item GROUP BY host_id) AS pi ON host.id = pi.host_id WHERE disabled = '' AND h.id BETWEEN 1 AND 1 AND h.poller_id=1 ORDER BY h.polling_time DESC'

**To Reproduce**
1. install Cacti from git clone https://github.com/Cacti/cacti.git current revision 64b395f16edb01d5f692e6760c858d3f6bbd4622
2. Execute DB update: sudo php -q cli/upgrade_database.php --forcever=1.2.22 --debug

**Expected behavior**
spine does not throw exceptions when poller is run

**Server (please complete the following information):**
 - OS: Ubuntu 20.22

This issue did not occur with spine revision 09e5a8c3c2ffe51a92b03d9f3725c3149ad2abf9

**Comment by interceptor** [comment]
Problem was likely introduced with this commit here: https://github.com/Cacti/spine/commit/a782364e136d8c94f274203daf20eaacc6e632e5

**Comment by TheWitness** [comment]
What is the SQL Error number?

**Comment by interceptor** [comment]
@TheWitness FATAL: Database Error:'1054', Message:'Unknown column 'h.poller_id' in 'where clause''

**Comment by TheWitness** [comment]
Okay.  Darn it.

**Comment by TheWitness** [comment]
Looks like it's only develop thankfully.

**Comment by TheWitness** [comment]
All fixed now.
