### ISSUE TITLE
SPINE: Poller[Main Poller] PID[p id] PT[pt number] Device[Device Name] Hostname[IP Address] ERROR: HOST EVENT: Device is DOWN Message: ICMP: Ping timed out

### ISSUE THREAD

**Issue by MSS970** [Cacti/spine#342]
**Describe the bug**
Spine Poller reports devices as down however, the devices are found UP by attempting to check the status of the devices in CACTI (click on management -> devices -> click on any device, the Ping Results is successful.

CACTI log shows:

SPINE: Poller[Main Poller] PID[p id] PT[pt number] Device[Device Name] Hostname[IP Address] ERROR: HOST EVENT: Device is DOWN Message: ICMP: Ping timed out.

**To Reproduce**
1. Install CACTI Dev (1.3)
2. Install Spine Dev (1.3)
3. Login to CACTI
5. Click on Logs
6. See error

**Expected behavior**
It is expected to see no errors from spine poller.

**Server (please complete the following information):**
 - OS: [Windows 2019]
 - Version [e.g. 2019]

- CACT version 1.3
- Spine version 1.3

**Comment by MSS970** [comment]
Hi TheWitness,
Please can you support on this issue. 
Much appreciated. 
Regards,

**Comment by MSS970** [comment]
I am closing this issue as I have submitted the same in CACTI issues.

**Comment by TheWitness** [comment]
Here is the answer

https://learn.microsoft.com/en-us/windows/win32/winsock/tcp-ip-raw-sockets-2
