### ISSUE TITLE
SNMP: Error DES is no longer supported on this system

### ISSUE THREAD

**Issue by tamanullah** [Cacti/spine#354]
We have recently migrated our Cacti to RHEL9. Everything works normal except for the devices using DES. SNMP fails for such devices and Poller keeps sending logs 'SPINE: Poller[Main Poller] SNMP: Error DES is no longer supported on this system.
Another error we get is when we open device to edit, it reports '500 Internal Server error'. Snippet of error is also attached.
<img width="254" alt="Screenshot 2024-08-05 095127" src="https://github.com/user-attachments/assets/375281b3-1243-4e0a-a554-cc8244b67816">
 

OS-Release: RHEL 9
Cacti: 1.2.27
Spine: 1.2.27

**Comment by TheWitness** [comment]
Net-SNMP Deprecated DES.  Go to the command line and see if the SNMP installed by RedHat still includes the DES option.  I suspect it doesn't. 

The way to work around this is by compiling Net-SNMP yourself with the DES flag enabled.  Another option would be to compile on an older system and bring the binary and shared libraries over from that system.

**Comment by TheWitness** [comment]
Best to open a ticket with RedHat.

**Comment by tamanullah** [comment]
Thank You. That helps a lot.

**Comment by TheWitness** [comment]
You're welcome.
