### ISSUE TITLE
spine_log() should obey cacti_log() date/time formatting rules

### ISSUE THREAD

**Issue by netniV** [Cacti/spine#39]
When logging with spine_log() the cacti.log file becomes inconsistent in its date/time formatting.  The reason is that the spine_log() function currently formats the date/time using a hard coded hyphen (-) separator rather than using the format selected within cacti's settings.

This should be changed to obey the same rules of formatting that the cacti_log() function by creating a spine version of cacti's date_time_format() in lib/functions.php which is defined by the settings table.

**Comment by cigamit** [comment]
This was resolved in 1.1.30.  Marking it for release 1.1.31 though.
