### ISSUE TITLE
Problem with large uptime in poller.c snmp_sysUpTimeInstance

### ISSUE THREAD

**Issue by pautiina** [Cacti/spine#4]
When the uptime is very large, in my case uptime = 2560814903, spine returns snmp_sysUpTimeInstance with minus, of course it is not inserted into the database, and Cacti is not shown uptime.
Log from DEBUG:
`2017-01-25 23:48:00 - SPINE: Poller[1] ERROR: SQL Failed! Error:'1264', Message:'Out of range value for column 'snmp_sysUpTimeInstance' at row 1', SQL Fragment:'UPDATE host SET status='3', status_event_count='0', status_fail_date='2017-01-12 03:07:00', status_rec_date='2017-01-12 03:16:00', status_last_error='Host did not respond to SNMP, ICMP: Ping timed out', min_time='0.203380', max_time='5658.534530', cur_time='0.413535', avg_time='1.905199', total_polls='2105441', failed_polls='2658', availability='99.8738', snmp_sysDescr='FreeBSD gate2.isp.kh.ua 10.3-PRERELEASE FreeBSD 10.3-PRERELEASE #1 r297151: Mon Mar 21 22:13:50 EET 2016     root@gate2.isp.kh.ua:/usr/obj/usr/src/sys/GATE2 amd64',  snmp_sysObjectID='NET-SNMP-MIB::netSnmpAgentOIDs.8', snmp_sysUpTimeInstance='-1733702469',  snmp_sysContact='NOC, +38 (057) 7076704, <noc@kharkiv.net>', snmp_sysName='gate2.isp.kh.ua', snmp_sysLocation='AC \\\"CIT Kharkiv Online\\\", apt 102, Kharkiv, Ukraine, 61002' WHERE id='20''
2017-01-25 23:48:00 - SPINE: Poller[1] Device[20] TH[1] Recache DataQuery[1] OID: .1.3.6.1.2.1.1.3.0, output: 2561264827
2017-01-25 23:48:00 - SPINE: Poller[1] Device[20] TH[1] Recache DataQuery[8] OID: .1.3.6.1.2.1.1.3.0, output: 2561264827
2017-01-25 23:48:00 - SPINE: Poller[1] Device[20] TH[1] Recache DataQuery[9] OID: .1.3.6.1.2.1.1.3.0, output: 2561264827
2017-01-25 23:48:00 - SPINE: Poller[1] Device[20] TH[1] Recache DataQuery[19] OID: .1.3.6.1.2.1.1.3.0, output: 2561264827
2017-01-25 23:48:00 - SPINE: Poller[1] Device[20] TH[1] Recache DataQuery[20] OID: .1.3.6.1.2.1.1.3.0, output: 2561264827
`
[poller_c.zip](https://github.com/Cacti/spine/files/731091/poller_c.zip)

I fix this:
`--- spine-develop/poller.c      2017-01-03 04:07:39.000000000 +0200
+++ spine-src-pautina/poller.c  2017-01-26 00:13:45.360251000 +0200
@@ -558,7 +558,7 @@
                                                        " status_rec_date='%s', status_last_error='%s', min_time='%f',"
                                                        " max_time='%f', cur_time='%f', avg_time='%f', total_polls='%i',"
                                                        " failed_polls='%i', availability='%.4f', snmp_sysDescr='%s', "
-                                                       " snmp_sysObjectID='%s', snmp_sysUpTimeInstance='%i', "
+                                                       " snmp_sysObjectID='%s', snmp_sysUpTimeInstance='%li', "
                                                        " snmp_sysContact='%s', snmp_sysName='%s', snmp_sysLocation='%s' "
                                                "WHERE id='%i'",
                                                host->status,
`

**Comment by cigamit** [comment]
This is resolved thanks.
