### ISSUE TITLE
Spine cause CPU usage up to 100%,issue #15

### ISSUE THREAD

**Issue by horizonlin** [Cacti/spine#41]
These day ,I try to debug the issue. I add one mutex  before mysql_init and mysql_real_connect . It work better than before.  I think the  issue cause by  mutli  thread operation  of  mysql.  
change  mysql setting   max_connection to 3000,  but  it  didn't  worked.
Any  idea?

ENV:  centos6.9    nginx   1.12.1   +  PHP  1.1   +mysql 5.7.17  +  spine  1.1.28

**Comment by horizonlin** [comment]
Recompile  with --with-reentrant  ,  it seems to work fine .    why mysql 5.7 should compile with --with-reentrant

**Comment by cigamit** [comment]
This is interesting.  Glad you pointed it out.  I just checked the API for MariaDB 10.1, and they are also providing the re-entrant library.  It had been removed from MySQL a few years ago.  But it looks like it has been re-introduced.  Can you please open an epel bug report as this can be handled in packaging?

**Comment by cigamit** [comment]
configure.ac will now search for re-entrant library if available automatically and use it automatically.
