### ISSUE TITLE
Spine 1.1.30 issue while making. libtool error.

### ISSUE THREAD

**Issue by sd3m0n** [Cacti/spine#43]
Log:

/bin/bash ./libtool  --tag=CC   --mode=link gcc  -I/usr/include/net-snmp -I/usr/include/net-snmp/.. -I/usr/include/mysql -g -O2  -L -lpthread -lssl -lm  -o spine sql.o spine.o util.o snmp.o locks.o poller.o nft_popen.o php.o ping.o keywords.o error.o  -lnetsnmp -lmysqlclient -lcrypto -lz -lpthread -lm
libtool:   **error: require no space between '-L' and '-lpthread'**
Makefile:466: recipe for target 'spine' failed
make: *** [spine] Error 1

It seemes like LDFLAGS var contains empty path for -L flag. All previous versions of spine on the same sys config ran without this issue.

**Comment by cigamit** [comment]
Please ensure that net-snmp-devel and mysql-devel or mariadb-devel are installed and try again.

**Comment by sd3m0n** [comment]
I'm using Ubuntu Server (16.04.3). This packages libsnmp-dev, libmysqlclient-dev are installed long ago. And before this situation everything was OK for about a year. There were no issues while making spine. I usually install every new version you release. And only now in 1.1.30 this problem appears...

**Comment by interduo** [comment]
On Debian 9.0 no problem with compilation.

**Comment by sd3m0n** [comment]
It seems the problem was solved after reinstalling some packages and recompiling spine. Still don't know why this problem even appeared... Thanx and sorry.
