### ISSUE TITLE
spine configure error

### ISSUE THREAD

**Issue by stalker37** [Cacti/spine#45]
On fresh git clone
./configure --with-mysql --with-snmp

checking whether we are using Linux Capabilities... no
configure: error: Cannot find SNMP header files under yes

| #define HAVE_STRTOLL 1
| /* end confdefs.h. */
| #include <sys/capability.h>
configure:13072: result: no
configure:13072: checking for sys/capability.h
configure:13072: result: no
configure:13082: checking whether we are using Linux Capabilities
configure:13151: result: no
configure:13270: error: Cannot find SNMP header files under yes

debian 9 (stretch)

dpkg -L libsnmp-dev | grep net-snmp-config.h
/usr/include/net-snmp/net-snmp-config.h

**Comment by cigamit** [comment]
Well that does not make any sense.  You need to update config.log please.

**Comment by cigamit** [comment]
You are calling ./configure incorrectly.  If you wish to use different paths, you would configure with something like

./configure --with-snmp=/opt/mylocationforsnmp --with-mysql=/opt/mylocationformysql

In your case, you should use NO options.
