### ISSUE TITLE
implicit declaration of function 'exit' 

### ISSUE THREAD

**Issue by stalker37** [Cacti/spine#46]
configure:13082: checking whether we are using Linux Capabilities
configure:13151: result: no
configure:13285: checking if Net-SNMP needs crypto support
configure:13298: gcc -c -I/usr/include/net-snmp// -I/usr/include/net-snmp///.. -I/usr/include/mysql -g -O2  conftest.c >&5
conftest.c: In function 'main':
conftest.c:60:1: warning: implicit declaration of function 'exit' [-Wimplicit-function-declaration]
 exit(NETSNMP_USE_OPENSSL != 1);
 ^~~~
conftest.c:60:1: warning: incompatible implicit declaration of built-in function 'exit'
conftest.c:60:1: note: include '<stdlib.h>' or provide a declaration of 'exit'

**Comment by cigamit** [comment]
Please note that these are not Cacti issues.  This is more of a make issue.
