### ISSUE TITLE
1.1.31 issue: functions.php: 4480 cacti_debug_backtrace

### ISSUE THREAD

**Issue by Izmenoff** [Cacti/spine#47]
After Spine updated 1.1.30 - 1.1.31

19-Jan-2018 08:29:26 - CMDPHP PHP ERROR NOTICE Backtrace: (/scripts/Cisco_WLC_Power_Level.php: 16 CactiErrorHandler)(/lib/functions.php: 4480 cacti_debug_backtrace)
--
19-Jan-2018 08:29:26 - ERROR PHP NOTICE: Undefined offset: 2 in file: /var/www/html/cacti/scripts/Cisco_WLC_Power_Level.php on line: 16
19-Jan-2018 08:29:26 - CMDPHP PHP ERROR NOTICE Backtrace: (/scripts/Cisco_WLC_Power_Level.php: 15 CactiErrorHandler)(/lib/functions.php: 4480 cacti_debug_backtrace)
19-Jan-2018 08:29:26 - ERROR PHP NOTICE: Undefined offset: 1 in file: /var/www/html/cacti/scripts/Cisco_WLC_Power_Level.php on line: 15
19-Jan-2018 08:29:26 - CMDPHP PHP ERROR NOTICE Backtrace: (/scripts/Cisco_WLC_Power_Level.php: 16 CactiErrorHandler)(/lib/functions.php: 4480 cacti_debug_backtrace)
19-Jan-2018 08:29:26 - ERROR PHP NOTICE: Undefined offset: 2 in file: /var/www/html/cacti/scripts/Cisco_WLC_Power_Level.php on line: 16
19-Jan-2018 08:29:26 - CMDPHP PHP ERROR NOTICE Backtrace: (/scripts/Cisco_WLC_Power_Level.php: 15 CactiErrorHandler)(/lib/functions.php: 4480 cacti_debug_backtrace)
19-Jan-2018 08:29:26 - ERROR PHP NOTICE: Undefined offset: 1 in file: /var/www/html/cacti/scripts/Cisco_WLC_Power_Level.php on line: 15
19-Jan-2018 08:29:26 - CMDPHP PHP ERROR NOTICE Backtrace: (/scripts/Cisco_WLC_Station_Policy.php: 18 CactiErrorHandler)(/lib/functions.php: 4480 cacti_debug_backtrace)
19-Jan-2018 08:29:26 - ERROR PHP NOTICE: Undefined offset: 3 in file: /var/www/html/cacti/scripts/Cisco_WLC_Station_Policy.php on line: 18
19-Jan-2018 08:29:26 - CMDPHP PHP ERROR NOTICE Backtrace: (/scripts/Cisco_WLC_Station_Policy.php: 17 CactiErrorHandler)(/lib/functions.php: 4480 cacti_debug_backtrace)
19-Jan-2018 08:29:26 - ERROR PHP NOTICE: Undefined offset: 2 in file: /var/www/html/cacti/scripts/Cisco_WLC_Station_Policy.php on line: 17
19-Jan-2018 08:29:26 - CMDPHP PHP ERROR NOTICE Backtrace: (/scripts/Cisco_WLC_Station_Policy.php: 16 CactiErrorHandler)(/lib/functions.php: 4480 cacti_debug_backtrace)
19-Jan-2018 08:29:26 - ERROR PHP NOTICE: Undefined offset: 1 in file: /var/www/html/cacti/scripts/Cisco_WLC_Station_Policy.php on line: 16

19-Jan-2018 09:31:03 - CMDPHP PHP ERROR NOTICE Backtrace: (/scripts/Cisco_WLC_Station_Policy.php: 18 CactiErrorHandler)(/lib/functions.php: 4480 cacti_debug_backtrace)
--
19-Jan-2018 09:31:03 - ERROR PHP NOTICE: Undefined offset: 3 in file: /var/www/html/cacti/scripts/Cisco_WLC_Station_Policy.php on line: 18
19-Jan-2018 09:31:03 - CMDPHP PHP ERROR NOTICE Backtrace: (/scripts/Cisco_WLC_Station_Policy.php: 17 CactiErrorHandler)(/lib/functions.php: 4480 cacti_debug_backtrace)
19-Jan-2018 09:31:03 - ERROR PHP NOTICE: Undefined offset: 2 in file: /var/www/html/cacti/scripts/Cisco_WLC_Station_Policy.php on line: 17
19-Jan-2018 09:31:03 - CMDPHP PHP ERROR NOTICE Backtrace: (/scripts/Cisco_WLC_Station_Policy.php: 16 CactiErrorHandler)(/lib/functions.php: 4480 cacti_debug_backtrace)
19-Jan-2018 09:31:03 - ERROR PHP NOTICE: Undefined offset: 1 in file: /var/www/html/cacti/scripts/Cisco_WLC_Station_Policy.php on line: 16
19-Jan-2018 09:31:03 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4518 cacti_debug_backtrace)
thrown in file: /var/www/html/cacti/scripts/ss_net_snmp_disk_bytes.php on line: 23
#1 {main}
#0 /var/www/html/cacti/script_server.php(221): ss_net_snmp_disk_bytes()
Stack trace:
19-Jan-2018 09:31:03 - ERROR PHP ERROR: Uncaught ArgumentCountError: Too few arguments to function ss_net_snmp_disk_bytes(), 0 passed in /var/www/html/cacti/script_server.php on line 221 and exactly 1 expected in /var/www/html/cacti/scripts/ss_net_snmp_disk_bytes.php:23

**Comment by Izmenoff** [comment]
resolved by itself ))

**Comment by cigamit** [comment]
These kind of issues really have nothing to do with spine.  It's really about the function and what is passed to it.
