### ISSUE TITLE
make in Debian 7: undefined reference to `clock_gettime'

### ISSUE THREAD

**Issue by rem-lex** [Cacti/spine#50]
```
gcc  -I/usr/include/net-snmp -I/usr/include/net-snmp/.. -I/usr/include -g -O2  -L/usr/lib -L/usr/lib -lpthread -lssl -lm  -o spine sql.o spine.o util.o snmp.o locks.o poller.o nft_popen.o php.o ping.o keywords.o error.o  -lnetsnmp -lmysqlclient_r -lcrypto -lz -lpthread -lm
/usr/lib/libmysqlclient_r.a(my_getsystime.c.o): In function `my_getsystime':
(.text+0x29): undefined reference to `clock_gettime'
collect2: error: ld returned 1 exit status
make: *** [spine] Ошибка 1

```
./spine/config.status @643 :
`S["CFLAGS"]="-I/usr/include/net-snmp -I/usr/include/net-snmp/.. -I/usr/include -g -O2"`
may be
`S["CFLAGS"]="-lrt -I/usr/include/net-snmp -I/usr/include/net-snmp/.. -I/usr/include -g -O2"`

**Comment by cigamit** [comment]
Smells like a MariaDB/MySQL issue.  What version of those libraries?

**Comment by rem-lex** [comment]
# dpkg -l | grep mysql | grep dev
ii  libmysqlclient-dev                 5.6.15-25.5-759.wheezy             i386         Percona Server database development files

**Comment by cigamit** [comment]
Seems to me that this was included in the core of gcc some time ago.  Something must be wrong on your debian install.  Have to figure out what test will bring in this library.

**Comment by cigamit** [comment]
Add the following to configure.ac

`AC_SEARCH_LIBS([clock_gettime], [rt pthread])`

Then run the following.

`autoreconf`
`./configure`
`make clean`
`make`

Is it fixed now?

**Comment by rem-lex** [comment]
yes, it fixed

**Comment by cigamit** [comment]
Merge complete.  Closing.
