### ISSUE TITLE
poller time increase

### ISSUE THREAD

**Issue by dsclassen** [Cacti/spine#52]
Not sure it really matters much as it seems the develop branch is considered unstable, but ab99de9 resulted in ~45 second poll times. I switched to 1fc1a83 and now my poll times are back to 5 seconds.

**Comment by netniV** [comment]
Thanks for the report.  When you updated Spine to 1.2, did you also update Cacti? When you reverted back was that just Spine or both?

**Comment by dsclassen** [comment]
My cacti is at 1.2.0
I updated cacti first, then noticed that spine had also been updated and I installed the latest commit from the develop branch. Once I observed the abnormal polling times I reverted spine only. cacti is still at 1.2.0

**Comment by cigamit** [comment]
This is likely due to thread settings being moved to the Data Collector table.

**Comment by netniV** [comment]
I believe that the core #1674 issue is the real reason for the problem.  As such, I am going to close this issue now.  If you believe that this is in error please let me know why.
