### ISSUE TITLE
Define connection type for local SQL-connection

### ISSUE THREAD

**Issue by Xake** [Cacti/spine#56]
If the SQL-machine is running remotely spine uses TCP, but if it runs locally cacti uses socket-connection.
I need for our setup to be able to run spine against a local TCP-port for sql, and not try to connect to the unix_socket. 
Could you please add this as an option to spine.conf?

**Comment by netniV** [comment]
The section of code within sql.c is:

```sql
if ((hostname = strdup(set.dbhost)) == NULL) {
        die("FATAL: malloc(): strdup() failed"
}
if (stat(hostname, &socket_stat) == 0) {
        if (socket_stat.st_mode & S_IFSOCK) {
                socket = strdup (set.dbhost);
                hostname = NULL;
        }
}else if ((socket = strstr(hostname,":"))) {
        *socket++ = 0x0;
}
```
This means that a socket variable is always populated.  However, you could try using "127.0.0.1" as the connection vector rather than "localhost" as a name.

**Comment by Xake** [comment]
Interesting, that seems to have done it. I was afraid it needed some logic with mysql_options. My take was to use the hostname for local host, however that spine tried to use as a socket.
Thank you!

**Comment by netniV** [comment]
I think the reason is that the hostname is a name that can be a socket but an IP must be a network connection. In truth it gets a bit confusing for me because a network connection is often called a socket too!
