### ISSUE TITLE
 Error on poller.c: escaping string from snmp_sysLocation

### ISSUE THREAD

**Issue by arno-st** [Cacti/spine#58]
The line 567 in poller.c has to be corrected, because if in snmp_sysLocation you have a ' (single coma) it' breaking the upate.
like that:
Compiled Fri 27-Jul-12 04:45 by prod_rel_team', snmp_sysObjectID='SNMPv2-SMI::enterprises.9.1.1378', snmp_sysUpTimeInstance='269059650', snmp_sysContact='SOI - Telecom', snmp_sysName='RA-RBOR-81.recolte.lausanne.ch', snmp_sysLocation='Suisse;Chateau d'Oex;Les Bornels;0;Prise d'eau' WHERE id='33344''2018/06/22 11:58:03 - SPINE: Poller[Main Poller] Device[33344] Device[ra-rbor-81] TH[1] Total Time: 1.1 Seconds

2018/06/22 11:58:03 - SPINE: Poller[Main Poller] ERROR: SQL Failed! Error:'1064', Message:'You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'Oex;Les Bornels;0;Prise d'eau' WHERE id='33344'' at line 1', SQL Fragment:'UPDATE host SET status='3', status_event_count='1', status_fail_date='2018-06-22 11:58', status_rec_date='0000-00-00 00:00:00', status_last_error='Device responded to SNMP, ICMP: Ping timed out', min_time='9.999990', max_time='690.662030', cur_time='174.910430', avg_time='175.596740', total_polls='667', failed_polls='1', availability='99.8501', snmp_sysDescr='Cisco IOS Software, C800 Software (C800-UNIVERSALK9-M), Version 15.2(4)M1, RELEASE SOFTWARE (fc1)

Probably calling a db_escape will solve the issue

**Comment by netniV** [comment]
db_escape() is actually called.  it's called as part of get_system_information() which performs an snmp_get() to retrieve the sysname information and then escapes the result into the sysname variable.

```c
poll_result = snmp_get(host, ".1.3.6.1.2.1.1.5.0");
if (poll_result) {
        db_escape(mysql, host->snmp_sysName, poll_result);
}
```
This then is used in building the SQL string:
```
snprintf(update_sql, BUFSIZE, "UPDATE host "
        "SET status='%i', status_event_count='%i', status_fail_date='%s',"
                " status_rec_date='%s', status_last_error='%s', min_time='%f',"
                " max_time='%f', cur_time='%f', avg_time='%f', total_polls='%i',"
                " failed_polls='%i', availability='%.4f', snmp_sysDescr='%s', "
                " snmp_sysObjectID='%s', snmp_sysUpTimeInstance='%u', "
                " snmp_sysContact='%s', snmp_sysName='%s', snmp_sysLocation='%s' "
        "WHERE id='%i'",
        host->status,
        host->status_event_count,
        host->status_fail_date,
        host->status_rec_date,
        host->status_last_error,
        host->min_time,
        host->max_time,
        host->cur_time,
        host->avg_time,
        host->total_polls,
        host->failed_polls,
        host->availability,
        host->snmp_sysDescr,
        host->snmp_sysObjectID,
        host->snmp_sysUpTimeInstance,
        host->snmp_sysContact,
        host->snmp_sysName,
        host->snmp_sysLocation,
        host->id);
```

What I am starting to suspect, is that the string was already in the DB, read but not escaped when put back in again but I'd have to run through some tests to be sure.

**Comment by arno-st** [comment]
Yes your right it's stored in the DB with the ' (single quote), and as you said it's has to be escaped again on read

**Comment by cigamit** [comment]
This is resolve now.

**Comment by cigamit** [comment]
poller.c line 1760 and ignore_sysinfo are your clues.

**Comment by netniV** [comment]
Basically, only doing an update if you've actually asked for info.

**Comment by browniebraun** [comment]
First off, I thought the same having real trouble on my new lab servers, but the issues occurs due the very long system description being returned by our Cisco devices. Escaping itself is working faultlessly. Changing the buffer size for the update query from BUFSIZE to BIG_BUFSIZE does the trick.

Regards
-Andi

Yep, I'm alive :)

**Comment by netniV** [comment]
Glad to hear your alive, and good catch on the length. I hadn’t considered that it may be truncated.

**Comment by browniebraun** [comment]
Fixed
