### ISSUE TITLE
Spine accepts arbitrary polling modes

### ISSUE THREAD

**Issue by shastah** [Cacti/spine#6]
The code to parse `--mode` only checks for "online" and "offline", everything else sets it to recovery mode, even if you run it with something stupid
```
$ spine --mode=aakjndaiusdh19hd3
```
or less stupid, because someone made a typo:
```
$ spine --mode=oneline
```

How about this patch?
```
--- a/spine.c	2017-02-14 23:52:04.870894363 +0100
+++ b/spine.c	2017-02-14 23:56:45.406365574 +0100
@@ -345,9 +345,13 @@
 				set.mode = REMOTE_OFFLINE;
 			} 
 
-			else {
+			else if (STRIMATCH(getarg(opt, &argv), "recovery")) {
 				set.mode = REMOTE_RECOVERY;
 			}
+
+			else {
+				die("ERROR: invalid polling mode '%s' specified", opt);
+			}
 		}
 
 		else if (STRMATCH(arg, "-H") ||
```
In case exit is not desired, even when non-supported mode is given, then the fallback should be to `online`, because that's what the manual says is the default.

**Comment by ronytomen** [comment]
Good call, it will be integrated for 1.0.3 release.
