### ISSUE TITLE
make error for spine 1.1.27

### ISSUE THREAD

**Issue by marshallgregor** [Cacti/spine#62]
am trying to compile spine 1.1.27 and getting error below on sles11. any idea what could be the cause?

/usr/bin/help2man --output=spine.1 --name='Data Collector for Cacti' --no-info --version-option='--version' ./spine
sh: line 1: 37327 Segmentation fault      ./spine --help 2> /dev/null
help2man: can't get `--help' info from ./spine
Try `--no-discard-stderr' if option outputs to stderr
make: *** [spine.1] Error 139

**Comment by browniebraun** [comment]
Such an error will also occur if a custom library, like MySQL, has been compiled before, but is not available as shared library through the missing configuration of an environment variable for example.
You can check that with "ldd ./bin/spine".

**Comment by cigamit** [comment]
Looks like spine is segfaulting.  You should download the latest develop version.  It is still compatible.
