### ISSUE TITLE
Remote poller db settings not translating correctly

### ISSUE THREAD

**Issue by scline** [Cacti/spine#7]
It appears RDB variables in spine.conf is not being sent to spine correctly. The username/password and db name are not correct. Unless this is by design where the master database and remote poller database needs to live on the same host using the same database credentials.

An outline of the issue can be viewed at http://forums.cacti.net/viewtopic.php?f=2&t=56978 - is this a bug or by design?

**Comment by scline** [comment]
I *think* the fix to the above issue lies in sql.c line 280 needing to be changed from
`connect_error = mysql_real_connect(mysql, hostname, set.rdbuser, set.rdbpass, database, set.rdbport, socket, 0);`
to
`connect_error = mysql_real_connect(mysql, hostname, set.rdbuser, set.rdbpass, set.rdbdb, set.rdbport, socket, 0);`

**Comment by scline** [comment]
https://github.com/Cacti/spine/pull/9 created for the fix

**Comment by cigamit** [comment]
Resolved, thanks!
