### ISSUE TITLE
Spine check for setgid bit

### ISSUE THREAD

**Issue by eschoeller** [Cacti/spine#77]
As referenced over in Cacti issue #2098 I ran into problems with perl scripts throwing Insecure Dependency messages on debian boxes after running 'chmod +s spine'. Switching this to 'chmod u+s spine' resolved the issue on the debian systems. The RHEL system never complained. Hopefully it is possible to add a warning message for spine (similar to the message about needing +s for ICMP ping) warning the user that the setgid bit is set and should be removed. Also reference https://forums.cacti.net/viewtopic.php?f=2&t=41534

**Comment by cigamit** [comment]
Updated readme and util.c

**Comment by cigamit** [comment]
Updated readme and util.c
