### ISSUE TITLE
spine does not insert start_time into poller_time on main data collector database

### ISSUE THREAD

**Issue by eschoeller** [Cacti/spine#78]
From everything I've seen, it appears that it should. Or, it's the other way around and this is a Cacti problem (poller.php should read the poller_time table from the local database, not the remote database).

**Comment by netniV** [comment]
Spine is inserting this into the local DB under 1.2 as all operations relating to the poller are local now

```

**Comment by netniV** [comment]
This may conflict with CMD.PHP which is using the `$poller_db_cnn_id` which itself is set from `$remote_db_cnn_id`.  That is set in `include/global.php` by setting the rdatabase_* variables and having the poller id greater than 1.  That connection should be the main poller.

**Comment by cigamit** [comment]
Since 1.2, spine should insert into the poller_time table of the remote database, unless it's in offline operation mode.  So, 1.1.x and 1.2.x are incompatible.
