### ISSUE TITLE
Missing sh.exe does not return meaningful error

### ISSUE THREAD

**Issue by dschall** [Cacti/spine#8]
Platform: Windows (Cygwin)
Version: 1.0.4

Description:
When sh.exe is missing from PATH / inaccessible, spine silently fails external program calls.

**Comment by cigamit** [comment]
Looks like a packaging issue.  Sending note to packager.

**Comment by BSOD2600** [comment]
@dschall what external program calls are failing?  
how do you repro the issue?
Is sh.exe still in the same folder as spine.exe?
do you already have cygwin installed?

**Comment by dschall** [comment]
@BSOD2600:
Cygwin is still installed, not in the PATH though.
sh.exe is not in the same folder as spine.exe.
Repro:
Run spine.exe without sh.exe available (not in the same folder / not in PATH).
spine.exe runs and does not complain about missing sh.exe, but script calls all fail.

**Comment by BSOD2600** [comment]
Did you use the Cacti Windows Installer or compile spine yourself?  
What cygwin version?

**Comment by cigamit** [comment]
Closing due to lack of response.
