### ISSUE TITLE
Compilation issue on CentOS 7

### ISSUE THREAD

**Issue by jackouille-ch** [Cacti/spine#81]
[root@cacti-dev cacti-spine-1.2.0]# ./configure
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gawk... (cached) gawk
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/tmp/cacti-spine-1.2.0':
configure: error: C compiler cannot create executables
See `config.log' for more details

[root@cacti-dev cacti-spine-1.2.0]# cat config.log
This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by Spine Poller configure 1.2.0, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ ./configure

## --------- ##

hostname = cacti-dev.local
uname -m = x86_64
uname -r = 3.10.0-957.1.3.el7.x86_64
uname -s = Linux
uname -v = #1 SMP Thu Nov 29 14:49:43 UTC 2018

/usr/bin/uname -p = x86_64
/bin/uname -X     = unknown

/bin/arch              = x86_64
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /usr/local/sbin
PATH: /usr/local/bin
PATH: /usr/sbin
PATH: /usr/bin
PATH: /root/bin

## ----------- ##

configure:2339: checking build system type
configure:2353: result: x86_64-pc-linux-gnu
configure:2373: checking host system type
configure:2386: result: x86_64-pc-linux-gnu
configure:2431: checking for a BSD-compatible install
configure:2499: result: /usr/bin/install -c
configure:2510: checking whether build environment is sane
configure:2565: result: yes
configure:2716: checking for a thread-safe mkdir -p
configure:2755: result: /usr/bin/mkdir -p
configure:2762: checking for gawk
configure:2778: found /usr/bin/gawk
configure:2789: result: gawk
configure:2800: checking whether make sets $(MAKE)
configure:2822: result: yes
configure:2851: checking whether make supports nested variables
configure:2868: result: yes
configure:3068: checking for gawk
configure:3095: result: gawk
configure:3154: checking for gcc
configure:3170: found /usr/bin/gcc
configure:3181: result: gcc
configure:3410: checking for C compiler version
configure:3419: gcc --version >&5
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:3430: $? = 0
configure:3419: gcc -v >&5
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)
configure:3430: $? = 0
configure:3419: gcc -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:3430: $? = 4
configure:3419: gcc -qversion >&5
gcc: error: unrecognized command line option '-qversion'
gcc: fatal error: no input files
compilation terminated.
configure:3430: $? = 4
configure:3450: checking whether the C compiler works
configure:3472: gcc   -lpthread -lssl -lm  conftest.c  >&5
/usr/bin/ld: cannot find -lssl
collect2: error: ld returned 1 exit status
configure:3476: $? = 1
configure:3514: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "Spine Poller"
| #define PACKAGE_TARNAME "spine-poller"
| #define PACKAGE_VERSION "1.2.0"
| #define PACKAGE_STRING "Spine Poller 1.2.0"
| #define PACKAGE_BUGREPORT "http://www.cacti.net/issues.php"
| #define PACKAGE_URL ""
| #define PACKAGE "spine-poller"
| #define VERSION "1.2.0"
| /* end confdefs.h.  */
|
| int
| main ()
| {
|
|   ;
|   return 0;
| }
configure:3519: error: in `/tmp/cacti-spine-1.2.0':
configure:3521: error: C compiler cannot create executables
See `config.log' for more details

## ---------------- ##

ac_cv_build=x86_64-pc-linux-gnu
ac_cv_env_CC_set=
ac_cv_env_CC_value=
ac_cv_env_CFLAGS_set=
ac_cv_env_CFLAGS_value=
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_LDFLAGS_set=
ac_cv_env_LDFLAGS_value=
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_LT_SYS_LIBRARY_PATH_set=
ac_cv_env_LT_SYS_LIBRARY_PATH_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_host=x86_64-pc-linux-gnu
ac_cv_path_install='/usr/bin/install -c'
ac_cv_path_mkdir=/usr/bin/mkdir
ac_cv_prog_AWK=gawk
ac_cv_prog_ac_ct_CC=gcc
ac_cv_prog_make_make_set=yes
am_cv_make_support_nested_variables=yes

## ----------------- ##

ACLOCAL='${SHELL} /tmp/cacti-spine-1.2.0/config/missing aclocal-1.15'
AMDEPBACKSLASH=''
AMDEP_FALSE=''
AMDEP_TRUE=''
AMTAR='$${TAR-tar}'
AM_BACKSLASH='\'
AM_DEFAULT_V='$(AM_DEFAULT_VERBOSITY)'
AM_DEFAULT_VERBOSITY='1'
AM_V='$(V)'
AR=''
AUTOCONF='${SHELL} /tmp/cacti-spine-1.2.0/config/missing autoconf'
AUTOHEADER='${SHELL} /tmp/cacti-spine-1.2.0/config/missing autoheader'
AUTOMAKE='${SHELL} /tmp/cacti-spine-1.2.0/config/missing automake-1.15'
AWK='gawk'
CC='gcc'
CCDEPMODE=''
CFLAGS=''
CPP=''
CPPFLAGS=''
CYGPATH_W='echo'
DEFS=''
DEPDIR=''
DLLTOOL=''
DSYMUTIL=''
DUMPBIN=''
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EGREP=''
EXEEXT=''
FGREP=''
GREP=''
HAVE_HELP2MAN_FALSE=''
HAVE_HELP2MAN_TRUE=''
HELP2MAN=''
INSTALL_DATA='${INSTALL} -m 644'
INSTALL_PROGRAM='${INSTALL}'
INSTALL_SCRIPT='${INSTALL}'
INSTALL_STRIP_PROGRAM='$(install_sh) -c -s'
LD=''
LDFLAGS='-lpthread -lssl -lm '
LIBOBJS=''
LIBS=''
LIBTOOL=''
LIPO=''
LN_S=''
LTLIBOBJS=''
LT_SYS_LIBRARY_PATH=''
MAKEINFO='${SHELL} /tmp/cacti-spine-1.2.0/config/missing makeinfo'
MANIFEST_TOOL=''
MKDIR_P='/usr/bin/mkdir -p'
NM=''
NMEDIT=''
OBJDUMP=''
OBJEXT=''
OTOOL64=''
OTOOL=''
PACKAGE='spine-poller'
PACKAGE_BUGREPORT='http://www.cacti.net/issues.php'
PACKAGE_NAME='Spine Poller'
PACKAGE_STRING='Spine Poller 1.2.0'
PACKAGE_TARNAME='spine-poller'
PACKAGE_URL=''
PACKAGE_VERSION='1.2.0'
PATH_SEPARATOR=':'
RANLIB=''
SED=''
SET_MAKE=''
SHELL='/bin/sh'
STRIP=''
VERSION='1.2.0'
ac_aux_dir='config'
ac_ct_AR=''
ac_ct_CC='gcc'
ac_ct_DUMPBIN=''
am__EXEEXT_FALSE=''
am__EXEEXT_TRUE=''
am__fastdepCC_FALSE=''
am__fastdepCC_TRUE=''
am__include=''
am__isrc=''
am__leading_dot='.'
am__nodep=''
am__quote=''
am__tar='$${TAR-tar} chof - "$$tardir"'
am__untar='$${TAR-tar} xf -'
bindir='${exec_prefix}/bin'
build='x86_64-pc-linux-gnu'
build_alias=''
build_cpu='x86_64'
build_os='linux-gnu'
build_vendor='pc'
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='NONE'
host='x86_64-pc-linux-gnu'
host_alias=''
host_cpu='x86_64'
host_os='linux-gnu'
host_vendor='pc'
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
install_sh='${SHELL} /tmp/cacti-spine-1.2.0/config/install-sh'
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
mkdir_p='$(MKDIR_P)'
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='NONE'
program_transform_name='s,x,x,'
psdir='${docdir}'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
sysconfdir='${prefix}/etc'
target_alias=''

## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "Spine Poller"
#define PACKAGE_TARNAME "spine-poller"
#define PACKAGE_VERSION "1.2.0"
#define PACKAGE_STRING "Spine Poller 1.2.0"
#define PACKAGE_BUGREPORT "http://www.cacti.net/issues.php"
#define PACKAGE_URL ""
#define PACKAGE "spine-poller"
#define VERSION "1.2.0"

configure: exit 77

**Comment by cigamit** [comment]
You don't have a working compiler.  You need to install the development tools including gcc.  You might want to do something like:

`yum -y install gcc autoconf libtool make m4 net-snmp-devel mysql-devel`
