### ISSUE TITLE
the spine return ERROR 

### ISSUE THREAD

**Issue by pan781023** [Cacti/spine#83]
this is my scripts is working on command ,but my spine is say has error Empty result ,what can i do ?
i want make this script working on my cacti

thanks

`snmpwalk -c public -v 2c $1 .1.3.6.1.4.1.8072.1.3.2.3.1.1 |grep '"conn"'|awk -F'=' '{print $2}'|awk -F': ' '{print "conn:"$2}'
`

sudo -u cacti ./oracle_conn.sh 10.1.x.x
conn:1523

`2019/02/12 15:46:18 - SPINE: Poller[1] Device[241] DEBUG: The NIFTY POPEN returned the following File Descriptor 24
2019/02/12 15:46:18 - SPINE: Poller[1] Device[241] ERROR: Empty result [10.1.x.x]: '/bin/bash /var/www/html/cacti-1.2.1/scripts/oracle_conn.sh '10.1.x.x''
2019/02/12 15:46:18 - SPINE: Poller[1] WARNING: Invalid Response, Device[241] HT[1] DS[4979] SCRIPT: /bin/bash /var/www/html/cacti-1.2.1/scripts/oracle_conn.sh '10.1.x.x', output: U
2019/02/12 15:46:18 - SPINE: Poller[1] Device[241] HT[1] DS[4979] SCRIPT: /bin/bash /var/www/html/cacti-1.2.1/scripts/oracle_conn.sh '10.1.x.x', output: U
`

cacti version : 1.2.1

**Comment by netniV** [comment]
Have you defined this template to know that the output is parameterized with the name?

**Comment by cigamit** [comment]
This is not an issue.  If you configure using nifty popen, you binary needs to include the full path in the data source as for speed, there is no environment set which differs from the popen method, which initializes and environment.
