### ISSUE TITLE
ERROR: Problems parsing Multi SNMP OID!

### ISSUE THREAD

**Issue by sonduko** [Cacti/spine#84]
After upgrading spine to version 1.2.1 my clog is filling with many messages like this one:

2019/02/15 11:53:03 - SPINE: Poller[Main Poller] Device[xxx.xxx.xxx] ERROR: Problems parsing Multi SNMP OID! (oid: .1.3.6.1.2.1.2.2.1.16.), Set MAX_OIDS to 1 for this host to isolate bad OID

My host graphs stop recording data.

![graph_data](https://user-images.githubusercontent.com/37623218/52852874-1acc0600-311a-11e9-8146-c3884b23aade.PNG)

![technical_support](https://user-images.githubusercontent.com/37623218/52852988-6ed6ea80-311a-11e9-8844-cd102786a5cc.PNG)

Different hosts (Windows, Debian, Switches...) are affected. Any ideas?

**Comment by cigamit** [comment]
Update to the develop version, then re-index all your devices.

**Comment by cigamit** [comment]
This is a known Cacti issue related to 1.2.0 and 1.2.1.  It has been resolved in the Cacti repo.
