### ISSUE TITLE
Problem to compile spine 1.2.3 from cacti

### ISSUE THREAD

**Issue by Networms007** [Cacti/spine#90]
After start make stop the process with error code.

/usr/local/bin/help2man --output=spine.1 --name='Data Collector for Cacti' --no-info --version-option='--version' ./spine
Can't locate Locale/gettext.pm in @INC (you may need to install the Locale::gettext module) (@INC contains: /usr/local/lib/perl5/site_perl/mach/5.28 /usr/local/lib/perl5/site_perl /usr/local/lib/perl5/5.28/mach /usr/local/lib/perl5/5.28) at /usr/local/bin/help2man line 29.
BEGIN failed--compilation aborted at /usr/local/bin/help2man line 29.
*** Error code 2

Cacti is running on freebsd server version 11.2

**Comment by netniV** [comment]
Have you made sure to run the following:

````
pkg install unix2dos gcc autoconf automake libtool openssl-devel help2man net-snmp
./bootstrap
./configure --with-reentrant
make
make install
chown root:root /usr/local/spine/bin/spine
chmod +s /usr/local/spine/bin/spine
```

**Comment by Networms007** [comment]
I could not install openssl-devel -> see below

Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
pkg: No packages available to install matching 'openssl-devel' have been found in the repositories

**Comment by netniV** [comment]
try security/openssl-devel then.  I know there is security/openssl

**Comment by Networms007** [comment]
So it was security/openssl not security/openssl-devel. I have install this pkg

but the same issue..
Can't locate Locale/gettext.pm in @INC (you may need to install the Locale::gettext module) (@INC contains: /usr/local/lib/perl5/site_perl/mach/5.28 /usr/local/lib/perl5/site_perl /usr/local/lib/perl5/5.28/mach /usr/local/lib/perl5/5.28) at /usr/local/bin/help2man line 29.
BEGIN failed--compilation aborted at /usr/local/bin/help2man line 29.
*** Error code 2

Stop.
make: stopped in /usr/src/spine

**Comment by Networms007** [comment]
pkg install unix2dos gcc autoconf automake libtool security/openssl help2man net-snmp **done**
./bootstrap **done**
./configure --with-reentrant **done**
make **stop with error**
make install **didnt start because error form make**

have some idea what i can do, for me looks like an error in the script

**Comment by netniV** [comment]
This appears to be a problem with a dependency of help2man wanting a perl function Locale:gettext

**Comment by cigamit** [comment]
Okay, this is not a real spine issue.  You may continue the discussion, but I will close this one.
