### ISSUE TITLE
Spine 1.2.3 is missing the configure script 

### ISSUE THREAD

**Issue by Lalbee99** [Cacti/spine#91]
**Describe the bug**
Spine 1.2.3 is missing the configure script 

**To Reproduce**
1. Go to spine on github 

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - OS: [e.g. CentOS 7]

**Compiling (please complete the following information):**

 - compiler: [e.g. clang or gcc 5.4.0]
 - autoconf: [e.g. autoconf 2.69]
 - glibc: [e.g. 2.23]
 - source: [e.g. release or github]

*Note: you can find glibc version by running `ldd --version`*

*Note: if source is github, please include last commit reference*

**Additional context**
Add any other context about the problem here including logs and command line output

**Comment by netniV** [comment]
It is not missing. You need to use bootstrap.

**Comment by Lalbee99** [comment]
The INSTALL readme still references ./configure for unix installation .While looking into the bootstrap option you mnetioned it says it will attempt to install based on  "normal" install path. I always use configfure with override for bin, conf etc..

**Comment by Lalbee99** [comment]
Unix Installation
=================

These instructions assume the default install location for spine
of /usr/local/spine. If you choose to use another prefix, make
sure you update the commands as required for that new path.

To compile and install Spine using MySQL versions 5.5 or higher
please do the following:

    ./configure
    make
    make install
    chown root:root /usr/local/spine/bin/spine
    chmod u+s /usr/local/spine/bin/spine

To compile and install Spine using MySQL versions previous to 5.5
please do the following:

    ./configure --with-reentrant
    make
    make install
    chown root:root /usr/local/spine/bin/spine
    chmod +s /usr/local/spine/bin/spine

**Comment by Lalbee99** [comment]
cacti-spine-1.2.3]# ./bootstrap --help
--------------------------------------------------------------
Spine bootstrap script
  Attempts to configure spine based on a 'normal' system. If you
  install things in non-common locations you may have to use
  the install instructions to build.
--------------------------------------------------------------

**Comment by cigamit** [comment]
@Lalbee99, we would appreciate your support here.  If you would make your recommendations in the form of a pull request, we would appreciate it.  Thanks.

**Comment by Lalbee99** [comment]
I tried, I cannot for the life of me figure the pull request process out. I attempted to let you know you went from having a configure script in Spine (through 1.2.2). If you choose to not supply the configure script be aware that not everyone is placing their spine files in your standard locations. I am currently running Cacti 1.2.3 using a Spine version of 1.2.2 because there was no configure script in 1.2.3 the repository.

**Comment by cigamit** [comment]
So, it's hard at first.  Let me give you the steps from a Windows user perspective:

1) Get a GitHub account.  You are there already
2) Download and install the GitHub Desktop
3) Goto this repository and 'Fork' spine.  Just click on the 'Forks' button at the top of the repo
4) Go Back to the GitHub and clone you Fork to the local system
5) Make you changes to that version.  The default location is Documents/GitHub/spine
6) Once the change is done, you can initiate a pull request directly from GitHub Desktop.

**Comment by netniV** [comment]
Bootstrap should always be run from what I know.  Once you have run bootstrap, then you run configure.  What the instructions are telling you is that we assume the path /usr/local/spine as the folder that you will configure/make/installer spine to if you use only our scripts/instructions.

If you do not run `make install` but instead manually copy the compiled `spine` program to say /usr/bin, then you need to amend the path from /usr/local/spine/bin/ to /usr/bin/.

What is displaying is purely guidance and those instructions for linux in the text files are missing the bootstrap step.  They were updated recently I believe but I will correct that now if it is missing.

**Comment by netniV** [comment]
Please review https://github.com/Cacti/spine/commit/43142d8af86940083ee494d1b08b4be3e84368ef for the changes that reflect my comments above.

**Comment by Lalbee99** [comment]
It did thank you
