### ISSUE TITLE
spine build with libnetsnmp.so.35

### ISSUE THREAD

**Issue by majed17** [Cacti/spine#93]
**Describe the bug**
Today, in gentoo, there was a net-snmp update, and cacti stopped graphing. the issue turned out that running ./spine produces:

./spine: error while loading shared libraries: libnetsnmp.so.30: cannot open shared object file: No such file or directory

sudo find / -name libnetsnmp.so*
/usr/lib64/libnetsnmp.so.35.0.0
/usr/lib64/libnetsnmp.so.35
/usr/lib64/libnetsnmp.so

so the expectation is to release a spine that builds with the new file

**Comment by majed17** [comment]
i rebuild spine and it worked!

**Comment by netniV** [comment]
Normally libraries are built using the non-versioned file which is a symbolic link to a versioned one as far as I remember, but if it does use the version specific one, that will cause an issue.  You can find out using `ldd` i believe.

**Comment by cigamit** [comment]
Yea, it's really dependent on the MySQL or MariaDB libraries installed on the client.  The versions have to align.  Generally, there should be a symbolic link to a non-versioned *.so, but that gets one into problems.  So, if you build with one version of the API, and then you upgrade your database to another version of the API, you have to rebuild.  Going to close this case now.
