### ISSUE TITLE
Increase default 'results_buffer' size to 2048 and MySQL max buffer to 131072 bytes

### ISSUE THREAD

**Issue by paulgevers** [Cacti/spine#94]
This is a [forwarded Debian bug report](https://bugs.debian.org/929323)

**Describe the bug**
	We have several services being checked that return more than 1024 bytes (with_resluts_buffer limit of cacti-spine). This makes it so information doesn't get catalouged by cacti.  

**To Reproduce**
	We use several different scripts, two of which  is a vanrish check: https://github.com/glensc/cacti-template-varnish and percona https://www.percona.com/doc/percona-monitoring-plugins/LATEST/cacti/creating-graphs.html. I assume there are many more packages that require a results_buffer more than 1024 bytes

**Expected behavior**
	The poller should reliably store information more than 1024 bytes. I believe the solution is to increase the default compile option of the with_results_buffer to at least 2048 bytes as services grow to return more data.

**Server (please complete the following information):**
```
Debian Release: 9.9
  APT prefers stable-updates
  APT policy: (500, 'stable-updates'), (500, 'stable')
Architecture: amd64 (x86_64)

Kernel: Linux 4.9.0-6-amd64 (SMP w/16 CPU cores)
Locale: LANG=en_US.UTF-8, LC_CTYPE=en_US.UTF-8 (charmap=UTF-8), LANGUAGE=en_US.UTF-8 (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash
Init: systemd (via /run/systemd/system)

Versions of packages cacti-spine depends on:
ii  cacti                  1.1.38+ds1-1~bpo9+1
ii  dbconfig-no-thanks     2.0.11~bpo9+1
ii  debconf [debconf-2.0]  1.5.61
ii  libc6                  2.24-11+deb9u4
ii  libcap2                1:2.25-1
ii  libmariadbclient18     10.1.38-0+deb9u1
ii  libsnmp30              5.7.3+dfsg-1.7+deb9u1
ii  ucf                    3.0036

Versions of packages cacti-spine recommends:
ii  libcap2-bin  1:2.25-1

Versions of packages cacti-spine suggests:
ii  snmp-mibs-downloader  1.1+nmu1
```

**Comment by cigamit** [comment]
@paulgevers, should be resolved now.  It's a configure option, but I doubled to 2048.  Hope that's enough.

**Comment by glensc** [comment]
in pld linux we are using 4096:
- https://github.com/pld-linux/cacti-spine/commit/74f5a7523b9553a9db4b26130b40b36b1c462f32

i'm also author of the varnish cacti template:
- https://github.com/glensc/cacti-template-varnish

i can't confirm that 2048 is too short, but for me 4096 worked (the change is 9 years old :)

**Comment by netniV** [comment]
I would point out your template only suggests 2048 ;-)

**Comment by glensc** [comment]
I know that. I also can't confirm which one is accurate as I no longer use the template myself and the change was done 9 years ago, and then it was varnish2/varnish3.
