### ISSUE TITLE
spine1.2.4 version number error

### ISSUE THREAD

**Issue by whsir** [Cacti/spine#95]
spine1.2.4 version number error

cacti-spine-1.2.4/configure.ac

AC_PREREQ(2.53)
AC_INIT(Spine Poller, 1.2.3, http://www.cacti.net/issues.php)

**Comment by whsir** [comment]
@netniV

**Comment by netniV** [comment]
Yes we are aware that the version of spine was not incremented. It will be updated on the next release now.
