### ISSUE TITLE
SPINE: Poller[1] Device[1] ERROR: SNMP Get Problems parsing SNMP OID perl /var/www/html/scripts/query_unix_partitions.pl

### ISSUE THREAD

**Issue by velbon** [Cacti/spine#97]
**Describe the bug**
From my log i am receiving this error and don't know what is the issue:
2019/06/25 02:39:30 - SPINE: Poller[1] Device[1] ERROR: SNMP Get Problems parsing SNMP OID perl /var/www/html/scripts/query_unix_partitions.pl 'get' 'device' '/dev/sda1'
2019/06/25 02:39:30 - SPINE: Poller[1] ERROR: SQL Failed! Error:'1064', Message:'You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'get' 'device' '/dev/sda1''' at line 1', SQL Fragment:'UPDATE poller_reindex SET assert_value='U' WHERE host_id='1' AND data_query_id='2' AND arg1='perl /var/www/html/scripts/query_unix_partitions.pl 'get' 'device' '/dev/sda1'''
<img width="1258" alt="Screen Shot 2019-06-25 at 2 50 57 AM" src="https://user-images.githubusercontent.com/8957923/60065679-35c80b80-96f4-11e9-86fc-053d49aa5cff.png">

**Expected behavior**
I am expecting no ERRORS

**Screenshots**

**Server (please complete the following information):**
 - OS: Debian
 - Version: 9

**Additional context**
I am using Cacti 1.1.38

**Comment by netniV** [comment]
If this was normally an issue, I'm surprised that we haven't seen it before.  I would recommend updating cacti/spine to the latest version and testing again but this isn't available yet until Buster is released.

**Comment by cigamit** [comment]
Confirming that we are escaping in the latest spine.  Requires you to be on Cacti 1.2.  You can hand diff spines.  Its in poller.c line: 912 and 913 in the 1.2 code.

**Comment by velbon** [comment]
Dear All,
The issue had been fixed. I think debian was not allowing cacti to have access to its partitions. So when i deleted the sensor the error stops.


Regards,
Gerald
